### ISSUE TITLE
Accessibility Registry

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#106]
The current UX has an Accessibility icon in the right side, but earlier mock ups show multiple accessibility icons. Lets use this issue to hash out all the conditions that need consideration and what we can do about them. This is not to isolate accessibility as its a concern in all aspects of the system, but more so what kinds of accessibility features can be put into the platform to enhance the experience for those in need of things beyond the obvious keyboard navigability / alt tags.

@kfurst brings up several considerations, especially for a K-12 audience perspective which are great to take into account. #88

## Accessibility Registry / profile
One of the earlier mock ups had a system / profile level accessibility icon. The thinking here is that we'd have accessibility settings that could be set globally. An example of something that you could set globally might be that you have an issue that requires you to have high / reverse contrast so you check the box for using the network in high contrast mode, and then all systems as you go to them respect this setting.

Others could be things like auto scaling all interfaces for those with poor eye sight, removing text based navigation, adjusting font styles, etc. The key is to think of how we can systematically improve the experience for those that need specific modifications, taking our usual network based approach.

There are other threads that talk about a profile authority / inbox which might be the home of these pieces of data but lets not worry about where it goes for now, just that there's accessibility influencing details about a user coming from somewhere and correctly affecting any service we build to aid them.

**Comment by rickhumphries** [comment]
I like the idea of the global accessibility settings. I think there should always be the chance to tweak the settings easily though wherever you are without returning to the inbox authority etc. There's also always local accessibility stuff like the speed reader and text-to-speech etc. So maybe the accessibility button would sit well in the LMSless (is that what it's called?) global menu that will be prevalent and carry certain settings around to each system.

We currently recommend ATbar (https://www.atbar.org/) which might give some ideas of things to include. Although it's something that students need to add themselves rather than having it built in

**Comment by btopro** [comment]
Very cool idea w/ atbar; definitely something to draw inspiration from.  The goal w/ the architecture is to have the system / authority fade to the background in most instances. Much like you have media piped into the content without the learner knowing, we'd propose a similar idea with inbox / profile settings.

**Comment by btopro** [comment]
Added to roadmap / CPR so closing this out
