### ISSUE TITLE
Pipeline project: Phase methods

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1162]
List of individual methods (scaffolding that will help students matriculate through the creative production pipeline). The pipeline will have 4 phases, and the methods may not be relevant or desirable for all types of projects. I will add more of these over time.

[Double Diamond Pipeline:](https://dmd-program.gitbooks.io/dmd-course-materials/content/topics/double_diamond.html)

**Phase 1: Discover**
- [ ] Define your audience
- [ ] Journey Mapping
- [ ] Interview

**Phase 2: Define**
- [ ] Card sort
- [ ] HMW question generator
- [ ] Insight statements

**Phase 3: Develop**
- [ ] Brainwriting

**Phase 4: Deliver**
- [ ] Plot diagramming
- [ ] Wireframing

**Comment by btopro** [comment]
https://dmd-program.github.io/pipeline/

**Comment by btopro** [comment]
@heyMP we'll want to talk about this at some point, maybe in a week or two after you've put some more work into Math033. We'd like to see the guts of what's going on w/ that branch as well as see how we could unify in some way to account for "projects" which are made up of hierarchy (structuring of assignments) so that then visuals like the pipeline above can be accomplished (as well as other things if just visualized differently).

**Comment by bradallenfisher** [comment]
if you guys talk about this please include me.

**Comment by michael-collins** [comment]
Interface prototype: https://dmd-program.github.io/pipeline/

**Comment by btopro** [comment]
@michael-collins get some sleep. you keep reposting yourself in these threads :)

**Comment by btopro** [comment]
merging this into #1251
