### ISSUE TITLE
Materialize and Animate.css

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1186]
We're at the point where we're beginning to create a series of really short courses that are more like knowledge top-ups. So we're experimenting a bit with different styles and effects to make them visually appealing. 

[This demo](http://giphy.com/gifs/3o7TKwuXygQLdnk784/fullscreen) shows the kind of thing we're looking at by using https://daneden.github.io/animate.css/. I admit that some of the animations are a bit OTT but simple ones can be quite effective. I think the next step would be to implement something so the animations are only fired once the user scrolls down to them, so I was wondering what the level of materialize.css integration was in 0.4.0? Because I'd be interested in utilising ScrollFire (http://materializecss.com/scrollfire.html) to achieve this.

Also, wondered about using animate.css as part of HAX (eventually) or Media to be able to easily create these?

Another thing to factor in is accessibility. If we implement a style with a different background, or a text box where it's white font on an orange background (or something), would this require an accessibility setting that forces the background to be white again, or forces all divs to have a white background color etc.? Not sure.

**Comment by btopro** [comment]
So Scrollfire is in scope but we need to trigger it. This might actually be a good use of #1069 angular directives because it would be MUCH more usable to do like
```
<div fadeInFromLeft>The content I have</div>
```
And then Angular write the scrollfire code automatically when it notices that directive.  The example pointed to in 1069 actually has some minor scrollfire support http://krescruz.github.io/angular-materialize/#scrollfire

Again, we haven't implemented this yet cause we'll most likely want to roll our own fork of this so we're not including the kitchen sink that they have (or we'll want to extend) but throwing it out there.

**Comment by btopro** [comment]
scrollfire should allow for this
