### ISSUE TITLE
Proposal to change any connotation of "outline" to "book" in mooc

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1188]
## Proposal

Within the MOOC distribution we replace any references to 'outline' to 'book'.  For instance, in the Course Tools Menu, we would change 'Outline Designer' to 'Books', and we would change 'Import Course Outline' to 'Import Book'.
![screen shot 2016-08-19 at 8 56 52 am](https://cloud.githubusercontent.com/assets/3428964/17810453/29e2b910-65eb-11e6-8dba-8e17001e7684.png)

We can also redesign the '/admin/content/book' page to look more like a book shelf.  For example:
![screen shot 2016-08-19 at 9 00 01 am](https://cloud.githubusercontent.com/assets/3428964/17810482/5de768be-65eb-11e6-8511-e82c508f0592.png)
## Justification

There are two words to describe one thing, 'outline' and 'book'.  Drupal's term for the functionality is book so it appears in the vast majority of urls, page titles and menu links.  This is causing confusion for users of the system who think there is a difference between the two.  The book shelf design will also make it slightly easier for the instructors to see which book is available for which section, which I have a surprising amount of users who don't grasp the concept.

**Comment by btopro** [comment]
I agree we need a standardization of language; might be good to have a workshop day with different IDs and some faculty to just get language in unity and challenge connotations.

This said, Book is a powerful connotation that this is literally just an online text. You don't generally watch videos in a book or any of the other interactive stuff going on there. I think we could get past this connotation but this is really important because the picture painted of a book store is very different from a course / courses. Then if on interfaces to students it says "Book outline" or "read this book" or wahtever, again, very different feel from 'course' even

@rickhumphries

**Comment by btopro** [comment]
Thoughts on having like a 1/2 day workshop w/ targeted faculty where we take notes while they build out a course and answer questions they have. Basically a faculty centric usability study, after having a staff centric usability study (much less formal though, just a lot of questioning assumptions and taking notes).

@michael-collins @kat-wehr @heyMP @bradallenfisher @kmiffitt --^

**Comment by heyMP** [comment]
Yeah I would definitely concur with doing a workshop like that to get the connotations and verbiage unified.

**Comment by rickhumphries** [comment]
Again, agree about the standardisation and I'd agree with @btopro - I'd be careful about using book everywhere. When I'm explaining to staff or students about the course 'book' they don't really know what I'm talking about, but if I refer to the course outline, course content, or course material then that seems to be more recognisable for them. Like the idea of the shelf showing the different outlines though, or having it styled in a similar way

**Comment by btopro** [comment]
Course
Course Outline
Course Content Outline
Course Outline Designer
Import Course Outline

A course to us internally as staff / builders, a course is a network. But to students, the course is basically the outline and the experiences they have as pegged off from it. So is it referred to as Course to the bulk of student focused use-cases?

**Comment by btopro** [comment]
previous commit at least makes
Outline Designer -> Course outline designer
Import Content outline -> Import course outline

positions us more towards having some kind of name consistency which is 1st step to making it one vs another way of describing it

**Comment by btopro** [comment]
default registry title from:
Content outline -> Course outline

**Comment by michael-collins** [comment]
I have somewhat strong opinions about this, bear with me. I thought a **COURSE** was a cluster of tools networked together? Is the "Course Outline Designer" also designing and outlining the other tools in the course network? I've always preferred Content Outline because it's more descriptive of what you see in that corner of the system – an outline of content. Consistency is very important, but I'd also like the tool to be honest about what it is.

If Course Outline Designer instead refers to the fact that you are editing an _oultine_ that happens to be in a course, then it's a redundant modifier, a bit like _Course_ Media and _Course_ Discussions.

Thoughts?

**Comment by michael-collins** [comment]
On the other hand, the Outline Designer also incorporates the flow and structure for learning the content, though not entirely. This suggests that maybe this tool has an identity crisis...

**Comment by btopro** [comment]
As we move forward, would your opinion change if you clicked the Add + at the bottom while on a page and then said "Studio assignment". Which then you filled out a form (while in course system) which then (on the backend) makes a space in studio, and appends the submission widget / display style to the page you were on.

In effect, you'd start having a workflow where you are injecting / appending / manipulating the entire course via the system that claims based on URL that it is for courses. Can you still go to the studio? Yes. Are there times that UX / UI requires advanced usage patterns where you have to go there. Sure. Would communicating via outline and unifying creation / orchestration of those other systems to be in the flow of material improve usability both on production and student in take? I'd hope so.

This is the course system for orchestrating a course. If that's the stated context, does it make more sense (asking, I know we're shifting bc of usability improvements).

**Comment by kat-wehr** [comment]
Like Collins said - what does this tool DO and let's name from there as opposed to trying to nail down what words mean what to which stakeholders, because we could discuss that for days. :)

**Comment by btopro** [comment]
@kat-wehr discussing for days is important for sure. My shifting was a bandaid so there was some convention which we can then break from and have hard discussions about instead of a mix of wording.

**Comment by kat-wehr** [comment]
@btopro Based on your latest comment, I feel like "instructional outline" might be a good fit. But I also like the idea that was posted a while ago about actually asking the folks who use the things to figure out what feels natural to them.

**Comment by btopro** [comment]
@kat-wehr I don't disagree w/ the taking feedback part though I feel people's mental conception will change completely when the UX golden spikes keep being driven. If I used my voice to command elms to setup a network of systems which happens to build instructional outlines, and happens to build studio assignments, and happens to integrate them. Then when I go to update / manage them after the fact, if I do so via the content outline; we have the conflict of "I need to change an assignment due date. Better go to the content outline...."

CIS dashboard could trump my connotation entirely.

I also personally like Instructional outline BUT when we allow for things like #640 a non-linear path isn't really an Instructional Outline, it's not a book, at that point it's not even really an outline. So, mixing things up for our days long conversation :)

**Comment by michael-collins** [comment]
Okay, yes my opinion would change if that's how it worked. With my limited interaction, I've only been modifying book-style content and image media.

However, a question I have is, and it's more of a high level one now, are the way things are being constructed with this tool now making it impossible to maintain a book of content? Perhaps the idea of content being a book was never possible. the content within the outline is not modular since it doesn't have it's own service. Studio, assignments, etc are stored in a modular fashion, and embedded within written content. That content can't be separated, filter and searched in the same way a piece of media can, and therefore can't be as modular.

The paradigm I'm describing would be like if you took my gitbook and imported it into a Book Service that manages books. This would also be able to import any OER content in the way that the OERSchema remix tool does. Then as modular assets, you drop them into the course outline service, that manages the flow and organization of the course.

**Comment by michael-collins** [comment]
Also, this would make git syncing more possible :)

**Comment by btopro** [comment]
@michael-collins OERSchema would be settings we could read off, strip out the content from the interactions and generate both. #827 LOR is also a far out place that would be for storage of "books" if you will which would be open to anyone, git import would go through here, then a course could start by forking a book in.

All of the above we're talking stuff over the next yearish, realistically.

As far as your comment on "can this just be a book" yes.  Git syncing will still be possible bc we'd just interpret / remodify the OERSchema head-matter.

**Comment by michael-collins** [comment]
Ah okay, that sounds pretty cool. I didn't realize what an LOR was and #827 does help much...

**Comment by btopro** [comment]
still in idea stewing land for sure :)

**Comment by michael-collins** [comment]
Perhaps we can appropriate the word Outline. Other words to think about: digest, synopsis, program, slate, plan, map, shape, frame, structure, shell, skeleton, scaffolding, foundation...

Those building construction words are fairly relevant. Just, for the love of all that is holy, do not call it elms360.

**Comment by kat-wehr** [comment]
Instructional Map sounds nice, especially since that works even for the nonlinear learning experiences.

**Comment by btopro** [comment]
These conversations will continue in #1758 as the UI implications have implications for this connotation. The screenshots illustrate the age of this issue and that it's starting to be unified with content outline, book, and instructional outline all being unified under "content" in current mock ups. The Book shelf connotation is a powerful one too which I think Course = Book as we move closer and closer to a unified UX pattern where everything is a faccet / app in a course instead of a stand alone thing.
