### ISSUE TITLE
H5P Drag and Drop is Wacky

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1241]
Having issues creating a drag and drop activity. Setup appears to be fine, but when you save and then try to check it, it gets all weird. 

The drop zones were moving after I saved the interactive. I think I fixed that by just resizing them for some reason, seems to have done the trick. The display for the draggables doesn't "stick" though. See the labels on the screen shot below: 
Backend setup: 
![screen shot 2016-09-13 at 4 04 22 pm](https://cloud.githubusercontent.com/assets/15616523/18489496/c7a80c88-79cb-11e6-9d2b-ba8bba6bea9a.png)
Display: 
![screen shot 2016-09-13 at 3 56 58 pm](https://cloud.githubusercontent.com/assets/15616523/18489469/ab271734-79cb-11e6-90c5-17dc12e89931.png)

The draggable answers won’t register as being placed correctly even though they're checked off in the appropriate drop zone in the settings.
Backend: 
![screen shot 2016-09-13 at 4 05 08 pm](https://cloud.githubusercontent.com/assets/15616523/18489524/de0ba746-79cb-11e6-9935-b310c9369416.png)
Display: 
![screen shot 2016-09-13 at 3 57 18 pm](https://cloud.githubusercontent.com/assets/15616523/18489475/b3ae988c-79cb-11e6-894c-908d21f23abb.png)

Also, the opacity settings aren't working. Nothing is coming up at 50. 

Not super high priority since I can do something else (i have a cool image hotspot that I included this information on) but just thought I'd point it out.

**Comment by btopro** [comment]
@kat-wehr did u try embedding this in a page and see if it's still screwed up? For now there's not much I can do about h5p issues other then direct you to their queue to post this https://h5p.org/forum

**Comment by rickhumphries** [comment]
@kat-wehr the issue with the correct answer not registering is because, with the option you've selected for the drop zone on the text element, it isn't saying 'Resources and Risk Management is the correct answer for Human Resources text', it's saying 'I'm allowed to drag the Human Resources text ONLY onto the Resources and Risk Management drop zone'. Try dragging the Human Resources text onto any other drop zone and you'll see that it won't let you.

Instead, choose 'select all' so that all the drop zones are checked, then click and edit the actual drop zone itself. There should then be an option to then select 'Human Resources' as the correct answer for that dropzone.

I'm not 100% sure on the other issues though or what you mean by the labels don't stick. I usually click 'show label' on each drop zone though to give the drop zone a title:
![image](https://cloud.githubusercontent.com/assets/4973810/18503257/cc19b748-7a53-11e6-9e08-bbd60ce58f36.png)

In terms of the 'task size' I usually pick settings that are in the ballpark of what I might expect the width of the area I'm embedding into (i.e. the content area in Courses) to be - so the authoring part best reflects how it'll actually turn out when you click 'save'. I tend to change it to 1000 x 600 usually as a strange rule of thumb:
![image](https://cloud.githubusercontent.com/assets/4973810/18503343/66e0acdc-7a54-11e6-81d6-aaa0461f1a1a.png)

Hope that helps a little

**Comment by btopro** [comment]
closing out since Rick is saying it's a settings issue. @kat-wehr reopen if this isn't
