### ISSUE TITLE
Support a global color value in the theme

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#127]
I would like to change the color on the title page to match the colors in the course - thanks!

**Comment by btopro** [comment]
Rock institute's instance has a hard-coded color property. It would be ideal to add this type of slider setting directly into the theme though so that it could be tweaked / exported. This would allow a color for the theme which would dictate headings and other touches of color throughout the content and the ID / faculty could align the color with their banner / any other association they'd want.
