### ISSUE TITLE
Timeout on roster sync for large number of users

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1271]
**Version**
0.2.0

**Steps to reproduce the bug**
1. Go to https://courses.{yoursite}.co.uk/{course}/cis/section-list
2. Edit and save a section with large amount of users
![image](https://cloud.githubusercontent.com/assets/4973810/18689120/7670e880-7f7f-11e6-8e4d-0d05c99bcb85.png)

**Expected behaviour**
The roster sync should pull users from CIS

**Actual behaviour**
The roster sync through this method is timing out, I'm guessing due to the large number of users.

**Additional information**
I'm not sure if any of the stuff done for 0.4.0 will help with this but I thought I'd raise it since I know we have a different enrolment setup to PSU, where we have continuous enrolment of students throughout the year - which can result in very large user numbers within a section.

**Comment by btopro** [comment]
Yes. 0.3.1 puts in place things for this though your custom processing of rosters may be related. How many students we talking in single shot?

From Mobile

----- Reply message -----

**Comment by rickhumphries** [comment]
Yeh, so we've got an overnight cron which kicks off all the roster syncing for all courses I believe. That's currently not syncing that course either so it's something to look at after the upgrade. 

That particular course has 1,781 users. The CIS currently has 37,222 users so we'll be approaching those numbers for people enrolled on courses eventually. For the time being though we've only actually got a small number of courses setup, so that equates to 6,500 who are actually being synced.

**Comment by btopro** [comment]
0.3.1 introduces the background callback structure for syncing. This ensures that each course syncs as a single process and then moves on to the next one (kicking it off in the background each time). This ensures that it'll sync eventually but that the cron job isn't experiencing the load of it.

That said, 1781 users in a single shot still might be a bit much for it unless execution time is set higher. After upgrade we'll see, may just need to allow php to run longer. It's also possible that the sync routine you were using (since you sync users into CIS / ran ahead of us a bit on that area) may need some tweaking to utilize the background call mechanism. We'll see when we get there.

**Comment by btopro** [comment]
Let us know if post upgrade this still occurs

**Comment by rickhumphries** [comment]
Will do. Upgrading this week so I'll test over the weekend and let you know

**Comment by btopro** [comment]
Sounds good. We typically test somewhere else other than local development before rolling live bc of our customizations. Also worth noting we usually run 1-2 releases behind the active one, then upgrade during semester downtime. Currently we run slightly past 0.4.0, but what's in 0.5.x yet. Our next upgrade window is probably in November unless we are feeling adventurous. Just an FYI so you can make sense of the versions and where you peg to them.

**Comment by btopro** [comment]
@rickhumphries after the vendor sorts out the current xml import issues we'll want to retest this

**Comment by rickhumphries** [comment]
@btopro I think the cron will sync the roster when it runs, but when saving the section as described in the initial issue post, it still times out. It would be good to utilize the background call feature in any case if possible. We may hit on this tomorrow

**Comment by btopro** [comment]
@rickhumphries I'll have to look at your sync methodology cause this happens in the background for newer deploys / upgraded deploys *but* there's a hook name that changed in order to utilize the backend method instead of the front-end method. The front-end method also used to be kicked off by a course's cron calling home to CIS. Now, CIS brokers the entire transaction and does so in a back-end request method that is X+1 requests per X courses. So 100 courses will actually call 100x to CIS behind the scenes (in serial) to give it a better chances of completing the portfolio.

If switching to this doesn't get the job done fully, we may want to do a trick where those backend threads can run as long as they want (at a php layer). How big are your "rosters" for sections?

**Comment by rickhumphries** [comment]
@btopro OK sure, that makes sense. The course above now stands at 1,950 users so it's a biggy. We reach those kinds of numbers because we keep enrolling and there's no real process for archiving once they've completed etc.

**Comment by btopro** [comment]
hmm... so there's nothing that indicates they've completed? Now, once they exist it's a lot faster cause it goes "oh ur here i wont make u" but yeah it still could take awhile on that sorta course size if it's having to make them every time (or attempt to)

**Comment by btopro** [comment]
the sections / roster / courses all sync at the same time so it's possible that 1 craps out cause of the other

**Comment by rickhumphries** [comment]
No, there's nothing to suggest it completes or is attempting to do it in the background (like it does if you try to sync the roster from the CIS). The browser egg times for a while then I get a HTTP Error 500 - 'unable to handle the request' message.

**Comment by btopro** [comment]
yeah this isn't possible anymore (for a human to experience it)

**Comment by btopro** [comment]
Haven't fixed yet for sure but proved at least this is the same as #1589
