### ISSUE TITLE
Course Overview Dashboard

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1336]
Kind of related to #1307 (in that we're talking dashboards). Could the CIS become the place for an 'individual course dashboard' of sorts? So it's almost an overview of what's been going on with the course recently. Any recent course updates, any course-wide announcements, recent blog posts, or forum topics that have been added etc. 

I see that as the natural home of https://online.whatever.com/course-name/. You could then possibly have a slightly different dashboard view depending on your role - so staff might see a dashboard widget showing the different tools that are plugged in too, whereas students wouldn't see that. Thoughts?

**Comment by rickhumphries** [comment]
Or perhaps this would make sense as a Service instead

**Comment by btopro** [comment]
I think this gets intertwined with #629 #484, etc.  With the new usability patterns emerging, and the next steps from there, I believe it will start to become clear that none of these things matter (let me explain):

The more the usability improves and the integrations between systems becomes a more seamless user experience, you'll start forgetting "where am I" and just be. So I'm not sure that it'll matter if I'm in people.whatever or online.whatever or inbox.whatever or whatever.whatever; so long as I can get logical information at that time.

The first step in my mind is a unified user profile that provides stupidly unified UX. By that I mean, the user should be the user; not knowing or caring that they are a person across multiple platforms, systems, drupal databases, user ids, etc. They are themselves. So if I click my picture / view profile. I won't care that it's courses.wahtever/coursename/user/me or people.whatever/user/me . I'm just me becasue the UX / data have been stitched together completely.

If I click edit, I'll barely notice that I just went to another URL to update my profile. If I hit save and it redirects me back to my profile in the context of the course or system I was using, same thing.

You're still way ahead of us on the "single user dashboard" approach as mentioned in CIS / online. I'm not entirely opposed to that but I'm also not entirely sold either because of previous issues that caused us to fork CIS into a 2.x where we had a marketing site in the same place as the course controlling / creation arm. We broke off the marketing side from the course controller brain connotation for this reason.

In the same way then I'd ask: Should students be logging into the course controlling brain platform? I'm not sold either way as you have valid points and your usability patterns at Buttercups are far better via customization then ours.

For now: I'd say let's keep hashing out these conversations and see where things go. I'd like to go Profile, then distributed profile, then LRS data sprinkled onto things that make sense, then sprinkled onto user profile specific to course they are in. I think once we have that stuff, like the "how am I doing in this course" Then it'll help inform the "ok, now what would an overview of overviews look like / where should it go".

**Comment by btopro** [comment]
I'll also say connotations of how CIS functions will change drastically if the #1051 / CIS Dashboard project to "angularize" it keep progressing. @curiosity26 has been getting ready to get his hands dirty with it and a highly unified / usable CIS that can fully orchestrate the rest of the system setup might change opinions (either direction) about this discussion.

**Comment by rickhumphries** [comment]
Yeh, the unified UX will definitely make these things not matter from a student point of view. The 'course dashboard' as a thing kind of came up in #851 so in terms of it being a tool, I think it's a good idea - it's almost just finding the right place for it. As you said, it'll work itself out.

I'm kind of expecting to move a lot of the custom functionality we've done in terms of the the single user dashboard over to 'People' at some point anyway - so I'm not apposed to having that live there and leaving CIS as a pure course creation authority either.  

Also, we're starting to work on the designs for having a reporting area of the site where a manager can quickly view data such as 'Within this region, 34% students have completed Course X, 55% are on target, 11% are behind target' etc. My initial thoughts are that I'd like to use Angular for this too, and that it should live in the People authority - so whether we could share ideas on the angular work too, I'm not sure. But I'll keep sharing what we're doing just in case.

**Comment by btopro** [comment]
@rickhumphries ooooo. so that 2nd use-case makes me actually think less people and more something in CIS. if CIS was like the administrative system (mental context). You'd put all reporting / administrative staff / management stuff there. "Where do I add a user / associations / Feed the system so we can all get paid and people can all get their stuff?" CIS.

Students getting the same style boiled down info maybe that comes from elsewhere. Definitely go towards Angular (2 if possible) as @heyMP and @curiosity26 are working in that direction so there'd be room for collaboration more easily / debugging as needed.

**Comment by btopro** [comment]
consolidating discussion around #851
