### ISSUE TITLE
CIS Shortcode / Markdown import conflict / testing

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1404]
In reference to #1401, CIS shortcodes currently aren't supported by the markdown filter. Figure out what the conflict is

**Comment by btopro** [comment]
ha, corrected :)

**Comment by btopro** [comment]
@bradallenfisher is picking up anything git book / book copy universe as a reference for why i've tagged him on all these related issues

**Comment by michael-collins** [comment]
Ha, @btopro that's a lot simpler than what I wrote.

**Comment by btopro** [comment]
this is insane that this was the actual issue. Can't save a node while interpreting it *for the purposes of calculating course context*. This is a check it would have failed on anywhere. I have almost no clue why this wasn't an issue previously other then (maybe) the multiple filters cause additional handoffs of how to filter the content, leading to a more complete cache clear.

Effectively, the page save was asking what the context was so it could make those nice whindy wheel links. When it tried to figure out "what course are they in" so the link would redirect back after save of media (for example), it would ask the node (currently being saved) what the context was (even though it didn't need to). This triggered the same interpretation on the same thing, which is then circular. Killing the page request stops the loop and because we're using asynchronous writes to cache bins most likely it would show up eventually in a background thread.

This is one of the more insane things I've ever found in here AND it only would be reflected for content authors (students would just see content)
