### ISSUE TITLE
Set Base Path when Angular app is on Drupal site.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1586]
Stupid problem, but problem none the less.  Your classic chicken or the egg.

We need the App to dynamically set what the base path is for its http calls.  To do this, we created a new endpoint at `/api/v1/elmsln/user` which contains base path information.  However, the app doesn't know the full address to call because it doesn't have the base path set.

**Comment by btopro** [comment]
@heyMP what about this idea:

You include the base path in a static json blob in your app. The App ONLY uses this IF it doesn't find the following JS value:

```
Drupal.settings.basePath
```

If that variable is available to the page (I think it already is) then it uses that, otherwise it uses your one marked for development purposes.  Minor pin-prick in the pure disconnected app but minor accounting for the deployment location; thoughts?

**Comment by heyMP** [comment]
Yeah I think that will work fine.  We are already using the Drupal object to check if we need to use basic authentication or not.

**Comment by btopro** [comment]
Oh, well then I'd say use that. `Drupal.settings.basePath` is available to every page

**Comment by btopro** [comment]
have u resolved this? seems like an easy one, just trying to clear the list a bit

**Comment by btopro** [comment]
Solved by @heyMP awhile ago,... uhh... last night in a house in the wood. One man, was able to do, what no one else in the repo could. Fix, the most epic problem,.... of his career.
