### ISSUE TITLE
Outline Designer 3.x / Types revisited

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#160]
@btopro: In reference to the index page, if those body fields could be edited inline on the page with a floating edit bar, that starts getting us pretty close to a HAX interface minus layout features with significantly less work.

We could print an 'edit' and 'settings' button above each rendered node and display a little plus button between the rendered nodes that would trigger a modal popup to add a new node/content. But then the expectation for editing all other pages becomes that interaction style, so we would have to think about how to make editing everything else feel cohesive.

One other thought is that if we are just using shortcodes, is it currently possible to embed a page in more than one place? I'm assuming yes, but we should think of a way to make that visual as well. Currently, we can nest nodes via outline designer, and if the parent level node is set to index, it will render the nested pages. However, if you want to have a nested node render in multiple places, you have to clone it or create a new page and embed the desired content's shortcode. I am imagining some kind of "create node instance" button which generates a new node with a shortcode reference to the original content.

**Comment by btopro** [comment]
So edit module allows in place editing.. it's confusing bc of the other methods of changing things like you said. It's core in D8 and I find it to be incredibly distracting (personally) but I agree it's an overall direction we're heading https://www.drupal.org/project/edit

**Comment by michael-collins** [comment]
Okay, that's helpful to know for the second half of the issue. Did the other problem I described make sense?

**Comment by btopro** [comment]
yeah pages can be embedded all over the place via the remixables, anything can go anywhere. Or are you saying we should have a content type that's like "reference page" or something and you copy and paste a short code into it and it's literally a by reference page in its rendering, nothing more?

**Comment by michael-collins** [comment]
My point was, how can we make it simple for people to have the same content embedded in multiple indexes visually in the outline designer hierarchy? You and I know that we can create a node, name it the same thing, and then paste the shortcode. But why can't that be one step? Click a button, generate an instance, and drag it to another index page in the outline designer. Perhaps it visually indicates that it's an instance of the original content. I don't know if the node should be by reference only, maybe it should. Perhaps there can be a "make unique" button to allow for editing, which would break the connection to the original reference.

**Comment by btopro** [comment]
human capacity, this is a good goal for capabilities in Outline Designer 3.x because I feel like that's what your creating needs for in. 2.x (the current version) can't possibly be worth adding these things into given how stable / little context it has of what we're doing, these connotations would provide API bending / breaking in that project. A thread that all these ideas get related to here for Outline Designer 3.x would probably be the way to go with a bulleted list of desires for it.

We'd want to query available options with this "reference page", ask where it lives, then query / auto complete and on save store the correct remote (or hell, local) piece of content so that it can be updated remotely as well as allow for the breaking connotation.

"Breaking" would basically be a workflow thing where
- [ ] content type changes to a page
- [ ] content from the remote (or local) address is loaded up in a rendered state then injected locally into the node that's being changed to a page content type
- [ ] heavy cache clearing cause this could be evil (content type switching is something that outline designer allows, not drupal nessecarily :) )

Like the idea, we've had remote page in the queue for awhile, the token / copy and paste step could be a good bridge to this later ease of use.

**Comment by michael-collins** [comment]
Yes, perfect!

**Comment by btopro** [comment]
merging into #355
