### ISSUE TITLE
learning lock integration question

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1605]
- ELMSLN 0.7.x
- For learning locker integration, do I need to install leaning locker? What locker url shall I use when registering learning locker?

**Comment by btopro** [comment]
@lizatgit you will need to install that as a separate thing. We suggest putting it on its own server since it's its own kinda animal.

https://elmsln.readthedocs.io/en/latest/lrs/LearningLocker/

URL is up to you but I'd recommend something that matches the rest of the pattern for sanity. Ours is lrs.THERESTOFTHEDEPLOY

**Comment by lizatgit** [comment]
OK thanks!
