### ISSUE TITLE
Concurrent course content display for instructors

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#163]
In the context of an interdisciplinary program, a core course would serve to tie together the concepts taught in the different disciplines that a student is concurrently enrolled in. In a perfect scenario, an instructor could look at every week 4 course topic and assignments and generate discussions based on that. For example, if in a programming course, the a topic was feedback loops, in a design course, the topic was animation, and in a communications course, the topic was framing, an instructor could compose some really interesting week 4 discussions that built upon the content of the other courses. This would create a kind of content banding, which a system like ELMSLN could make possible given the an ideal enrollment scenario. A display of concurrent topics would make the instructors job much easier.

Perhaps there would need to be a viewing mode in the CIS dashboard.

**Comment by btopro** [comment]
yeah that sounds like a CIS kind of thing. It also breaks from the current query modalities which are within network as this would span networks. Cool idea but would require a different kind of query style then our current APIs allow, also would need a data-bit in CIS that would suggest courses are related (program or department could provide this since right now they aren't really used).
