### ISSUE TITLE
embedding video with captions

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#167]
I read some of the issues Rick was having, but I don't understand all that code talk. I tried the embed code provided by JWplayer and it doesn't work. I tried to add a link to external video, but it's not supported. I need the closed-captioning from JWplayer. How can I get this to work? 
![2015-08-06_1548](https://cloud.githubusercontent.com/assets/1186260/9121825/eeb140ea-3c52-11e5-8585-cce7d6c493a7.png)
 
Link to page I tried to embed on: https://courses.ed.science.psu.edu/chem202/node/81 
Thanks.

**Comment by michael-collins** [comment]
If you upload the video instead of create a link to external video (only vimeo, youtube are supported on that), you can upload the captions directly.

**Comment by btopro** [comment]
@juststormy two things: copy and paste of JS needs to be done into the "source" view otherwise it evaluates the snippet as text and not code. Also I needed to disable the filter (much like the footnotes thing from before) because it was actively blocking javascript.

We'd need to provide direct support for bitsontherun / jwplayer cloud streaming of the file, which is possible via APIs to do so but currently doesn't exist.

**Comment by juststormy** [comment]
@michael-collins got me fixed up. I realized you could upload caption files. Sorry for missing that.
