### ISSUE TITLE
spacing after videos

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#170]
So, I figured out how to insert my short links, and collins showed me how to code the size for full screen. So, I went with width+640 and height=640 because when i go full screen, then the captions fall below the video into the black space. However, that seems to create a buffer between the video and the text when it's not full screen. So I have this big glob of white. thoughts? https://courses.ed.science.psu.edu/chem202/node/15
![2015-08-07_1025](https://cloud.githubusercontent.com/assets/1186260/9137905/cb7a2e88-3cee-11e5-800a-209e2c718622.png)

**Comment by btopro** [comment]
so it appears to be after the video but it's actually an issue with the video / media window itself. We need to modify the way that the output is styled (mediaelement widget) so that it's not setting a height / width. What's happening is the code to render it in the course is scaling it responsively BUT the frame itself is not. This gives the giant white space.

Course of action is to make it not set properties in the frame and then it should auto-magically work.

@heyMP @michael-collins we do need to think about how we'd like to present video other then the lazy method of "oh, full width 100% responsive". Something like borders / padding to present it consistently would be key.

**Comment by michael-collins** [comment]
Well, defaulting to 100% width by 400 height is never a useful dimension. So that needs to change. However, well need to find some inspiration. I'm thinking constraints based css of some kind...

**Comment by btopro** [comment]
#96 related

**Comment by btopro** [comment]
@heyMP did you ever fix this?

**Comment by btopro** [comment]
verified in your current install this isn't an issue thought he #975 thread cleans it up even more
