### ISSUE TITLE
LearningLocker and php 7

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1732]
Has anyone installed LearningLocker with PHP 7.0? It seems the current LL works with PHP 5.5. PHP 7 has an updated Mongodb extension which causes errors for LL installation. Is there a way around, or is there plan to move to LL2.0?

**Comment by btopro** [comment]
Interesting, no I haven't yet. Ours runs on php 5.6 I believe. We've got this one on a separate server since its it's own solution Entirely.  Haven't played with 2.0, most gains seem in UI from what ive seen though I haven't paid attention in awhile

**Comment by btopro** [comment]
http://docs.learninglocker.net/installation/ official docs don't mention anything beyond Ubuntu 14. I'd wait for U16 support from them (which would signify this works) and setup a Ubuntu 14 setup (which they have docs on how to do). 14 is pretty fast out of the box and there's very little PHP processing associated with Learning locker since most power is handled in the database / mongo
