### ISSUE TITLE
Usability Eureka

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1758]
This is where we are today:
![2017-01-19_08-55-11](https://cloud.githubusercontent.com/assets/329735/22109273/0b327840-de25-11e6-9ad0-c11f57832170.png)

*these are mock ups meant to generate discussion*

Not accounted for in this yet:
- Help / Syllabus / Resources as pervasive options
- What this looks like when on an authority (tho very similar)
- What the menus look like when expanding user, course, section, or tool based menus
- Programs, though they'd play into this design paradigm very easily (which could have visual implications when in progam)

The light bulb went off while working on a different issue ( #1754 ) . This is a mock up of a possible next iteration of our LMS-less bar which would allow quick switching between courses, quick operations (like creating courses from the bar if in an authority system), quick situational awareness gaining (I am me, In this course, in this section). Quick ability to change settings (knowing what they are related to, section, course, user, tool). Future expansion into notifications per situational item (hey there's a new comment on your work in studio w/ alittle 2 in a radial burst next to the Studio tab). Quick visibility and access to all applications in our course experience. This also works well on mobile (screenshot 2)

![2017-01-18_23-38-39](https://cloud.githubusercontent.com/assets/329735/22093968/00108aee-ddd8-11e6-8ac5-636efa50c86f.png)

Mobile
![2017-01-18_23-46-33](https://cloud.githubusercontent.com/assets/329735/22094098/c9539fa4-ddd8-11e6-8c1f-3d3237d66727.png)

Slight style tweak w/ support for notification badge
![2017-01-18_23-56-46](https://cloud.githubusercontent.com/assets/329735/22094223/d3b2d3c4-ddd9-11e6-9a76-8ed1a48ce493.png)

**Comment by btopro** [comment]
some more color / small variations

![2017-01-19_00-53-15](https://cloud.githubusercontent.com/assets/329735/22095362/2bdb010e-dde2-11e6-86f0-012ca4245aee.png)

![2017-01-19_00-56-34](https://cloud.githubusercontent.com/assets/329735/22095364/2e863b62-dde2-11e6-91e2-6c0e03c9a488.png)

**Comment by btopro** [comment]
darker, in same color family (amber)
![2017-01-19_00-57-39](https://cloud.githubusercontent.com/assets/329735/22095387/4b0ef1ca-dde2-11e6-8e49-8c2a4a1bf917.png)

**Comment by btopro** [comment]
active application shifted all the way to left, user darkest variation, course / section context slightly darker then normal variation
![2017-01-19_00-59-41](https://cloud.githubusercontent.com/assets/329735/22095423/93b2f980-dde2-11e6-98ee-46b2e2d186ab.png)

**Comment by btopro** [comment]
inspiration from google doing some similar conventions
![2017-01-19_01-24-56](https://cloud.githubusercontent.com/assets/329735/22095872/28aac2cc-dde6-11e6-9efe-080d912efca8.png)

**Comment by aitala** [comment]
The designs are visually very strong and appealing.  I think the version with the dark to light transition works the best at showing the 'hierarchy'.  The initial image, with the inset, dropshadowed menu items was not as clear.

**Comment by btopro** [comment]
@aitala which dark to light? Same color family, contrasting, or fade code?

**Comment by aitala** [comment]
The same color family.

**Comment by btopro** [comment]
BMR: "Everything is omnipresent"

**Comment by aitala** [comment]
Assuming idea #5, if the student had two classes in the system, would they both have the same color pallet or different?  Could the student select a different pallet so they knew in which course they were working?

**Comment by chrisnebgen** [comment]
I like idea 1, but would stray from that yellowish colour. I think the varied palettes of the other ideas are great, but can get messy when you start to decide what to assign to what colour. The design being influenced by Google is great; I have yet to not enjoy the way they present their "product suite".

**Comment by mmilutinovic1313** [comment]
I do really like the styling - I think google influences are good to base designs upon as they have become the new design standard after apple began circling the drain in relevancy. The biggest thing I don't like about this is the buffer size for icons. I think some of them such as the more tab belong on the right side of the screen -- as that is where users would naturally look for things pertaining to their accounts. On the left, I think course items and menus should be present, but we should really think of what can be placed in the top right as well.

**Comment by btopro** [comment]
@chrisnebgen  @aitala the pallet is a pattern based on http://materializecss.com/color.html . So the color changes based on system (content for example). We have also kicked around the idea of a color level pallet that gets applied across headings, icons and interface elements. We've got some minor support for that but it's weak / people can pick whatever they want (needs to be structured to only allow complimentary sets for example, like http://color.adobe.com).

Screenshot so you can see what another system (currently) looks like
![2017-01-19_09-38-56](https://cloud.githubusercontent.com/assets/329735/22110861/49d2066e-de2b-11e6-9a86-c943f5c5553b.png)

**Comment by mmilutinovic1313** [comment]
Number 1 and 2 design also look best for coloring. Although i am in support of anything blue but with the color scheme from 1. This is of course like paint colors in a house as I mentioned yesterday.

**Comment by dolfinitylearning** [comment]
Way nice!

Maybe change preferences icon to a settings gear.

Idea 2 adds a nice thing on the toolbar. Left three buttons identify the current context. You make a visual distinction to separate context from actions on the context. The buttons are visually distinct, not a set of similar looking buttons in a group separated by a |, as in CKEd. I like it. 

New Project button might not need a +. 

Would New Project button be better after existing projects?

Assignment = Project? Maybe one name or the other.

Good stuff.

**Comment by btopro** [comment]
@dolfinitylearning good suggestions. Feedback currently focusing on the top bar I call "LMS-less" as in, a system lacking an LMS experience in which we can make any system a learning system by applying a consistent bar, color, and icon (is the idea). Some ideas from what you said applied

![2017-01-19_10-07-17](https://cloud.githubusercontent.com/assets/329735/22111909/17facda2-de2f-11e6-9a27-11679e9301cb.png)

**Comment by heyMP** [comment]
I like this concept for the toolbar.  It's something that we constantly grapple with, so many options in the system, what do we show the users.  I would like to do a responsive mockup of the new LMSless toolbar.  What are the priority buttons, what aren't.

**Comment by juststormy** [comment]
I like the organizational aspect of it. Reminds me of Trello. How easy is it to implement? Manipulate? I'm guessing it's totally accessible. Can users change the color palettes? 
And while I appreciate this functionality, I can't help but state that right now, I just need faculty to be able to insert pictures without going through a 10-step process. It's the little things.

**Comment by btopro** [comment]
@juststormy it's a mock up to gain feedback so dono, not planning to implement or attempt for a bit. To just do it, not hard, to make perfect, always long process. color palettes are system set w/ planned support for tweaking it.

**Comment by thomasjtobin** [comment]
I'm also a fan of Idea 5. There are two things to consider, though.  For users who turn on high-contrast as their screen colors, Idea 5 would turn the whole top bar into two colors. The contrast between the color blocks and the text labels would still work well, though. Second, for users looking at the interface as text-only or using screen readers, the idea of a hierarchy would be completely missed. If the color is the only indicator of the hierarchy, then there needs to be some other way to show it (perhaps in ALT tags or metadata tagging). I'm new to the project, so forgive me if I';m saying something that's already been discussed or solved, y'all.

**Comment by btopro** [comment]
@thomasjtobin lots of invisible headings that say things like "User menu" sorta thing but yeah we'd take that into account (and aria coverage). Good note on the color contrast aspect.

Ultra high contrast to demonstrate visual hierarchy might still be there (rough cut again):
User -> Course / what I'm working on -> other stuff you can do
![2017-01-19_11-40-27](https://cloud.githubusercontent.com/assets/329735/22115724/242a550e-de3c-11e6-865a-14dc2fc4e028.png)

**Comment by kat-wehr** [comment]
I was going to point out the same thing as @thomasjtobin with the fading colors - the shades aren't different enough for those who don't do colors. I like Idea 4 - using one color for the user/course/role, one other color in the same family for the rest of the tabs, and then one color for the "active" tab all in the same color family but in three distinct shades (maybe darkest, medium, and lightest for best contrast).  

Also re idea 5, I think the active tab should stay in its place in the bar. It doesn't do anyone any good if things are shifting all the time. Consistency! 

The only other thing I'd challenge is @mmilutinovic1313's idea that account related things "belong" on the right - if I'm using the left to navigate everywhere in the course, I'd expect to navigate to my account on the left as well. Unless there's some textbook theory research that says "account info goes on the right" which in that case, who am I without that piece of paper that says I'm an expert? :)

**Comment by cmd30** [comment]
I like the google feel of the layout. I love when I'm on google and I know I am in a specific place based on color, sheets, docs etc. 

I don't get the feeling that the brown conveys a modern feel though. The yellows and goldenrods are more common now. 

I'd be concerned with how similar the new project brown is to the yellow button in value. It doesn't really stand out to me due to the value similarity and thin font weight. Same for the tightly kerned brown text on medium gray cards. The black trash can and plus sign have much more contrast and spacing and stand out more than the brown.

Is stacking the cards possible on mobile? That is my least favorite part of my Trello mobile app. I don't like have to compromise text size on mobile and would rather Trello have stacked cards with an expand feature (I know you mentioned you haven't covered expanding menus here yet). 

Is the accessibility icon for preferences just a placeholder? I associate that with accessibility features and not so much updating my account or preferences. 

Sorry if I repeated or overlooked any notes. Coming in kind of late and haven't been very active on here.

**Comment by btopro** [comment]
@cmd30 ignore the app stuff as I wasn't really designing that just messing with it. Looking for the "google bar" type of approach. What's good, questions it raises, if it conveys situational awareness of who I am, what am I doing, where can I go from different user mindsets.

All the rest is valid feedback I just wasn't really designing that (yet) so... :)

**Comment by mmilutinovic1313** [comment]
@kat-wehr Not sure if there is research to support this. I could always look. I was just thinking of Google's standards and Facebook's standards as to where profile information goes on non-profile pages.

**Comment by btopro** [comment]
It's placement could also be relative to like "do I care that I'm me after I've logged in and see my picture?" not really, so I could go either way on that personally.

**Comment by btopro** [comment]
![2017-01-19_14-13-12](https://cloud.githubusercontent.com/assets/329735/22121277/6dd84548-de51-11e6-9519-9ca3997e463b.png)
based on feedback / playing, tweaked size and spacing of the bar to be in alignment w/ the mock ups in this thread. The other changes need more opinions / iterations before making a shift of that magnitude. @juststormy asked about how long it would take... a 3-4 days I'd say to iterate towards it. The mock ups without additional feedback / stewing isn't a priority currently still cleaning up / expanding studio app.

**Comment by rickhumphries** [comment]
Had a discussion with a few people about this today. We think what you're trying to do here is the right thing. Thought that the following mock up made most sense in terms of how the menu items are arranged:

![lmsless-mock-up](https://cloud.githubusercontent.com/assets/4973810/22129115/12231f66-de9c-11e6-88ca-3f56e493f9e2.jpg)

* I agree with @mmilutinovic1313  that the user icon should move to the right as most (though not all) common interfaces seem to have it in this position. In this case I think it makes sense to move it here though from a functional point of view as it sits distinct from the other menu items on the left which are more about situational awareness for the course and navigating. The user profile links are more about user settings etc.
* The settings menu on the right would provide the current menu options that appear when clicking on the course name.
* The menu items on the left then work well as shown I think. The course that you're on furthest left, then showing the different component tools coming off this. Kind of breadcrumb-esque.
* I wouldn't, therefore, include the 'Help' or 'Syllabus' menu items within the links to the other services, as they aren't really 'services'. I would make the 'Sing 100' link a side-nav flyout. This could include these specific course links (for 'help' and 'syllabus') alongside other options to go back to 'Home' or to 'Dashboard' or wherever to switch between courses.
* I'm assuming the 'Section Name' link would not appear for students. I don't think it should as this doesn't really mean anything to them (well, it doesn't in our context anyway :) ). But I think it's good that it's there for staff etc. One thing to be aware of though is really long section names. Because our section name is the 'access string' some of ours can be about 30 characters in length because of how it's been set up in external systems. You might want to support a 'section label' field instead to be displayed here.
* I don't think the 'active service tool' should appear furthest to the left of the other services. My opinion is that they should stay in the same order, just for consistency.

Nice to see there's plenty of debate though :)

**Comment by michael-collins** [comment]
**Student View**

![elmsln-redesign-jan-2017-student](https://cloud.githubusercontent.com/assets/1085304/22237606/efea54a4-e1da-11e6-8be0-3803d64fa988.png)

**Administrator View**

![elmsln-redesign-jan-2017](https://cloud.githubusercontent.com/assets/1085304/22237605/efe9cfac-e1da-11e6-8aa1-5ca727074e14.png)

**Comment by michael-collins** [comment]
![elmsln-redesign-jan-2017-studio](https://cloud.githubusercontent.com/assets/1085304/22239370/43a95064-e1e4-11e6-98ff-66651eb1547d.png)

**Comment by michael-collins** [comment]
![elmsln-redesign-jan-2017-alt2](https://cloud.githubusercontent.com/assets/1085304/22239649/8effbcc8-e1e5-11e6-8ef6-3bb91eb91b70.png)

**Comment by btopro** [comment]
Painted on w/ descriptions of thoughts below. Seeking mental model uniformity since I know you were going for better visual hierarchy. I do REALLY like the "studio" example that's last where there's the "you are viewing this item in the bar" and then it's visually connected to the options below it. This will go a long way towards system unification to the point that **we can start hollowing out entire systems and replacing them with angular apps for their UX patterns**.
![2017-01-24_09-29-09](https://cloud.githubusercontent.com/assets/329735/22251310/49a2c3b8-e218-11e6-9d43-06f541ea5e51.png)

RED
1. I like the visual hierarchy of these items which are most important / critical being 1st. The course is formed around help and the social contract w/ the faculty for students. Obviously these would still be configurable to be removed (as they are now) but are based on UX recommendations w/ a large sample size of students at WC (500+). These don't really look like buttons / clickable is my only thing with them.
2. I miss the icons already / while clean there's something missing visually to offset the other options as part of this group, don't know what that is. As the `[+]` button here while the right color I don't think works in the same way (yes I realize this is a rough placement w/ some things)
3. Very interesting idea w/ having the other applications over here, the ... could also be used to hide things as there isn't enough realestate. The question w/ these will be if students see them or not. I'd say for the next year no but as the UI is cleaned up more in this direction it would be nice to have a setting to display this to students. Architectually the data model is in tact in media to allow this for a day when we'd want to say "go check out the course media gallery as I added feedback for last week's in class work" sorta deal. Allowing for the media stuff to act more as a gallery. ICOR probably wouldn't make sense in this regard though it also has that level of unified data model
4. Is this the in page nav or between pages nav? Would there be no in-page nav? I got all kind of grief when taking the between pages nav off the interface, universally (except from you know, students, but I mean who takes them into account they only click linearly through linear content so I mean, what opinion would they have that's relevant here *fake chuckles*).

GREEN
1. Edit I think needs to be more prominent. I do like that it's still down "in the page" context visually but we get so many people completely overlooking it. Word edit w/ it would go a long way probably.
2. Share, this is admin/staff/instructor visible only, not sure if there's a more dedicated area / color region for things like this (i know we've gone back and forth about that idea in the past)
3. Preferences person would probably be under the user's windy wheel menu based on this mock up. These settings were once specific to the system but now are global in scope so might make more sense in a global hierarchy location.
4. Something visually offsetting about the `[+]` to make it obvious that this is an admin only task.

Also the section name being visible probably just takes up a lot of space. There's also very little banner and very large white space smack in the middle. I wonder if there's some way we could make the course name bigger w/ smaller description so that it hits you in the face as to what your looking at.

Other considerations: If we continue system level color / iconography (yes) OR if we allow course level manipulation of colorsets. Personally, I see the appear of having a "course color", however, this could get very "at a glance" confusing contextually if we allow too many things to be flexible in this regard.

A nice middleground could be allowing a course color and just mixing the course color into things but that the system color is still the primary thing seen (again, at a glance). Think driving a car and glancing down at the dashboard to see how fast your going or what your current heat / radio / nav settings are. Color / placement (which I think you've got good progress towards) and iconography are critical in this flash of "where am I, ok resume" that our brains do 100s of times a day without realizing (ala 99% invisible :p).

**Comment by michael-collins** [comment]
@btopro Thanks for the detailed feedback. I think most of your points are good ones. The visible banner area should be larger in the mockups, I just overlooked it (though I want to get rid of it entirely on my course section, I'm assuming there is an option for that ;). However... the use of white space directly above the nav links helps make the page as a whole more glance-able. If you take it away (which I did in may iterations leading up to these mockups), you lose the ability to quickly glance and see where things. One more case for white space – without it, everything feels compressed and I really want to mimic the airiness of an academic building with high ceilings (more room to think). So, that's my rationale, it's definitely on purpose. There is a tremendous amount of white space, even on github as I write this.

1. Unfortunately you are probably right about the edit button. I think a button in the style of the "add category" button from the studio mockup would look nice.

2. Let's try it with service icons, I kind of miss them too, but the space savings was enormous. 

3. I was thinking that we cluster the admin only visible links in the read area. If it's available to students, it would move over the blue area. We could also instead of red, use green, and then use some other color that isn't blue.

4. This is the outline navigation that takes you through books. Keep the linear nav, I just imagined it was below the visible area in the mockup, wasn't suggesting to remove it. 

My main focus on these mockups was reorienting importance back on content. Even in these mockups, the navigation is still slightly aggressive with drawing attention away (solid areas of color are hard to compete with). We can nix the section name, I thought that was an interface requirement for some reason.

**Accessibility**  
I realize accessibility is now global to the system, but I wouldn't hide it away. I think it's worthwhile to keep that button there so people can find it. If you put it up in settings, it will probably most likely never get used, and you've done way too much interesting work on accessibility/UI interaction to let that happen. I imagined ADMIN course settings being up there under the gear icon, whatever those are. If there aren't any that don't live in CIS, then we can get rid of it altogether. I think permanent accessibility settings could be stored under the user profile icon/name giving you the ability to edit it globally there.

**Comment by michael-collins** [comment]
@heyMP and I worked through some ideas. Made a lot of changes per your feedback as well. I think the section name would only be there for a user level permission higher than a student. Also, that thick line under the nav is the scroll bar. Reserving the color blue for page links and certain nav links.

![elmsln-redesign-jan-2017-alt12](https://cloud.githubusercontent.com/assets/1085304/22268376/56c31574-e255-11e6-93e1-2b96f6a89946.png)

Of course... I don't like banner images, I'd rather just use this for my courses:

![elmsln-redesign-jan-2017-alt13](https://cloud.githubusercontent.com/assets/1085304/22268377/56c307be-e255-11e6-8885-9d2030235802.png)

**Comment by rickhumphries** [comment]
Really like the mock up @michael-collins. Think it works really well. 

One thing I've been slightly concerned about before is the amount of space taken up by the banner and the menus at the top. We do really like using banners to give a course its own identity though. I only really find it distracting though when I'm moving between pages in the outline so maybe it doesn't apply to all tools. But it's especially prominent on mobile.

Not sure what the solution would be. Perhaps having a 'read mode' similar to the type of thing you can get in a browser but optimised for elmsln? Or having the page scroll automatically to the top of the content when moving between pages?

**Comment by michael-collins** [comment]
Thanks @rickhumphries. I think maybe a banner would be appropriate on the syllabus, resources, and help pages, perhaps where brand identity reinforcement wouldn't be too awful. To warn you, I'm pretty anti-banner.

Unfortunately, I think my opinions on this are in the minority (everyone else is clearly wrong! ;). But, when I use other web applications/sites, the only time a banner exists is when it's from a user uploaded image for personalization (twitter, fb, ello.co) or on some marketing website. @btopro often points to google and microsoft as inspirations, but neither use banners within their tools, they save it for the marketing site. The online course environment in my mind should be more like a serious tool that doesn't have much more than room for an icon for brand reinforcement. Banner images just don't seem like a serious use screen real-estate in a work tool. So, that's why I have a strong dislike for them. :)

**Comment by rickhumphries** [comment]
Yeh I see what you're saying. I do think the mock ups/applications in general can look a lot cleaner without a banner. In the case of Microsoft and Google I suppose those tools are always a singular instance of that tool - so always authorities. Colour and logo together are usually strong enough indications of what tool you're using in this case. However, a student could be enrolled on multiple courses, so they may have 3/4/5 course outline instances on the go, in which case I think a banner can play an important role in giving that visual indication of what course you're on. A comparable might be a Facebook group or Google Community page.

Don't get me wrong, I'm not a banner super fan, there may be something else visual that can provide this, but I do think it needs something. Google communities do use banners, but use display it at the side of the screen rather than across the top:

![image](https://cloud.githubusercontent.com/assets/4973810/22271476/a141c820-e28c-11e6-914a-47dfc31ca3ae.png)

Not sure that would work in this case, but it's an alternate example at least

**Comment by btopro** [comment]
*shade*
Don't worry @rickhumphries , @michael-collins also hates when reading a physical print magazine that the article has a high res photo or that it has a cover at all. He prefers books which never have images to emphasize to the reader what they will engage with
![moby-books-moby-dick](https://cloud.githubusercontent.com/assets/329735/22273113/876a3646-e26c-11e6-8286-9e7c4d77a86a.jpg)

**Comment by btopro** [comment]
@michael-collins @rickhumphries now, the shade is not without constructive criticism. I think there's a place between the two methodologies. For example, when I come to a book on my shelf, I pick it up and know what it is. The cover is very important for initially establishing wtf this thing is. After I know what the cover is, a thumb through the pages to the chapter I left off on (poor analogy as I barely can read but still). There at times is an image or small icon associated w/ the start of chapters to serve two purposes:
1. help me remember I was there
2. help set the tone of the chapter

In both of these image uses though (and this is the payoff) I DONT GET CONSTANTLY BEAT IN THE FACE WITH THE BANNER OR IMAGE OR ICON EVERY FRIGGING PAGE TURN.

Simply when viewing the book on a shelf (overview) so I know what to pick, and then potentially when referencing the book.  I think a high fidelity full page image to start off a unit / lesson / course experience in general can serve the purpose of the "oh this is cool I remember this course" and then collapsing it back into a small thumbnail (think twitter profile photo vs header image). If I click on the course to look at settings associated w/ it or a menu is presented that is all around "you are working within this ecosystem" or "remind me of this ecosystem".

A smaller version of the high fidelity image can be presented in things like flyout menus related to the course, overviews in other systems (like CIS / media / etc) when dealing w/ the course. @heyMP and I have talked about the idea of having a angular app that treats content more like it's a magazine. Would this satisfy the need to consolidate space but also to appropriately brand and provide context of what someone is about to engage with (when dealing w/ a program of courses foe example and taking, oh I dono, 4 of them at once)

**Comment by btopro** [comment]
@rickhumphries RE the scroll down on next page. The latest build of the authoring experience does this. If you hit edit it will scroll down about 200px so that the banner and top bar stuff isn't visible since that's not what you'll be editing.

**Comment by btopro** [comment]
@michael-collins What if your mock up w/o the banner had the banner consolidated into a square abstract / mini version of that image to the left of that text

**Comment by michael-collins** [comment]
@rickhumphries Agreed. I will add though, Google doesn't use them everywhere in the communities tool. I imagine the following example to be like what I want a student's view to be in the open studio in ELMS.

<img width="1323" alt="screen shot 2017-01-24 at 7 58 59 pm" src="https://cloud.githubusercontent.com/assets/1085304/22273608/ac504dc6-e26f-11e6-9e05-17123038c620.png">

I think it's a good idea to put a banner/graphic representation on maybe the syllabus page in the way that google is using an image there on their communities page. Is course differentiation really the problem for students, and one that needs to be solved with a banner? I'm not intending to come off as contrarian, but I am curious if you've heard of students being confused about which course they are on. My personal experience as a student using online learning of platforms ah la 14 years (ugh, I'm getting old), is that content was the only thing differentiating courses and I don't remember that being terribly upset about it. Though, I did generally hate ANGEL, so maybe that isn't a good example. Regardless, the content itself was the main differentiator. So, I just want to make sure that we are designing things for the right reasons. My theory is that students aren't impacted by banners, and I will try to test this theory scientifically over the next couple of semesters.

**Comment by michael-collins** [comment]
@btopro The high res images you described for each lesson is what I am considering to be content. When I say banner, I really mean a permanent fixture of the UI itself, that is an images that takes up space at the top of the screen, regardless of context. They make a ton of sense in marketing websites, because they make it feel like a print article or advertisement.

So... I really like the functionality you've described and the uses of images that you've described. I think it's a really good idea to make images play a more important role in the content, and perhaps even in the navigation.

**Comment by michael-collins** [comment]
Really like that image idea Bryan. Sold. That's the image for my courses when they run.

![elmsln-redesign-jan-2017-alt14](https://cloud.githubusercontent.com/assets/1085304/22274218/1b651f40-e273-11e6-8dcc-145fa35ccb8d.png)

**Comment by btopro** [comment]
@michael-collins still a lot crowding the top but yes that kind of an idea. Green I realize is just for visualizing admin vs non tho that color drives me crazy :p.

We'll need a hueristic associated with what and when things take on the course color (something taht can be defined) vs the system color (something that's inflexible) vs (in case of content) content level colors.

**Comment by btopro** [comment]
Another thing that I think will help us along in our thinking is if @heyMP and I get the HAX / drag and drop upload to make remote media widget working. Once the lines start to blur between where one goes to do stuff, it'll help inform the design even more as far as operations that would be good to have quick access to.

**Comment by btopro** [comment]
Another round of suggestions
1. shift the section name up on same line as the course machine name (DMD 100 | Master)
2. Cut the word Outline from Content Outline, we enforce a 1 word system name. Then shift content to be the 1st positioned item in lists since it's driving the engagement with the rest of the items (inbox is still a future dream atm too)
3. use materialize style plus sign / plus circle
4. Add print icon (which would expand w/ list of methods of print, paper, pdf, epub in future or whatever) as well as shrink the items in this line and make them to the right in the gutter, aligned with the title of the page. On scroll the header could also scoop these up into it so as you pass the title it shrinks the title and these elements down into it in a logical way (title = last item in the breadcrumb so it basically happens anyway).
Also: 
- reduce spacing on all 3 levels of hierarchy as items I nudged around require less vertical space
- consolidate settings gear w/ profile picture / name; space saved here can shift critical elements (syllabus / help / resource)  over
- DMD100 label in breadcrumb could probably be replaced w/ an icon or something to imply outline / table of contents / top level / what have you

Additional thought on banner. https://tympanus.net/Development/OffCanvasMenuEffects/index.html with top-side idea if clicking on course name / smaller image could peal back interface to reveal full banner.

![2017-01-24_21-00-28](https://cloud.githubusercontent.com/assets/329735/22275724/b8a6fd1a-e27c-11e6-95b1-63f0fff1a2a1.png)

**Comment by btopro** [comment]
![2017-02-04_11-25-05](https://cloud.githubusercontent.com/assets/329735/22619904/a3799e72-eacc-11e6-965a-7001f2ec5f4f.png)

**Comment by btopro** [comment]
Prototype video showing what this would look like if we applied some more ideas from this thread. This has been put off on a new branch for additional remediation since this is a longer term feedback goal then currently exists https://www.youtube.com/watch?v=CLalqQ7PA_4

**Comment by btopro** [comment]
![2017-05-01_11-01-03](https://cloud.githubusercontent.com/assets/329735/25582902/853d14d2-2e5d-11e7-8379-1610c52e6e55.png)

ignore the blockquote text since that's a hax prototype thing

**Comment by btopro** [comment]
![2017-05-01_11-02-46](https://cloud.githubusercontent.com/assets/329735/25582950/b7fb17de-2e5d-11e7-868d-e44056d15d92.png)

**Comment by btopro** [comment]
![2017-05-01_11-03-45](https://cloud.githubusercontent.com/assets/329735/25582978/dc0dbdca-2e5d-11e7-84df-3d117ed191d0.png)

**Comment by btopro** [comment]
merging the code from this thread into 0.8.x since it'll have a lot of improvements (including this visual hierarchy / ordering of elements from @michael-collins pipeline prototype). This is not a webcomponent as that proved more complicated then necessary (for now).

**Comment by btopro** [comment]
![2017-05-11_20-18-51](https://cloud.githubusercontent.com/assets/329735/25977136/4732022e-3687-11e7-8621-8b8099e71b33.png)
 a little closer...
