### ISSUE TITLE
Hide course outline link (table of contents) for anonymous user?

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1791]
When a course requires login and the user is not logged in, can we hide the course outline link at the top? Currently the outline link is always there no matter user is logged in or not, and if not logged in it just shows a table of contents popup with the line "create a new course outline to get started". That message does not make much sense for unauthenticated users. Is there a way to hide that link? Any idea?

**Comment by btopro** [comment]
That sounds like a valid feature request / bug to fix. It's happening because if they are anonymous, and they don't have permission to view content, then when it goes to select a default outline for them to view it gets mad and instead of failing (old way it worked) it says "create content", which obviously makes no sense.

The module powering this is mooc_helper_book_nav which is a block rendered as a breadcrumb so mooc_helper_book_nav_block_view is doing the render. If it had the permissions logic check to ensure that they actually can see something in the first place, you could potentially resolve this issue at the source by not presenting the icon if they don't have the ability to view published content (there may be edge cases beyond this where it would fall flat but I believe this would resolve what your saying and make the most sense for now)
I believe this is how to check rights of the current user for accessing content
`user_access('access content')`

Want to take a stab at fixing it?

**Comment by lizatgit** [comment]
@btopro Thanks for the explanation! I added a line to mooc_helper_book_nav.module on my local copy and it works well. Below is the line I changed:

elmsln/core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/mooc_helper_book_nav.module:

---------line 85 --------
function mooc_helper_book_nav_block_view($delta = '') {
  if(!user_access('access content')) return null; // do not show outline for anonymous users
-------------------------

Is that OK?

**Comment by btopro** [comment]
i'd return $block instead of null since it's expecting an empty array downstream in drupal.

Also could you do the following to get this in for review for everyone:
- fork the repo at the top
- clone this version locally on your computer
- make the change in your copy locally
- edit the line and commit the change back to your repo
- come to this repo and hit pull request, then issue a pull request to pull your changes into the main platform

This will give you credit in our repo, give us the ability to test / review it like we do all other changes from contributors, and get you practice with that development workflow for when you fix future things :)

**Comment by lizatgit** [comment]
Thanks! I'll do that.

**Comment by btopro** [comment]
PR fixed this!
