### ISSUE TITLE
Active/Sync this Now Button

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#186]
I need a button to make my sections active prior to the "legal" start of said University semester in one click.

**Comment by btopro** [comment]
We'll need a better justification then that given the nature of the word "Legal" which means, outside of the bounds of access it is not legal. The legal definition of a semester is both a student loans concept as well as a justification for TeachAct and providing access to materials that otherwise would not be permissible, exception being within the confines of the legal semester. This is also why access is revoked / modified when the semester end date is met.

Are you looking for adding everyone but not granting roles to view content until the legal start? or are you looking for a way of feeling better about the fact that you added in a section and want to know it's going to work when people start to access.

**Comment by juststormy** [comment]
I am looking to make sure that faculty can get in and edit it now, before the start of classes. Without being to pull the ANGEL roster in I couldn't masquerade as the faculty member. Should I just be adding them as standalone users? I guess that is what I am trying to do. Just don't know how to capture it. Thanks.

**Comment by btopro** [comment]
Makes sense, so we should sync as soon as ita created and only add non student accounts in this routine. All others just get an account but no level of access until it actually starts. If we can get the right university APIs this stuff will just happen

**Comment by juststormy** [comment]
Thanks. Sometimes I just can't find the words to explain it. This makes sense.

**Comment by btopro** [comment]
Sync on addition of a section BUT
- [ ] if it's before start date, only pull in non student roles (Instructor / TAs)
- [ ] create all accounts / section association, just no role elevation
- [ ] Doesn't start actively syncing under after course has started

**Comment by btopro** [comment]
@michael-collins I think your CIS dashboard for a course has support for a button like this but throwing this out there so you can let me know if that's the case.

**Comment by michael-collins** [comment]
There is a sync button, yes.

**Comment by michael-collins** [comment]
There is a sync button, yes.

**Comment by michael-collins** [comment]
I'll delete one of those responses...

**Comment by btopro** [comment]
- [ ] create a link / path that uses the pin-prick api to kick off the sync for a course (across systems)
If we have this (even in our crappy UX pattern now) then we'll be able to use the same thing when we fix the UX

**Comment by btopro** [comment]
Sync button available on the new homepage course grid which has more options then what was previously exported
