### ISSUE TITLE
Issue with Copyright/Trademark Symbols

### ISSUE THREAD

**Issue by Anthall** [elmsln/elmsln#1872]
Hi Guys, 

I've come across an issue when trying to use HTML symbols like &#169;, 	&#174; and 	&#8482;.

They appear fine initially after saving, but when I go back into a page and edit the source code further they are replaced by  (c), (r) and (tm). 

Has anyone else come across this problem and know how to get the symbols working properly?

**Comment by btopro** [comment]
that is so weird, lol. So that's related to the textbook input filter having "Convert all characters to US-ASCII". This has been discussed (dropping this) because of some conflicts with Math #1852 . It might be time that we just drop that conversion requirement entirely. it's a bit too aggressive and is in place to protect against rendering weird Word / other characters bleeding over via copy and paste.

**Comment by btopro** [comment]
this is provided via textbook module implementing transliteration. transliteration is important for stripping weird characters out of filenames / from landing on the file system but we probably can disable it in the text areas.
