### ISSUE TITLE
Building a course made purely of shortcodes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1900]
OK so I do a thing where I've essentially built an entire course out of shortcodes. To do this I use the static content type in Media to build a page, then fill that full of content, and other media (using shortcodes). The end result is that in the course, the page is just one shortcode.

The reason I do this is because I have one course which feeds into many others and I guess I'm trying to get some form of function that was discussed in #763

This has actually worked really well as it's a short course (I think managing the pages in Media would be too difficult though in larger courses and where LOR would come in). However, starting to see the following issue. 

As an admin user I can see the 'settings cog' and clicking the 'overall' cog works well:
![image](https://cloud.githubusercontent.com/assets/4973810/23273282/62851a84-f9f6-11e6-9a50-73e3f57b5345.png)

However, clicking on any 'embedded' cog takes me back to the CIS, regardless of whether I've clicked 'edit', 'display modes', or 'related data'. E.g.
![image](https://cloud.githubusercontent.com/assets/4973810/23273377/b27310dc-f9f6-11e6-9de2-78c06cd77f55.png)

Also, if I log in as a student, I can see the cog link options, but displayed as direct links underneath the embedded embedded Media:
![image](https://cloud.githubusercontent.com/assets/4973810/23273443/ebedd43c-f9f6-11e6-86c2-d620a4781c74.png)

Related #1602

**Comment by rickhumphries** [comment]
Just to show that it doesn't show those cog options to the student if I used the system like a normal person and just embedded the media type onto the page:
![image](https://cloud.githubusercontent.com/assets/4973810/23273539/59717ef0-f9f7-11e6-93b2-c6df4ccd859b.png)

**Comment by btopro** [comment]
it's a race condition to what role is triggering the render since local will cache the response data, but generate the remote data as a super user which can do those things. This is quite inception-esk given that you have media rendering tokens, interpreting them, and then bundling that up as a token and rendering it some place else as the token which unpacks and has the interpret'ed things.

hmm... a few ways to go about this... one could be using the render-as property via webservices to actually hit the page as someone else. I don't like that idea...

Another could be forcing results to be raw. Technically they'll be processed twice as is. So your trying to basically have token 1 unpack, THEN get processed. This becomes a matter of who's doing the processing (right now, media is processing then sending and injecting into MOOC, this would be making it so MOOC makes the call, media doesn't process it just returns, then MOOC injects and processes)...thinking

**Comment by btopro** [comment]
@rickhumphries what's the token you are using to embed the static page? There's a "individual fields" option in the share menu flyout. See if just doing the body field will work. This returns just the field instead of rendering it (remotely) and then renders it locally.

See if that clears up the role issue, I think it will. Clicking the nestedly rendered token still directs me to CIS (meaning it failed to match something and bailed) but that could be another issue we account for if the token is in rick-inception-mode ;)

**Comment by rickhumphries** [comment]
Getting kinda trippy. Looks like I'm already using the individual field shortcode for this though, for example - `[ciscode|rev=1|tool=elmsmedia|item=1846|entity_type=node|render=value|field=body|delta=0]` but I can maybe look at different combinations of shortcodes within the other options

**Comment by rickhumphries** [comment]
I've fixed with a slightly crude CSS bandage for now:
```
div.contextual-links-wrapper:not(.contextual-links-processed) {
display:none;
}
```

**Comment by btopro** [comment]
hm... so this would help hide things in things yes? If so this isn't a bad bandaid to apply in general since I'm not sure we really WANT to support inception use-cases directly.

**Comment by rickhumphries** [comment]
yeh the settings cog that an admin sees has both classes applied to the div wrapper, but the list of links that the student would see is only wrapped in a div with the `.contextual-links-wrapper` class. So this specifically targets the student's view of things.

**Comment by btopro** [comment]
Applying the CSS that fixes this. @heyMP was able to make this happen the other day and then wasn't able to replicate it. I like @rickhumphries 's simple solution for insane edge cases where this is possible :P
