### ISSUE TITLE
gitbook importing: Generating an ELMSLN outline 

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1934]
I was thinking today as I was working on the course calendar, could we import the gitbook based on a file that is not the SUMMARY.md file. This would give us the ability to design the outline how we want, rather than change the gitbook to accommodate a course offering schedule. We could make a file called ELMSLN_OUTLINE.md in the repo and read from it instead of summary. The potential here is that we could also trip configuration settings (visible/not visible, when things are due, etc.)

Is this worthwhile?

**Comment by btopro** [comment]
err... so like some kind of additional custom configuration stuff based on a different file that provides that and overrides summary or builds upon summary? Not opposed but this smells more like yaml / non-reusable effort unless we had a full blown "elmsln.yml" which just orchestrates the whole thing. Again, once reaching that point though I'm not sure what this does other then tries to switch time spent on the part of the faculty for time spent on the part of institutional members in making this format be supported instead of clicking buttons (yes I know, I enjoy automation too).

**Comment by btopro** [comment]
Possible settings:
- How to handle images
- How to handle external links
- How to handle youtube videos
- How to handle files / documents

Example for handling a elmsln.yml:
```
- elmsln
  - styles
    - image : lightboxed
    - youtube : modal_popup
    - files : file_viewer
```

Something like this which then on import we could store these settings / read them off to know how to render media. So we could automatically present all images as a lightbox version as an example.

**Comment by btopro** [comment]
most likely this information now would be in web components. we started this discussion last year prior to having them when we thought of markdown augmentation; now we're replacing markdown w/ components that express more verbosely what they do and what they represent. Something like this could be useful down the road but let's get on webcomponent based publishing workflows with #2303 before that
