### ISSUE TITLE
Font tweaking for paragraphs

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2019]
Roboto is a good interface and headline font, but it's hard to read in large paragraphs. It looks like it's overriding the Droid Serif font that was originally there for the p tags. Any reason it's not being used? I think if we bring it back and lower the text size to 1.1rem instead of 1.3, readability will improve considerably. Also helps to distinguish reading content from navigation items a bit more.

Before:
<img width="1195" alt="screen shot 2017-05-18 at 2 12 48 am" src="https://cloud.githubusercontent.com/assets/1085304/26188863/98879912-3b6f-11e7-91e3-db880d1de855.png">

After:
<img width="1195" alt="screen shot 2017-05-18 at 2 12 36 am" src="https://cloud.githubusercontent.com/assets/1085304/26188859/9453e044-3b6f-11e7-851b-82fae85cd079.png">

**Comment by btopro** [comment]
it'll be a cold day in hell before we use a 17px font size.

Which is which here? pre and post or how it is and how it was?

**Comment by michael-collins** [comment]
I've updated the first comment to show before and after. I don't know what the weather is in hell, but it's starting to get chilly down there, I'm sure. ;) The reason I didn't go down to 16 (the minimum recommended size for readability on the Internet), is because the rest of the interface is quite magnified. Any smaller than 1.1 and the scale difference started to look noticeably strange. Too large of text size (1.3rem in this example) can be just as hard to read as too small.

**Comment by nmillin** [comment]
It looks like https://github.com/elmsln/elmsln/commit/ec56057c1fb675c14d3fd5df12132a073ccd9825#diff-b035893ae969455741fbc2061a3a57e6 was when Roboto started to override Droid (found commit to try add context of why it was added). 
I'm assuming michael has an idea for reworking the CSS since he added screenshots. +1 to reviewing the Roboto CSS in tweaks.css shown below.
`body, p a, p p a, h1,h2,h3,h4,h5,h6,p,p strong,strong,p b, b, #etb-course-nav span.course-title, .alert-box, #etb-tool-nav .tab-bar span, ul.off-canvas-list li a, .etb-book ul, .etb-book ol, .etb-book dl, .etb-nav-modal ul li a, a.etb-nav_item_service_btn span, a.etb-modal-icon span, a.modal-img-link span, .etb-nav-modal h2, #admin-menu .dropdown li li a, .admin-status-bar span.course-section-label, .admin-status-bar span.user-role-label, .admin-status-bar span.current-user-id-label, h2, a, p.txtbk-intro, p.txtbk-intro a, .section-id, .accordion .accordion-navigation > a, .accordion dd > a, .sub-tier-1 h2, .sub-tier-1 h3, footer p, .admin-status-bar span.course-section, .admin-status-bar span.user-role, .admin-status-bar span.current-user-id, h1, .image-media h3, h4.testimonial-name, #etb-course-nav span.course-abrv, .etb-nav-modal h1 {
  font-family: "Roboto", sans-serif;
}`

**Comment by btopro** [comment]
we are killing the CSS off so if you fix it it won't be questioned. Components will eventually take the place of all this global BS

**Comment by nmillin** [comment]
Hmm... in looking deeper into the CSS, I'm not sure what should stay/go. 
It might be best leave this as is until the legacy folder in elmsln_contrib can go away. (I'm assuming removing legacy & legacy_zurb is the long term plan with components replacing everything.) Otherwise fixing this could cause other issues.

**Comment by btopro** [comment]
fix should be in tweaks to override it. eventually we'll shove everything over to that file from all the inheritance BS going on. And then we'll kill off that folder, then we'll abstract out of tweaks into components, then kill off / drastically reduce the tweaks file. This is a process over the next year or so.

**Comment by nmillin** [comment]
So there appears to be 2 parts to this issue. The font-family & the font-size.

https://github.com/nmillin/elmsln/commit/7d3336fcba32d47f9368a3c132103f8a94cfb79d is an idea for splitting up the font-family into 3 use-cases per comments above and scss structure.
1. droid font -- default of content authoring
2. open sans -- special content authoring overrides
3. roboto -- admin toolbar and navigation

I searched through the code to see what styling is used where. I didn't remove any classes/elements in case I missed something and I defaulted to roboto if I wasn't sure.

For the font-size, 1.2rem would be 19.2px. Any smaller than 1.2rem and then it would be a chain reaction of changing all of the other font sizes (.text-largest 1.7, .text-larger 1.5, .text-smaller 1.0, .text-smallest .8)
https://github.com/nmillin/elmsln/commit/38fc7e4098b0cbf534ac9a45944f7ec88b053a80

Thoughts?

**Comment by btopro** [comment]
scss stack is completely broken and needs thrown out (components tearing this down a bit to begin with) as an FYI.

1.2rem sounds good. @michael-collins can you provide font recommendations so we can gut down to 1 preferably or whatever you want it to actually be. We shouldn't have 3 in here for no real reason other then the nature of the building over time :p

**Comment by btopro** [comment]
bumped to 1.2

**Comment by btopro** [comment]
tip of 0.9.x has font usage (and style sheets) untangled drastically. Now we should be able to say "these get this" kind of font selection whenever @michael-collins has some thoughts on which font(s) we should use in what situations. I also depreference san-serif personally as it's impossible for me to read (its what makes me think I have mild dyslexia as the sharp edges of the letters kind of bounce for me for whatever reason). That said it's why I'm not making a decision on this.
