### ISSUE TITLE
Broken markdown link.

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2042]
Update: Found multiple pages with link issues.
- https://courses.aanda.psu.edu/dmd100/projects/narrative/deliver_hypertext_story.md
- https://courses.aanda.psu.edu/dmd100/projects/narrative/deliver_iterate.md

I didn't fix the link manually because I'm assuming we need to fix this globally? Here is the page the link is located: https://courses.aanda.psu.edu/dmd100/projects/narrative/develop_story_and_plot.md

There is a link on this page called "character topic", which doesn't resolve. This where it points: https://courses.aanda.psu.edu/topics/character.md

**It should be:** https://courses.aanda.psu.edu/dmd100/topics/character.md

**Comment by btopro** [comment]
dont think we support rewriting non-asset links currently. This isn't terribly difficult but it is probably something you should fix manually for the moment as I'd like to talk through it with @cgldevel and @heyMP since it has implications for people who would create git based content in the future.

**Comment by btopro** [comment]
@michael-collins fixed and reflected in ur content in prod
