### ISSUE TITLE
deprecated: Clean up permissions after running git-book drush commands

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2088]
Bug:
- after running git-book-create or git-book-sync the file permissions are changed from apache to the current user.

Need a way of running permissions clean up after drush commands, or running drush command as apache user.

**Comment by heyMP** [comment]
I think this is still an issue.

**Comment by btopro** [comment]
might need to just put this in the docs. If you run a drush command manually then you'd have to run the leafy option 6 so it hardens security to set these to what they need to be. There's no way to do this automatically without sudo rights since it happens file system wise. I looked at sticky bit and that solves the group but not the rest. my guess is that this has to do with ownership rights in the `.git` directory. Is this an issue if issued from commandline?
