### ISSUE TITLE
Legacy support for zurb/materializecss

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2100]
I just wanted to get an idea for the current roadmap for the phasing out of these to be replaced by WebComponents. Whilst I totally agree with the move towards this, we've spent quite a few months, maybe over a year, building applications and course style guides based off these frameworks. It would be good if these were still somewhat supported over the next few releases so that we have time to play around with the Drupal WebComponent stuff and build a WebComponent library of our own to replace what we've done already. I'm a little worried about the current 'gutting' of these frameworks from core and what this might mean.

**Comment by btopro** [comment]
so a lot of the files removed were in building the front end stack, and a lot of the front end stack wasn't used. It was CSS written like 3 years ago that we were band aiding on band aiding. Components help make sure the wrapper GUI isn't influencing the content presentation. We'll still have the HTML wild-west for quite awhile in the body field. Foundation legacy support is still there / untouched from how u are currently using it. MaterializeCSS color set is still all there and the classes for grid still there. Basically, we've bought in on the same stuff so we're not killing all of it, just trimming it all back so that we stop overriding an override that was already overidden but oh crap where did that ocme from, oh now it's blue, red this time, underlined with 2px margin left but why?!??!?!

:)

**Comment by rickhumphries** [comment]
Ah OK, so this isn't affecting anything content (body field) wise? For the materialize stuff, we use a lot of their component classes and then style them with our own CSS for our actual content. So in writing content we use materialize tabs, buttons, accordions etc. 

We also style the core ELMS menus/GUI too but I'm guessing we'll be able to influence that afterwards with CSS changes...(maybe?) more easily than going through all courses and changing the html

**Comment by btopro** [comment]
so how I see this playing out as we work through #2019 is that we reduce all theme CSS down to 1 file (right now it's 3 core ones + a whole bunch influencing things that shouldn't be). This is effectively then "elmslnCSS" sorta thing w/ our core styling for the UI, much of it being wrapped up in the components, thus reducing our CSS / scoping the styles of things that have custom tags.

This will reduce the "elmslnCSS" more and more till it's basically just a minimized version of materializeCSS. After that, a compatibility mode that loads in the legacy materializeCSS actual library (much like foundation) should work.  Your CSS styling stuff will still be able to target cause we use what's known as ShadyDOM instead of true ShadowDOM (shadow doesn't allow CSS to influence it from outside its element so I don't like that).

Something else I was considering (though I have to look into the full ramifications of) is potentially making like a `<elmsln-content-body>` tag which could take in options for things like foundation and material styles. How this could (potentially) be beneficial is that then all those stylings from those libraries would ONLY be applied to anything inside that tag. This would allow content to look like it should today but also prevent bleed through into the larger UI (my bigger concern).

**Comment by btopro** [comment]
Added to milestone, it's a good point to raise and something we need to provide support for.

**Comment by rickhumphries** [comment]
Sounds good. Thanks for clarifying 👍
