### ISSUE TITLE
Need a drush alias for targeting all tools in a specific course

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#212]
It would be very convenient to have a drush alias for every course that targets all of the tools that are being used for that course.

For example.  If I have a site that is called "Sing 100" and I want to programmatically add a new user to all of the tools in that course, I would like a command that is something like:

```
drush @sing100 ucrt mgp140
```

**Comment by btopro** [comment]
+1

https://github.com/elmsln/elmsln/blob/master/scripts/drush/server/generate_aliases.php is what's managing that

**Comment by btopro** [comment]
naturally @ elmsln calls would pick up all targets generated by the alias file. we might need an alternate alias file like coursecentric.aliases file which is similar to generate_aliases but organizes itself differently. This could load off of elmsln.aliases and shift the array around. Otherwise we'll double and tripple up our calls on the spiders we currently have in place.
