### ISSUE TITLE
Installer improvement suggestions

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2141]
Couple of suggestions regarding https://www.elmsln.org/install-guide if I may.

1. [x]  "Organisation" label: shouldn't it be "Site URL"? I've used a real organisation title and have had to purge the whole setup, because the first word of organisation name has been used in all links.

2. [x]  Whatever puts at "Share anonymous statistics.. " it always stays "yes".

3. [x]  Since installer is strict regarding all things and inevitable conflicts with anything pre-installed, maybe it makes sense to
a) add something like "[sudo] apt-get purge apache* mysql* php* && apt-get autoremove && apt-get autoclean && apt-get dist-upgrade" at the very beginning of the script OR
b) Add a noticeable warning / info somewhere at the beginning of https://www.elmsln.org/install-guide page, which would say something like "You have to set this up only on fresh Ubuntu without any Apache\Php\Mysql pre-installed". I've learnt this a hard way so think such notice will save a lot of time for anyone else.

4. [x]  May be it worth excluding HTTPS option from the installer since it doesn't seems to work properly even on fresh Ubuntu. There is something in letsencrypt part which prevents it from working.

5. [ ] I am not really sure if installer keeps it's own log, yet it would be useful: I've mentioned some errors regarding Composer & Drush and may be other parts, which, probably, should be reported back here. Would be nice to have something like "All issues have been saved to /var/www/elmsln/install.log, please report it back to github.com/elmsln/elmsln/issues/ if there is any installation issues" at the end of the setup process.

Sorry if it sounds like too much criticism, I'm just trying to share experience gathered for several days spent on set this up.
Thanks!

**Comment by btopro** [comment]
@yurg thank you for the feedback this is very helpful. All of us involved are too close to the project to see these things so it's great to get feedback about the struggle you went through (and I apologize for it being difficult). https://github.com/elmsln/install-builder/blob/master/install.html is where that file lives and I've incorporated your feedback into it (https://www.elmsln.org/install-guide)

As for your question about the log, currently there is some minor logging but it would be nice if everything wrote out to a log I agree. 

https://github.com/elmsln/elmsln/blob/master/scripts/install/elmsln-install.sh would be the place to add that in; could you open this as a separate issue so we can close these installer enhancements out since they had more to do with the install builder mini-app instead of the actual installation of the system

**Comment by yurg** [comment]
Done: https://github.com/elmsln/elmsln/issues/2156
