### ISSUE TITLE
create a document viewer for PDFs

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2218]
It's in our ontology document. https://github.com/LRNWebComponents/ontology/blob/master/lrnsys-ontology.md#lrnsys-pdf

**Comment by heyMP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [lrnsys-pdf](https://trello.com/c/NwRSYEEH/16-lrnsys-pdf)

**Comment by proconnor15** [comment]
Looking into implementing with [pdfjs](https://mozilla.github.io/pdf.js/), using the [pdf-element](https://www.webcomponents.org/element/streetturtle/pdf-element) webcomponent. The webcomponent currently has:

- Arrows to click to go to next page
- Input field to enter the page number to go to
- Zoom in/Zoom out functionality
- Reset zoom button
- Download button

Right now each of the pages of the pdf are only loaded when they are accessed. I am trying to implement the scrolling functionality by displaying each page in a `<canvas>` element. 

@heyMP Would scrolling be the most useful functionality not included that should be added?

**Comment by btopro** [comment]
@proconnor15 could you give an update based on what I saw the other day which looked like it cleared up a bunch of the bugs previously found

**Comment by proconnor15** [comment]
@btopro Fixed:
- Made the slidebar view 25% of the screen width, no matter the size of the viewer
- When switching the pdf, the slidebar loads the new pdf

Improvements:
- Ability for user to change the width. (Height is already adjustable)
- Keep pdf centered when sidebar slides out
- If there are two of the same pdf's then the second one will not work due to the eventListener being setup by the fileName

**Comment by btopro** [comment]
@proconnor15 status update as I think we should be able to pull this into production builds as well as a published release on WC . org.
