### ISSUE TITLE
Studio image rotate button 

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2231]
Many images come in sideways. Can students uploading rotate the image before publishing it out to the studio? My neck hurts.

**Comment by btopro** [comment]
There's hurricanes in the world but sure, turning your screen 90 degrees like a normal person sounds really hard ;).

Can you shoot me an example on slack and I can see if I have to apply something to at least fix some of these based on exif data immediately? The way to tell if they are shooting it wrong would be to download the image and see if it's still rotated funny locally. This is a fix we've applied in the past to at least solve a large portion of them. I think part of #2226 would involve making an image viewer which could help solve your busted neck in scenarios where the image is shot wrong :p.

I will say to this functionality, we've been asked in the past not to add it because it became a learning opportunity to understand the orientation for a camera (after we fixed the EXIF aspect ratio not rendering in the browser which let me check on).
