### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2286]
This is probably a very daft question but I'm attempting to install ELMSLN via the command line on a linux ubuntu 16.x server. I followed the steps [here](https://www.elmsln.org/install-guide) and it went through everything correctly.

However, when navigating to online.elms.com (directed to the IP address using my hosts file) I can only see the "Index Of" listing page where it displays the files in the folder. I thought it might require install Drupal separately but when I go through to http://online.elms.com/domains/online/install.php it displays a Drupal message saying it has been set up correctly.

Is there a step I have missed out somewhere which allows the actual ELMSLN site to show when I go to the subdomains? It looks like there is no index.php (or equivalent) in the root folder of ELMSLN so is there a modification to Ubuntu's virtual hosts file which I need to do manually?

**Edit**

I'm trying to run version 0.8.1

I can view the login page by going to: http://online.elms.com/domains/online/user but not when I go to http://online.elms.com/

**Comment by JackWillDavis** [comment]
Sorry, I should mention I'm attempting to run version 0.8.1

**Comment by btopro** [comment]
hmm... sounds like apache config might be goof'ed or not reloaded. Did you do the automated 1-line install or step by step manual? automated is preferred since there's a lot involved. We have a little builder here -- https://www.elmsln.org/install-guide

Before doing that though you might want to just try restarted apache from commandline and see if the addresses pick up -- `sudo service apache2 restart` since it sounds like it's just not pointing to the correct place

**Comment by JackWillDavis** [comment]
Thanks for getting back to me. I have it working now thanks, turns out it is a VMWare issue with the command line interfacing timing out. I have a follow-up question about migrating an existing ELMSLN site into this new VM (to act as a dev version for coding work).

I was using the one-line installation (although with a minor change to checkout v0.8.1 instead of master.

Is there a way to "import an ELMS" site? Or is it a case of moving across all modules, config settings and database? (I can post this followup question somewhere else if you'd prefer?)

Thanks again for pointing me in the right direction. Once I'm up and running it will mainly be Drupal work which I'm a little more used to!

**Comment by btopro** [comment]
no problem. In the installer you can set it to use whatever branch you want instead of master since in the middle of the command is `&& git checkout master &&`

As for importing an ELMS site, it is a lot of Drupal sites so you can import individual DBs (yeah I know, not ideal). We have an internal dev server which we have a script that can sync prod down to stage. Unfortunately the person that set it up is no longer involved w/ the project so we'd have to vet that script a bit more then just getting it out the door (pretty sure it's specific to the deploy itself).

There is a script but I haven't tried it in awhile for pulling things into local dev. It would be
```
vagrant ssh
bash ~/elmsln/scripts/utilities/migration/pull-down.sh
```
You can check it out here to piece through what it's doing: https://github.com/elmsln/elmsln/blob/master/scripts/utilities/migration/pull-down.sh

**Comment by btopro** [comment]
also what was the issue w/ VMWare because that would be good to document if you are using VMWare instead of Virtualbox (which is what we use for local dev)

**Comment by JackWillDavis** [comment]
Yeah I had issues with vagrant on my machine so used VMWare instead.

I can't fine anything online but it was due to the text in the VMWare CLI disappearing on a timeout (around three minutes). Pressing any button restores the text but only the current page worth, not the entire history. It must've effected the commands in the install script as once I kept it from timing out, it installed correctly.

I'll send through a proper description shortly as I know I'm being a bit vague. I'll have a look at the pull-down script and give it a go but I can always look at importing the databases manually and moving across themes/modules etc.

Thanks again, much appreciated!

**Comment by btopro** [comment]
good to know, we'll definitely want to put something like that in our docs. @grshane when you had issues w/ your console the other day you didn't happen to be using VMWare for your VMs were you? (trying to isolate that aspect).


@JackWillDavis if you have any ?s have rick send me ur email address and I can add you to our slack channel where we hang out and help each other more synchronously.

**Comment by grshane** [comment]
No I was not using VMWare. It boiled down to the network not allowing me to connect to Ubuntu.org

**Comment by btopro** [comment]
@grshane Ha ok cool thx for verifying. 

@JackWillDavis when you get a chacne I'd you could write something in or docs associated w. Vagrant and the VMware issue you ds covered that's be great
