### ISSUE TITLE
Editing menus & theme coloring 

### ISSUE THREAD

**Issue by lifelike99** [elmsln/elmsln#2315]
Sorry if this is an obvious question.

Trying to figure out how to edit the network-nav as well as edit/remove other menus. 

Additionally, i'm still unsure how to edit the coloring of different aspects of the theme, I have applied the patch as discussed here https://github.com/elmsln/elmsln/issues/2254 but i'm not sure if the changes i am trying to achieve are possible? 

See the below image to describe the changes i am trying to achieve. 

![menu themes](https://user-images.githubusercontent.com/23331137/32259618-cd989b86-bf15-11e7-9736-d152a7cd5c63.png)

**Comment by btopro** [comment]
End of the day this is drupal so things can be heavily modified / overridden (this is part of the point of us using drupal). @rickhumphries may be able to shed light on how they've customized things because they have a lot of custom colors going on. Code / css can always hijack things in this way.

As for the links on that bar there's 2 options. In the context of a course (so go to a course space) you can hit the course name in the left side of that bar and a menu open then click this link: 
![2017-11-01_10-10-29](https://user-images.githubusercontent.com/329735/32278724-f6ed03e2-beec-11e7-8c48-a8c528f7cc70.png)

Here's some lines from a custom module we have to make some changes (assumign a module named `my_elmsln_changes`):
```
/**
 * Implements hook_page_build().
 */
function my_elmsln_changes_page_build(&$page) {
  $path = drupal_get_path('module', 'my_elmsln_changes') .'/';
  drupal_add_css($path . 'css/my_elmsln_changes.css');
}

/**
 * Implements hook_cis_lmsless_theme_vars_alter()
 */
function my_elmsln_changes_cis_lmsless_theme_vars_alter(&$vars) {
  global $base_url;
  if (!isset($vars['network']['services'])) {
    $vars['network']['services'] = array();
  }
  if (!isset($vars['services'])) {
    $vars['services'] = array();
  }
  $vars['network']['services']['Network']['inbox'] = array(
    'title' => t('Inbox (Canvas)'),
    'url' => 'https://whatever.instructure.com/conversations',
    'machine_name' => 'inbox',
    'icon' => 'inbox',
    'weight' => 15,
  );
  $vars['network']['services']['Network']['calendar'] = array(
    'title' => t('Calendar (Canvas)'),
    'url' => 'https://whatever.instructure.com/calendar',
    'machine_name' => 'calendar',
    'icon' => 'calendar',
    'weight' => 16,
  );
}
```


1st part wires in a custom css file of your choice. 2nd part adds custom links to that bar

**Comment by btopro** [comment]
@lifelike99 please feel free to issue pull requests against our documentation pages to clean up / answer these questions. You can find our docs in the repo itself here -- https://github.com/elmsln/elmsln/tree/master/docs

**Comment by lifelike99** [comment]
Thanks for the help. Edit network links does not seem to work for me. Adding links seems to have no effect.

**Comment by btopro** [comment]
Make sure you set group to `Network`. There's some definite need for docs in this area but the Group value has to do w/ the heading utilzied either in the "More apps" fly out on the right for admins or the top bar which is technically `Network`. Network should probably be the default since that's what most people would think they were doing.

**Comment by btopro** [comment]
@lifelike99 commit should at least clear it up while on that page if you putt the latest of 0.10.x. Additions to our documentation section would be much appreciated if you could contribute a pull request to help others that might run into this in the future -- https://github.com/elmsln/elmsln/tree/master/docs

**Comment by lifelike99** [comment]
You were spot on with the group setting! Changed it to Network and it is functioning fine.

**Comment by rickhumphries** [comment]
Hi @lifelike99 - as Bryan said, we add a lot of custom styling to the theme using the CSS Injector module which we added to config `/elmsln/config/shared/drupal-7.x/modules`
We basically just spent a lot of time using the Chrome inspector tool to target things, see what we wanted to change and then added it as a CSS Injector rule. We don't really use the in built theme options as you just get a lot more control using CSS and we're comfortable using it.

**Comment by btopro** [comment]
#2293 related, closing as the entire menu top part is up for review
