### ISSUE TITLE
Easy way to install?

### ISSUE THREAD

**Issue by ugintl** [elmsln/elmsln#2350]
What if I do not want to use vagrant? Can you provide me the export of your current website and database so that I can just import and use it?

**Comment by btopro** [comment]
We have an installation guide as well as an automated installation builder -- https://elmsln.readthedocs.io/en/latest/INSTALL/

Vagrant is for local development and getting something to play with though there is a Vagrant to AWS script out in the community that isn't supported yet.

`Can you provide me the export of your current website and database so that I can just import and use it?` - No, that's not possible in ELMS:LN. ELMS:LN is not a single database, it's a network of solutions that set themselves up and are positioned for current and future scale. It's not a single drupal database (if that's what your asking) it's many databases, drupal and non-drupal systems and automation and single sign on mechanisms to stitch it all together

**Comment by btopro** [comment]
closing as there is an easy way to install and the question of asking for a database to import is not possible. please submit other issues if you have issues getting any of our existing methods setup.
