### ISSUE TITLE
Installatron

### ISSUE THREAD

**Issue by Pahkis** [elmsln/elmsln#2422]
Hi there BTOPro et. al.,

Sorry, I realise this is probably the wrong place for this, but I have not yet managed to find a more suitable forum by which to contact you.  My name is Chris, I am an education and training services professional who would like to set-up his own on-line education business. However, I am an amateur hacker when it comes to site building and development.

Bug: (Its been bugging me to exasperation!)
- ELMSLN installation on shared drupal hosting with base drupal profile already installed via Installatron 

- What happens
Nothing so far

- What you expected to happen
No Idea, but would like to find out

Feature request:
- What you are trying to do / where it should go

The site I want to build involves some distinct working areas for different student membership grades and service types. I.e. The LMS would be one part of a broader learning eco-system containing 3 course types/membership domains that may or may not contain various facets such as collaborative learning facilities, Student & Learning Self-regulation mechanisms, Portfolio/Learning Showrooms, learning resource (libraries of study references and study aids/webtools etc.) and business oriented information service (_Infosites & databases_) centres. I.e. a 360 degree Learning Eco-System based on my own pedagogy and business models. To achieve this I am considering ELMS-LN and the new GROUP module which, may make the need to use the multiple domains, sub-sites modules or even Organic Groups unnecessary. 

Though I have watched videos and read endless streams of documentation I still have not seen anything clearly showing/demonstrating ELMS capabilities as CMS based Learning Management environment/system. My techie friend is also convinced that ELMS-LN is merely a networking platform without the needed functionality and hence in favour of other seemingly easier and less risky (continued support wise), but, more traditional if not out-of-date LMS systems. Personally, I have been very uneasy about the suitability of other options we have tested (E.g.  Opigno blocks based system) and found considerable affinity with the concepts and principles you have espoused. However, I do need to know:

1.  Can ELMS support this kind of Business and Information Services oriented Learning Eco-System?
   - Does ELMS-LN already include that LMS type functionality or do I have to import some other system  on or into it? 
 - How stable/reliable is support for this distribution?  (_I.e. Still need to convince my IT friend about the risk_s)
2. If I have to add some further course/learning management system, 
 - can it be integrated as a sub-elemental Learning Management Centre in this framework?
 - Would Opigno work with ELMS-LN?  If not what would you suggest... OpenEdu? PHPEdu?

I have a shared hosting service (GoDaddy) which, installs a basic drupal profile using their Installatron programme. I have set-up devsites in the main domain (D8) and sub-domain (D7 & D8) for both learning and development purposes. 

I am having trouble finding clear instructions on how to install distributions in this environment. I have set-up the command line interface and have been getting to grips with the use of composer (_had to write/copy-paste my own plus json file scripts that I don't yet fully understand)_ as a dependency manager to install the contributed modules and themes - a necessity for some of the modules and functionalities I want to install at a later date.

3.  How then , do I install the ELMS distribution in this shared-hosting environment?
 - not with the one-line install command I presume!?

Thanks for your kind understanding and patience.

Kr,
Chris

**Comment by btopro** [comment]
Hi Chris -
You found the right place so thank you for posting this in our queue! A lot to unpack there for sure but let's see if I can help.

`ELMSLN installation on shared drupal hosting with base drupal profile already installed via Installatron`
- No. this is not possible. We do not support drupal shared hosting. ELMS:LN is meant to be installed on a server and sets itself up from there. Unlike a traditional install profile, a core piece of the ELMS:LN architecture provisions new drupal sites automatically. When creating a new course, you are actually creating new drupal sites (well, the automation is at least).

If shared hosting is a requirement, a smaller scoped system like Opigno may be the way to go. You have expressed the real issue in education / training solutions. Do I go with something that lacks all innovation what so ever, but works and I put little effort into managing? Or do I support the future and build a better mouse-trap that may teach people more effectively (it will).

If you want install this and we're good to teach - elms:ln isn't for you just yet. It's going to get there, in fact soon to be pushed out updates make drastic UX improvements, but it's still attacking the problem space in a way that allows for sustainable innovation. For example, @rickhumphries adopted ELMS:LN 3 years ago. I saw a video recently and it made me realize just how far we've come. He's showing media interfaces that we've since improved, workflows that are drastically faster then they were previously.

"But so what, all platforms get better over time." - True, platforms get better and easier to use; but educational systems are uniquely positioned to some how not follow this pace. Things in education tend to be built for singular purpose and stay there forever. A discussion board in any LMS will always look and function like we live in the early 90s. I'd feel differently if any LMS proved me wrong. I've used them for 12+ years now and seen them go from poor CSS / table based layouts to Bootstrap skinned div tags. Pedagogically, they are identical though. Post a title + text, people respond linearly and it gets lost.

A tangent for sure but the reality - When we focus on discussion boards (we have crappy ones now) they will transform from boring to amazing. The chicken and egg problem is adoption within a community to help it grow and grow with it or use something that just gets the job done. Similarly we'll automate upgrade from Drupal 7 to Drupal 8 based systems (or wherever else we go in the future, GravCMS seems likely as well). We're changing the game, not simply keeping the wheel spinning.

As for your technically minded friend you reference, they are incorrect in this assumption. ELMS:LN gets the networking name from the fact that it is actually a system of systems architecturally. When you create a course using 1 system, that course is setup in another. Users get seamless access as people are logged in as they get there (much like Google between multiple systems). Our major systems that have received the most focus as Asset management, Content production, Studio based instruction and an information system to piece it all together.

As for sustainability; This is supported by multiple Colleges at Penn State. There are currently 5 actively employed people that have core commits at the university + some contributors from other places like Buttercups training in the UK. Our code base has contributions from far more then just Penn State as we utilize the best of open source solutions (Drupal, GravCMS, many many libraries, Polymer / Web components). As more people contribute to our elements and word spreads of what we're doing (as it keeps getting easier to use) it'll start taking off more. It's also built on technologies other developers understand. You won't make a job posting for Moodle and get a ton of people unless they are in edu-space. Make a posting about Drupal, or Web components, and you'll find people easily.

I hope this all helps. I don't want people adopting things that aren't for them. If this seems like it's of interest and you want access to the future of edtech, feel free to join us on our journey. If you need something that you can click, install and forget (but not improve much) then traditional LMSs are the way to go.  I will say though, that this is our authoring solution we'll be rolling out in the coming months and.... no one has anything like it -- http://haxtheweb.org

**Comment by Pahkis** [comment]
BTOPro hi,

Thanks for the prompt and highly informational reply, certainly far quicker than Opigno to date  :)

Shared hosting is not a requirement - but, the server my tech-friend set-up with Opigno was so unstable it seemed to crash every time I so much as looked at it. That's why I took up a shared hosting, so I could maintain system with back-ups for myself, play, learn, experiment and break-it without fear or too much extra hassle. 

1.  Borderless learning:
Despite your confirmation of ELMS-LN content creation and course management capabilities, I am still hazy on how well, in concrete terms, that lends itself to the need for a tiered approached involving learning activities, programmes, courses, lessons, paragraphs and content items? 

For example:
 - I need to be able to create a multi-level membership framework with a tier structure for individual lessons as well as for courses and programmes, at least within our core membership area. Obviously some of these tiers will have access requirements in terms of previously completed courses or lessons, which as much as possible should be automatic, unless a pre-test or other screening is required. 
- Content entities down to the paragraph (text) and item (video, images,  audio podcast) level need to be re-usable via referencing and linking.  This presumably involves uuid level referencing and linking to make it easier for teachers not so well versed in the system as dedicated content editors might be.
- Topographical features for planning and navigating personal and pre-set learning paths (programmes?) are needed as part of a progression towards a full  Augmented Reality Learning process rather than just technological gadgets. This means a tiered development path, crowd sourced contributions, study aids, (web)tool and collaborative resources generically available from a resource centre/library and contextually (relevance) from within course and lesson pages in a consistent layout/location.

2. Catch 22.1: 
There is only me and a limited amount of help from my techie-friend at present, though I would like to get other contributors from the drupal community to ease and speed up the process.  Yet to do what I want to do, Extensibility is very important if the business is to be sustainable. So, yes, despite the limitations of our current capacity, I do want to Flip the entire Education system, not just the classroom. This potential capability is what drew us to Drupal in the first place. But, if we need to extend and customise on your system**, is this something we must do for our selves?** _

If so, then what happens when you upgrade in the future? How can we ensure that we still move forward together?_ _I want to do more than just post content, which, it seems, constitutes a 'course' in the eyes of my techie-friends who thinks I can just keep rewriting content and courses every time we upgrade with a new functionality/feature (_There will never be time to do this, so although content and features will evolve, the critical framework and infrastructure for supporting the pedagogy model does need to be in-place already_). Innovative Pedagogy providing the learning processes (wrapping around the content that actually constitutes the course rather than just content) and a 360 degree P2P self-regulation system is at the heart of the learning environment  I want to create.  Clearly it is not intended to be a conventional higher-education institutional system, but one which has its focus on a self-sustaining education business, al-be-it.. 'Highly-Educational' ;-). There are many facets (portfolio of features and functionalities) that can help to achieve this from statistical performance analysis  to reputation management systems (e.g. voting api etc.), most of which are already available in Drupal as contrib modules, subject to configuration capabilities._

3. Catch 22.2: 
As noted, this again raises the importance of my other question in respect to Support vs. Extensibility. A worry is that you are unable to provide the range of extensibility/functionality I am seeking and we therefore need to add/integrate functionality via other contributed drupal modules and apps. Extensions for commerce management and student registration etc, that are usually handled by other systems in HEI's are also a requirement. Though the journey you describe is conceptually enticing and I would much like the support and company of a community of like-minded education professionals, I am worried about the forks along the way. Your comments about GravCMS seem to underline this concern - though I presume it is php based just as drupal is -  as non-techie I am not clear **how?** this specifically would affect future service functionalities and features, not to mention course and content migration. 

**OPIGNO at a Glance**:
Opigno looks flexible and manageable at first sight, but is focused on blocks rather than Paragraphs and Panels/Panopoly approach and sub-contracts other critical infrastructure.  I.e.:

1. Whilst blocks may be OK for the main course presentations, collaborative learning areas in which user groups from student assignment projects to External Associate Teachers,  ePublication and editorial management groups need a little more flexibility and control over their work areas, that has thus far been achieved in Drupal by Organic Groups. This means a multisite or themed sub-sites is needed unless the contrib module GROUP can do this more simply.
The external teachers and groups obviously need a simpler and easier to use working environment and tools set than internal teachers and learning managers that will create the core courses according to our own pedagogic model. I have seen a couple of other very interesting developments also, such as: Stacks, Bricks and anything else that will help make document, lesson and course creation for casual/part-time teachers and other users easier and in accordance any pre-set quality and presentation criteria.  

2. Though Opigno is designed as a wire frame system under the mantel of flexibility, I have so far found that - out of the box - its content creation capabilities, catalog taxonomy/presentation fall woefully short of what, in my view, is needed/acceptable to even start creating courses and content.  I am also unclear as yet if Opigno has to be the main focus of the system or can be loaded into a sub-site as part of a broader learning environment (such as ELMS) in which users can easily identify and navigate to the various resource and activity centers.  For example, though content is rather lacking, this is my D8 sandbox site: http://www.liikanjitsu.club/lol-liikan - where I have used a simple tabs presentation for the resource centers. Most of my learning efforts with content creation modules have so far been focused on my D7 site, which just crashed with a 'Fatal Error' ;D

3. Opigno farms out its content creation (H5P) and collaborative facilities to external service providers, which raises issues of both adequacy and control (ownership and privacy) of content that needs to be referenced and re-used.  The ability to object orient / entitify all lessons and content items for easy linking and re-use in other lessons and courses is an important tenet for a multi-tier lesson. course & learning system, for which, the Opigno slide system goes part way to, but still leaves me lost and confused when trying to locate and link to the relevant content objects/entities - though that may in large part be due to my own inexperience and lack of understanding still, if I am having trouble with it, part-time external teaching associates certainly will. 


Finally! :)
Yes, I know I am asking a lot of any system, but, I am a dreamer, and I have had this dream for quite a long time - and so keeps getting bigger ;-).  Open source and modular systems such as Drupal have for the first time given me a glimpse and some hope that the dreams might be feasible.  However, the time for idle dreaming is over and only the technology system/strategy is holding me back. I need to make a decision and get on with building the site and creating content and courses to get the snowball rolling as soon as possible.

Anything you can do or teach me in order to realise them would be a God Send.

Bw,
Chris

**Comment by btopro** [comment]
"Learn / Break it" - So this is where ELMS:LN has two key advantages. 1. We have a Vagrant file built into the repo itself so you don't even need a server to mess around with and start to go "is this for me". https://elmsln.readthedocs.io/en/latest/development/Vagrant-Step-by-Step-setup/ has the directions for getting dependencies setup but basically you'd want the 0.10.x branch of the project.
```
git clone https://github.com/elmsln/elmsln.git
cd elmsln
git checkout 0.10.x
sh developer
```
(see directions for more flexibility but that's the basic setup) Will build you a server and start setting up ELMS:LN on your computer to play with.

2. Opigno / traditional Drupal says "have fun setting this up on this rig" while our "one line installers" heavily optimize the server to run the production level configurations that we have. In this way, ELMS:LN has deeper control over the entire server not just the application layer. It sets up from nothing (apache, mysql, php, installing optimizations, plugging in domain entires, all of that jazz) to get you way further way faster. Our install guide has an interactive builder to suggest the copy and paste 1 line install https://www.elmsln.org/install-guide

We've installed on AWS, custom stuff, pen-drives (for testing), digitalocean.com and other places with success.  Especially if your in the "I just want to mess around" then it's a great platform for getting going w/ that pretty quickly bc of all our automation.

"Borderless learning"
That's understandable. We don't really prescribe that stuff, we've got a lot more of "here's the tools to create educational material". Usually what we've made starts to make more sense when playing w/ it but here are some public examples:
http://stem-researchethics.org/ -- customized ELMS:LN instance for OER content
https://courses.openulmus.org/xapi/ -- an open course that has self-assessment items and more rich media in it to teach people about xAPI (the site then generates statements which we've given talks on showcasing how that can be used, etc)

"multi-level membership framework"
We are positioned to do this as our CIS system is a course information system and disconnected from the course spaces (architecturally). This allows for flexibility to be added there for things like paid membership levels, unlocking access based on criteria, etc.

"Content entities down to the paragraph (text) and item (video, images, audio podcast) level need to be re-usable via referencing and linking."
This is an area ELMS:LN destroys "competition" as everything only works bc of resource references. The entire system is a giant API of APIs :)

"Topographical features for planning and navigating" We've had discussions of this; some of this could be done in the Open studio (think flickr crossed with trello but in an edu / course context). It's an areas we definitely need some more growth in.

Catch 22.1: We've built on Drupal / Web components in order to make it so that people from these technology stacks can jump in. As for upgrades, we provide upgrades in a heavily tested and automated manner for roll out (internally). Penn state has multiple ELMS:LN deploys, 2 with over 100 drupal sites. We usually pick a smaller deploy as the 1st mover once it gets to that point (like last night when I just did this with 1) after we've gone through our staging process. Our development workflows are pretty solid aside from needing more automated test coverage both on front-end and back-end. travis-ci helps ensure our system builds each commit and runs automatically to at least let us know thigns would "blend" so to speak.

Catch 22.2: I wouldn't worry about forks. https://github.com/elmsln/elmsln/tree/0.10.x/core/dslmcode is where drupal and grav live. It's more about picking the right tool for the job. Grav is being reviewed for personalized student portfolios so that they could easily be given a zip file of all their work w/ us and take the whole site with them. Drupal will never be that. Similarly, Grav will never be powerful / flexible enough to do what we need and NEITHER of these are as UX powerful as Polymer / Web components :)

We also have support for H5P installed locally. The issues you mention are like an apples and oranges comparison associated w/ Opigno, we just view and approach the world differently. This isn't a traditional singular drupal site. This is an architecture that leverages Drupal in a very interesting way so that we can sustainably innovate together. Eberly college of science has had many little "forks" of innovation (site building, trying new modules, etc) which we've then incorporated back into the project. IF they need to "fork" it might be on like "we like this version of mathjax in this one course". Cool, do that. It doesn't impact the project as a whole and you are still able to upgrade with it.

If authoring is a thing for you then check out haxtheweb.org and realize we're building that for ELMS:LN (it's in some prototype branches now)

I'm a dreamer to so I can appreciate that. I've dedicated my life tot his platform and how I think it can positively impact society through OER, open education, and new, vibrant, humanizing tools to create deeper empathy in society.

**Comment by Pahkis** [comment]
Great info!

I'll no doubt get back to you when have had time to process / investigate it all - not to mention update my techy-friend's assumptions ;-)

Many thanks again for your help and openness :)

Bw,
Chris

**Comment by Pahkis** [comment]
Hi,
I installed virtualbox, vagrant and git as instructed (as far as I can tell ;-). 
Then closed the VB and rebooted the computer as requested.
I ran the git command but windows power (W10) shell does not recognise it.

Was I supposed to open the virtual box first or initiate the first VM first or something?

Kr,
Chris
--------------------------------
PS C:\Users\chris\Documents\ELMSLN> git clone https://github.com/elmsln/elmsln.git
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git clone https://github.com/elmsln/elmsln.git
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
PS C:\Users\chris\Documents\ELMSLN>
----------------------------------

**Comment by btopro** [comment]
https://stackoverflow.com/questions/17457182/how-to-install-git-shell or https://www.cygwin.com/install.html should help

**Comment by Pahkis** [comment]
Hi,
Everything (virtualbox, vagrant, git) seems to be installed correctly now, but, not sure how to proceed from here.

The vagrant up command seemed to work after first opening the VirtualBox application (_I omitted to do this the first time around_ ;) and ensuring that the elmsln item is 'running'.

Next comes up another CLI for virtual box with a couple of options for Ubuntu and ubunto extras. I had no idea what IU was supposed to do here, so I selected the former. The cli is now empty, although auto capture keyboard option is on ~ a tad disturbing.

If I understood correctly (it was not specified), I should now simply enter 'http://online.elmsln.local/' in my web browser and  log into this with user: admin | password: admin. To connect to the console cli of my instance, I should type: "vagrant ssh"  into the VB CLI ?

However, it can't find or reach this site/page.

The notes also state that: _If this address doesn't resolve, you may need to do this extra step at the bottom in Legacy - host file management_ 
Further down the vagrant step-by-step setup instructions page, under 'Legacy - host file management' it states that: _This step is now only required if you don't follow the above directions about how to get our development environment up and running. Add this code to your /etc/hosts (or windows equivalent)_   

- Do I need to do this?

- If so, I  have no idea what the w10 equivalent of /etc/hosts would be unless it is simply: cd \users\chris\documents\elmsln - 

- Is this done within w10 Power Shell or the VirtualBox CLI?

Questions:
- Is there something  I have missed or miss-understood?
- Assuming all is at it should be, how should I proceed?


As you can see, all this is way beyond my comfort zone ;-)

The instructions, whilst for the most part clear, missed what for you would be rather obvious requirements leaving me rather nervous and hesitant ;D

I have kept a copy of all the returns (feedback) from the W10 Power Shell session just in case that is need to check and clarify what happened and where I am at.

Looking forward to hearing from you :)

Kr,
Chris

**Comment by btopro** [comment]
So you're very close. To access our vagrant instance running on your machine, you need to have your computer understand where it is. On OSX / Linux this step happens automatically, Windows can be finicky.  Your computer has a 'hosts' file which effectively allows for rewriting URLs from the browser via that file (so that calls for online.elmsln.local actually point to 10.0.18.55 instead of nowhere).

Read this tutorial on how to modify / find this file based on your system https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/

to clarify the CLI: Vbox CLI is actually a tunnel into the server. You CAN access the server this way (so equivalent of logging into a system sorta deal) however when we typically access our machines we use `vagrant ssh` on our computer to "login" to the "remote" system. It all gets a bit confusing since it's actually just another part of your hard drive but `vagrant ssh` acts like you are tunneling some place else (the some place just happens to be running on your machine).

**Comment by Pahkis** [comment]
Hi,

I edited host file with:
10.0.18.55 online.elmsln.local #elmsln vagrant virtualbox

**Comment by btopro** [comment]
entire list yes

**Comment by Pahkis** [comment]
Hi,

Thanks.

I have tried it with both normal and headless start, but the AMD hardware acceleration issue seems to be a show stopper.

Looks like I'll have to talk to my techie friend about setting up the full version on a separate server.

Does all the ELMSLN stuff delete automatically if I uninstall the VB and Vagrant?

Bw,
Chris

**Comment by btopro** [comment]
I see, that sounds like your computer is not allowing virtualization. See: https://stackoverflow.com/questions/45409664/vt-x-amd-v-hardware-acceleration-is-not-available-on-your-system

**Comment by Pahkis** [comment]
Hi there,

Long time no hear :-)

We sorted the hardware acceleration issue and ran vagrant up from power shell. (Having already done this once immediately after  running the vagrant plugin installs,  I had thought I just needed to click elmsln 'start' in virtual box, but techie friend convinced me of the error of my ways ;)

We then tried to load via browser, but would not accept the admin id and password.

Apparently there appears to be some problem with shh keys now - where and how to install them etc. I have already created some via GoDaddy C-Panel and downloaded them, but, what to do with them!?

I have to say, that thus far, this has proved almost as big a challenge (nightmare for plebs like me ;) as trying to make Composer work correctly on Drupal 7.  The latter is more weird and wayward in its creation and results than my craziest dreams after eating a heavy late dinner (Curry usually) with strong red wine.

I definitely prefer the latter!

Kr,
Chris

**Comment by btopro** [comment]
which admin id / password? It creates one at run time which is not admin/admin if on godaddy hosting. I'm sorry your having such issues getting things up and going (hate composer as well). drush is installed on the box so if you can SSH in then `drush @online uli` should supply you a one time login link

**Comment by Pahkis** [comment]
Hi,

No, this is on my laptop with windows 10. On the Vagrant [instruction page](https://elmsln.readthedocs.io/en/latest/development/Vagrant-Step-by-Step-setup/)

It sais that after installation... (command: "Vagrant up" using power shell cli)

- Go to http://online.elmsln.local/ in browsers
- You can log into this with user: admin | password: admin

The only thing left in the instructions I have not tried is the legacy host file management step but, it is not clear to me if this has anything to do with it - given that we did follow all the instructions ;-).

Kr,
Chris
