### ISSUE TITLE
Upload file destination

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2451]
v0.8

We've implemented the Webform module on some courses to allow learners to upload and submit a file to us. 

I've set the upload destination to 'private' so that only admin can view the files, but I also want those with the staff role to be able to view the file too, which they can't as they get an 'access denied' message and I can't see a user permission related to this.

I also noticed the following options on where to store the files:

![image](https://user-images.githubusercontent.com/4973810/38302486-c5ba624c-37fa-11e8-9dc0-af528dc611ae.png)

I just wondered if choosing either of the ELMSLN options would work for this purpose?

**Comment by btopro** [comment]
`View private files` is a permission under 'File Entity' and should allow access to those after the fact (though I believe admin is the only one that can see it by default). DO NOT use those other 2 file destination types. They are there for internal pathing only so that we can cheat on some calls for media (give me the banner for a course but get it from the CIS). It's not an actual file storage mechanism but Drupal doesn't know that :)

**Comment by rickhumphries** [comment]
Got it...I'll steer clear of those others :) Just realised that I needed to switch on the file_entity module to get those permissions to show but I see them now. Thanks for that
