### ISSUE TITLE
Bakery logout on slave sites should logout of Master site too

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2512]
Bug:
- 0.10.x

I've noticed that when logging out of a course site (which is a slave site to the CIS), the user will stay logged into the Master site  (and therefore all other sites in the network).

I think in terms of user security any site logout needs to also log out of the Master site. 

I know the 'login destinations' module may provide a solution if set up as a standard feature on each site, as you can specify a redirect to `https://online.site.co.uk/user/logout` at the same time. But I thought we may need a similar solution to this that's baked in.

**Comment by JackWillDavis** [comment]
@btopro 

I've managed to get a unified logout working on our development server by adding:

`$cookie_domain = '.example.com';`

To the `shared_settings.php` file in config which is now logging the user out of Master from a Slave site. Not sure how this can be contributed unless it's just added to the documentation? Bakery seems to need the setting for logouts in any case.

**Comment by btopro** [comment]
hmmm... so we do have a elmsln_bakery module. Maybe in the .install of that this could be set some how automatically. If you look in that file you'll see how elmsln_bakery engineers the M/S relationship in a generic, domain-less way

**Comment by JackWillDavis** [comment]
Not sure how best to proceed with this. It looks like if there is no `$cookie_domain` setup in `settings.php` then Drupal creates one in [drupal_settings_initialize()](https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_settings_initialize/7.x).

Would the best option to fire a function after `drupal_settings_initialize()` which amends `session.cookie_domain` using `ini_set()`? I assume since this is on the fly it would need to be done/checked on every page?

Or would something to open the `settings.php` file and write a config value during `elmsln_bakery_install()` be better? Not sure about this one as there's no write permissions on that file by default which would need to be changed in code.

**Comment by JackWillDavis** [comment]
Unless I can add it into the install profile?

**Comment by btopro** [comment]
hmm.. there's probably a `$conf['cookie_domain']` tho right? that's how you can force global settings in drupal to apply to config

**Comment by btopro** [comment]
oh... iu didnt know drupal had a global cookie_domain value... hmm...

**Comment by btopro** [comment]
so if this was calculated in shared_settings.php OR that you wrote it into your config shared settings, that would probably be the best option. A line in shared_settings.php (commented out) that says how to set this ahead of time might help -- https://github.com/elmsln/elmsln-config-example/blob/master/shared/drupal-7.x/settings/shared_settings.php

**Comment by JackWillDavis** [comment]
Yeah it's a global so no access via `variable_get` unfortunately. I've just added the option to that shared_settings file and put in a PR there.
