### ISSUE TITLE
ELMSLN tool Builder

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#26]
# ELMSLN Builder

## Description of functionality
Enable anyone to add complex functionality to ELMSLN courses by adding a user created custom Drupal site in a repeatable way.

## How would it work
* You get a “build” space for custom Drupal site building 
   * Uses a standard Drupal distribution designed to make this process easier
* You can publish the newly built Drupal tool to a specific course
   * Server addresses and other connection settings are automatically configured
* You can publish the new tool for all courses
* You can publish the new tool to ELMSLN project, so it’s available for all systems

**Comment by btopro** [comment]
And be able to do Pull Requests

**Comment by jonpugh** [comment]
Pull requests on the curriculum?

**Comment by btopro** [comment]
This would be using a UI to actively build new toolsets into the system, automatically producing distributions without people knowing how to do so (using profiler builder and drush recipes / DDT). Kicking off a script in the UI (obviously in a developer mode) that would author a new stack and link it into the product, update all parts of ELMSLN's code to act as if it had installed everything automatically (as if I sat here and ran the commands / manually put code in place) and do everything in a compliant way. Then, after these modifications / ability for someone to make their own new thing out of the factory of things; they could push a button which would update their (elmsln managed) git repo and then automatically issue a PR against elmsln.

This would be the "features" of ELMSLN tool building in which people without technical knowledge could contrib their remix of ideas to the system in a very technical way. These images / PRs could be turned into patches and even added to a service of their own so people could share their creations.

All in theory... though a lot of the under the hood stuff needed to pursue this are already starting to shape up.



Curriculum would be nice too (hell of a lot easier) ;)

**Comment by btopro** [comment]
very close to having the backend work required to make this happen cause... yeah... whenever mike leaves the country I try to do something insane.

**Comment by btopro** [comment]
all hardcoded definitions have been removed under the hood! When developing locally you could issue:
`bash ~/elmsln/scripts/developer/create-new-tool.sh assessment assessment 7.x-1.x authority`

This will correctly establish all of the following:
docs/domain.txt file addition
core/dslmcode/stacks/assessment
core/dslmcode/profiles/assessment-7.x-1.x (by duplicating the ulmus-7.x-1.x directory)
It then rewrites all the file names in this folder to match assessment, creates a sub-theme that will work w/ a menu positioned in the left fly out called Assessment Navigation. It modifies its info file based on if you select authority or service to build so that it will correctly position itself in the network to operate as one of these two tools.
Based on this decision it also makes the correct files in domains/assessment (service it has the files prepped for symlinking, authority symlinks directly to the stack)
It also modifies the example configuration directory so that it has the correct base files in place that can be pushed up for the working example repo online
it also starts to create a git repo for the newly created distro

So now from here, we just need a website that builds this stuff and then does the auto github PR / deployment integration. From there we need to make the system automatically stand itself up similar to what it does in the Travis CI auto demo upgrade routine that we currently have and don't talk about much :)

**Comment by btopro** [comment]
This is working in a nearly automated way and will have a video shot once automated / having a form to make it something possible to do via the UI. right now it's backend job only after copying and pasting a key; obviously we want this automated :p

**Comment by btopro** [comment]
- [ ] automatically create ~/.ssh/config
- [ ] include keys with repo
- [ ] make UI module in innovate_helper

**Comment by btopro** [comment]
well. this is verified to have worked from a clean vagrant rebuild. Future steps of making an innovation viewer that reads off the repo can be new / future discussions that reference this one (especially since they are beyond the original scope of this which was already ridiculous)
