### ISSUE TITLE
Supported Browsers going forward

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2608]
This is definitely something we want to discuss a bit though the data backs what I'm going to claim a bit so it'll be hard to talk me out of it...

Moving forward, we should stop supporting IE11 and any browser that doesn't support ES6 syntax. We will continue to transpile and serve polyfills for quite a while but I don't think we need to keep trying to lug these few browsers along. Here's why:
- Microsoft said to stop using IE11 awhile ago, in Jan 2020 they kill support for Windows 7, the last OS of theirs NOT to have Edge on it
- Edge is being hollowed out to be chromium based, meaning support there will be normalized w/ everyone else and we'll get a 0 polyfill route to web components on all browsers
- These are the numbers as of this week http://gs.statcounter.com/browser-market-share#weekly-201908-201908-bar
Digging into the numbers a bit, right now HAXcms (which will not support IE11 / ES5 browsers) would currently still successfully serve 95.37% of all global traffic. That's extremely high considering that IE11 is still more widely used then Edge by these latest numbers (and in general that's been true the last few years).

As ELMS:LN is pretty pegged to where HAX / HAXcms are heading (from a UI side at least), this would pit it's browser support against HAXcms which, while still new and still in development, is being engineered with an eye toward the near future where IE does't exist.

@rickhumphries I'd love to know your perspective / control over browser support, if there are legal requirements or governmental regulations in this space or not and how you think we should go about timing this.

Right now HAX supports IE11 (though I don't really test it much) and should work with like 99.5% of the web traffic out there. The elements of HAX / LRN / ELMSLN all should work with IE11 though we don't test it. Testing is extremely time intensive and increasingly nets less and less of a gain. Again today in compiling these numbers even and testing things w/ integration routines that's another 1/2 a day down the drain that could be spent just building.

Plan as expressed and then up for debate / discussion:
- 0.10.1 still supports what it supports, no major change here
- http://outdatedbrowser.com/en/project is injected into elmsln theme layer, which should start to notify people "hey, this is old please upgrade" proactively
- 0.11.0 stops paying attention to IE 11 / ES5 browsers, we don't block them or anything but stuff will not be tested for supporting them
- 0.12.0 transpiling / babel removed, effectively killing all ES5 browsers and forcing an upgrade by the end user

Timing would be for 0.12.0 to be beyond the Jan 2020 marker by which Windows 7 / IE11 should die. We can review the numbers again before removing the transpiling though quality of experience on transpiled browsers 6 months from now may be pretty meh as a result of us not paying attention to it.

@nikkimk @heyMP tagging for additional thoughts on this plan / if this makes sense / how we can mitigate issues in a roll out (I'm going to look into that outdated browser script right now for HAXcms #105)

Additional references:
EU numbers on browsers (95.19+ as of today) -- http://gs.statcounter.com/browser-market-share/all/europe#weekly-201908-201908-bar
US numbers on browsers (93.17+ as of today) -- http://gs.statcounter.com/browser-market-share/all/united-states-of-america#weekly-201908-201908-bar

**Comment by rickhumphries** [comment]
@btopro I completely agree with the direction of travel and eventually removing support for IE11. It's one of my major points of irritation too, but the stats for access to our system aren't quite as optimistic as the ones's you're referencing. These are the 2019 stats for learners accessing our ELMS:LN system:

![image](https://user-images.githubusercontent.com/4973810/53404509-bc224a00-39ad-11e9-9099-e1c3a073fd76.png)

The reason I imagine this is much higher is because of the number of old computers in pharmacies where a lot of learners would do their training. If the operating system is Windows 7, then the default browser is IE11.  Some large pharmacy chains would prevent the individual branches from being able to download additional programs which then prevent a challenge for us in having control over, or advising to use another browser.

We do also have site notices up already asking people not to use IE11 if they use it, so it's something I'm chipping away at, but having zero support for IE11 would (currently) be a major headache for us.

I can start to speak with the employers we work with and ask them what their future plans are post Jan 2020 to upgrade to Windows 10. If we get a positive response then I can't see an issue with the plan you've outlined above, but I suspect it'll still be a few months after that they'll actually get their systems up to date - so it just all depends on that really

**Comment by btopro** [comment]
That's really good to know (and we're evidence based on this one for sure) -- https://twitter.com/mweststrate/status/1100336634946560000 which is a big blocker for keeping IE11 (Mobx maintainer) just told me that the 4th version is still very popular bc it can hit IE11. If there's no functionality differences (@heyMP would have to look) we could maybe move forward like this as an additional alternative...
1. start putting in a message saying to upgrade, core to the system. Other platforms in Apereo are doing this (IE users getting a message to upgrade and saying they have an old browser)
2. explore Mobx 4 as part of our ES5-amd builds
3. Not drop it out but testing will effectively cease on it; it will be more so in remediation mode. If there's an issue, you notify us (since you ride behind us a bit / more heavily vet releases) and then we could explore what needs fixed to account for it
4. alter the feature detection methodology for ES5 and serve a hyper optimized bundle to everyone modern, 1 bundle that has everything to everything old

**Comment by btopro** [comment]
also just to clarify -- elmsln currently does NOT use Mobx but from our enjoyment of it with HAXcms and easy to understand it will more than likely make its way into the system through others app / element redesigns

**Comment by rickhumphries** [comment]
Yeh I think what you've outlined sounds like a sensible approach to this, and it's hopefully the last transition of its kind! We don't necessarily test IE11 too much either really other than brief browser walkthroughs and tend to find most issues through learners reporting it.

Since GDPR regulations came in, companies are much more aware of (and nervous about) data security so I'm optimistic they'll be more proactive in looking to upgrade from Windows 7 to Windows 10 before the end of support. I've drafted an email to all our clients today about this so I think the early communication will help too.

Although I'm not planning on always being as behind versions as we are currently, like you said, it'll still take us a few months to upgrade once v0.12 is released anyway so it feels like the overall timetable you've put forward would work.

**Comment by btopro** [comment]
another article in the direction of this -- https://www.pcworld.com/article/3393198/microsoft-edge-ie-mode.html

The current direction of IE 11 is that it'll be a tab / mode inside of Edge. Edge appears to be slated to ship the Chromium based version to Windows 7,8,10. This means Win7 would get it before end of life and that users stuck there would be able to get the new Chromium based Edge (which I've been testing locally and works great already).

So. I think we need to see HOW IE11 is integrated and go from there but it appears that increasingly in 6 months IE11 will effectively not exist and that ALL other browsers will be capable of delivering ES6 (uncompiled) code. The few browsers that don't support certain features of ES6 (Firefox as of a month ago, though current version is fine) get a custom build called ES6-AMD. This ensures it's fast and yet solves issues in those browsers.

@heyMP are I are pretty over ES5 (meaning anything older than 3 years old at this point) because it's impossible to do small team development and keep having to worry about ES5. IE11 and older safari/edge are the only things in this space and their traffic footprint are very small. We'll keep pushing on as we are, trying to get the build routine into ELMSLN for 0.11 that's using JS modules. This should technically support IE11 but I don't test it at all because we can't focus there. I'm relying on the build routine to actually do what it claims and if it works on (current) Edge then it SHOULD work there but again, time and resources :p.

Just wanted to give an update here of where this is progressing. the #2606 issue now has a branch I just pushed a ton of code into which is still work in progress but uses JS modules AND has many of the design of the top bar mirroring what Buttercups has pioneered (cause it's def better than what we had).

**Comment by btopro** [comment]
0.11.x works with polyfills. 0.12.x will have HAXcms which will have even less support for polyfill based browsers though we might be able to do something where content presents as it does today in ELMSLN but we try and push for HAXcms site builder tag to deliver the site prior to that.

Anyway, hashed out w/ the vision map and aggreed upon for support in 11 vs 12
