### ISSUE TITLE
Domain setup help

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2622]
I've replicated a server that ELMS:LN was set up on, created a new domain name and necessary sub-domains and pointed those to the IP address of the new server. 

I've also changed the domain names on the server's host file and following the instructions in the docs here - https://btopro.gitbooks.io/elmsln-documentation/content/developer-guide/general-questions.html under 'We're moving hosting from where we started building, what urls need updated'

Unfortunately it doesn't seem to work and I'm wondering if there are any other steps we need to follow?

**Comment by btopro** [comment]
what's not working? Because of when your system was stamped out (mine too which I fixed manually at one point), the URL might be directly written into things like `/elmsln/config/stacks/courses/sites/courses/YOURPART/COURSE/settings.php` and the other settings.php's that are floating around.

This might also help -- https://github.com/elmsln/_elmsln_env_config

specifically things like https://github.com/elmsln/_elmsln_env_config/blob/master/shared_settings.php

**Comment by rickhumphries** [comment]
When going to online.newdomain.co.uk, I'm getting `Not Found: The requested URL / was not found on this server.`

It would be good to manually fix our settings.php too. I've spun up a new version of ELMSLN on a fresh server to check what settings are applied there but it's forcing me onto https so kind of stuck with that at the moment. Will create a new issue for it

**Comment by btopro** [comment]
closing out due to age and other install related issues consolidating on #2626
