### ISSUE TITLE
What are the plans to upgrade to Drupal 8?

### ISSUE THREAD

**Issue by mgifford** [elmsln/elmsln#2639]
Drupal 7 is approaching it's EOL.  We should start preparing for D8, right?

**Comment by michael-collins** [comment]
By my calculations (okay, Google's calculations), there are 831 days from now (7/26/2019) until D7 EOL on November 1st, 2021. Wonder how long until D8's EOL? D9 is supposedly coming out in June 2020, perhaps it's worth thinking about D9 rather than D8?

**Comment by btopro** [comment]
There are no plans to upgrade to Drupal 8. We'll slide into LTS at some point and ride that until we can either move to Drupal 9, switch to Backdrop or this isn't a discussion point because we've left the island. The current plan / momentum is around decoupling Drupal 7 to minimize the impacts of Drupal in order to make any of the above directions easier. In the last year we've dropped like 50+ modules from elmsln and will keep doing so to make migration easier later on.

**Comment by mgifford** [comment]
Good to know..  For a big distribution like this it makes sense.
