### ISSUE TITLE
Discuss forum - removing section field when creating a new thread

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2640]
I'm trying to patch together the Harmony Discuss forum for a couple of courses we're running on ELMS version 0.8.x

One thing that I can't figure out is how to remove the field to select a section when creating a new thread:

![image](https://user-images.githubusercontent.com/4973810/61952046-b22b6400-afaa-11e9-85fd-52958b6038e9.png)

I managed to remove it from the actual forum post form by going here `/admin/harmony/structure/post/fields/og_group_ref` and then choosing 'Hide Field'

![image](https://user-images.githubusercontent.com/4973810/61952114-e9017a00-afaa-11e9-8fae-83b1ff1d8ff4.png)

However I can't see a similar field on the thread options here `/admin/harmony/structure/thread/harmony_thread/fields`

I know the discuss system is pretty much depreciated but we just need a couple of short term forums up and running fairly quickly so we're going with it!

Thanks

**Comment by btopro** [comment]
hmm... so my guess it it's in the features for it some place that they have to have that control on them. Because of how Harmony works it's basically a complex entity to entity relationship (as opposed to the normal forum module which is like comment + comment == thread and poor ux + poor permissions).

So if everyone is the master section or if they are all the same section or whatever the case, you could probably just hide it with CSS as itll default to the right thing. We did this awhile back with the studio to get around this UX issue yet still needing the permissions relationship there

**Comment by btopro** [comment]
this also brings to mind that if this is a bandaid, the forum module from core might help. You could just turn it on directly in the courses in question and then add a link into the UI for it. Probably way less complicated though I'm guessing it would need themed

**Comment by rickhumphries** [comment]
I did try switching on the Drupal core forum but seemed a bit naff - much preferred using harmony in it's current state.

Yeh not a bad shout on the CSS front. I'll take a look at that

**Comment by rickhumphries** [comment]
OK I'll close this out since I've just hidden things with CSS. I also think disabling the 'Discuss Section Threads' feature is what I'd probably need to do here but kind of don't want to mess with too many settings at the moment if I don't need to just in case.

![image](https://user-images.githubusercontent.com/4973810/62067042-b1086a00-b22a-11e9-9891-52c41c177286.png)
