### ISSUE TITLE
Installing for the first time

### ISSUE THREAD

**Issue by ugintl** [elmsln/elmsln#2690]
I downloaded it from https://github.com/elmsln/elmsln/archive/1.0.4.zip. Now should I install it like any other distribution?

**Comment by btopro** [comment]
elmsln is not a drupal distribution but a server level deployment for application that happens to be built on drupal. It has many install profiles within it but it's not a traditional distribution. Here is our install generator though it's been some time since I leveraged it - https://www.elmsln.org/install-guide

**Comment by ugintl** [comment]
So it is a backend server serving the drupal site. Correct? How to use it? Is there any drupal built site using it?

I just want to understand how I can use it on drupal.

**Comment by btopro** [comment]
it is multiple Drupal sites working together in a network configuration. Each site has a dedicated purpose. Might be easier to field questions around "using it on Drupal" in our slack channel to field what your use-cases are - https://bit.ly/haxslack
