### ISSUE TITLE
Content outline and book outline options both show on Welcome/Help/Syllabus pages - mobile

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#278]
Just noticed this:

![image](https://cloud.githubusercontent.com/assets/4973810/10343100/19c04848-6d14-11e5-912f-4f29e4e878d5.png)

It only happens for the Welcome/Help/Syllabus pages but don't think the book outline table of contents option should be there.

![image](https://cloud.githubusercontent.com/assets/4973810/10343131/49df730a-6d14-11e5-8dde-8982871a8719.png)

Btw, I know there's been talk of dumping the course outline option for mobile (there's probably a good reason!) but I actually think it works really well :) :+1:

**Comment by btopro** [comment]
@rickhumphries so we're working on this in a sprint branch currently since it's a major overhaul. Basically we got feedback from many people that once you start using multiple systems the offcanvas is cumbersome. If I had to use CIS or Media a bunch, I want those options readily available, not constantly opening stuff to flip around.

Also on MOOC it's a silent killer of DOM load speed bc of how intense the structure of it was. We've got some work to do still on making the Map more mobile friendly but think it's the easier of way go. The breadcumbs also go away on mobile in our current iterations so that it's just the map icon.

Going to close this out since it's been rectified in the builds we're working on which will get merged back into master once we clean up the UI over the course of this month (high priority atm)
