### ISSUE TITLE
Magellan sticky nav on mobile

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#287]
I love the magellan sticky nav, but wondered if a 'show/hide' option is required for it when stuck to the top - particularly as a solution for pages with quite a few headings when viewed on mobile, where the sticky nav takes up quite a lot of screen space:

![image](https://cloud.githubusercontent.com/assets/4973810/10529463/16cf3d46-7396-11e5-8d97-796e6b0f403d.png)

There's also a gap above it where the breadcrumb/book icon would be on desktop

**Comment by btopro** [comment]
Maybe on mobile it should only show the current heading at the top as you scroll down and have a quick back to top button or something. @michael-collins thoughts? it's definitely goofy

**Comment by btopro** [comment]
also @rickhumphries at some point I'd like to see what additional in-page templates you've added, might be some simple ones we could roll into the main package / provide inspiration for layouts as we build out HAX

**Comment by michael-collins** [comment]
It should either be put in an off canvas menu or taken away. Not a lot of horizontal space on mobile devices to account for long auto-generated links. This is something that was never really finished. @btopro I recall that I came back from some trip, and you have implemented this auto-generating system, but I never wrote any CSS  or tested it on mobile. In the past, this is the point where we typically remove our cool sticky-whatever ideas when they become too burdensome to design. @heyMP We should add this to the todo list. Where is that exactly?

**Comment by btopro** [comment]
That sounds about right. [sic] @michael-collins went on one of his many non-work-laden vacations, while I sat in a coffee shop ignoring my family on our vacation to build something awesome that looks crappy on mobile. ;)

The more we un-off-canvas our ecosystem the happier I get unless you were just pulling up the localized items in this nav. Our mobile mode is still between solutions as we need to pick either off canvas for mobile or go w/ the map / something like it (this has my vote). I could see it being nice to just have the heading be visible as to what section you currently are on since it's a tool for long vertical, in page nav styles.

**Comment by rickhumphries** [comment]
Yeh I think just having something to indicate the section you're viewing would work. @btopro how's best to send you the templates? I could just export them and send as .txt. files? I style them using CSS Injector so will send CSS file too. Also realise I've got a blog post to write... :+1:

**Comment by btopro** [comment]
Open a new issue about the templates thing. @heymp and mark can share how we  got some more added recently. Flat html and CSS are better then nothing though :)

Wp8
________________________________
