### ISSUE TITLE
Is ELMS a Student Information System as well as E-Learning system

### ISSUE THREAD

**Issue by meatballcoder** [elmsln/elmsln#292]
Does ELMS have a Student Information System?

**Comment by michael-collins** [comment]
@meatballcoder SIS is on the roadmap for another, larger-scale project. ELMS-LN won't do admissions, course scheduling, financial aid, school wide-data tracking, etc. That's well beyond the scope of an online learning platform. For now.

**Comment by meatballcoder** [comment]
Is that project online in Github yet?

**Comment by michael-collins** [comment]
Yeah, @btopro is it online yet? @meatballcoder I think there is a git repo waiting for contributions: https://github.com/elmsln/online-university

**Comment by btopro** [comment]
Currently we're assuming data comes in to power this thing in the form student enrollment data. Our people distribution in the roadmap could potentially provide light weight SIS stuff but as everyone views SIS differently I'll say no not at this time. Online university has a goal of being a college / university in a box but it's a longer term effort. Currently it stands up the publicize distribution and ELMSLN, and then mashes their back-ends together so that they can share connection credentials.

There's basically nothing there but what you get are something like this:
http://openulmus.org/ -- Publicize distro
http://online.openulmus.org/ -- CIS, the rest of the network is there and setup but I don't want to mention all the links as it deploys 11 distros currently OOTB

**Comment by btopro** [comment]
people distro is about as close to SIS as we'll ever get since it's the central person registry.
