### ISSUE TITLE
Standards/Competencies Tracking

### ISSUE THREAD

**Issue by kfurst** [elmsln/elmsln#293]
In the K12 environment, we're heavily vested into tracking national/state/local standards & benchmarks. Essentially, this means at least at the course level (but also likely at the unit and/or lesson level) established objectives/skills/competencies need to be tracked. 

From a teacher point of view, this would mean the ability to have access to a slide out or dropdown menu with the established standards/benchmarks for the course and then select them (via selection/ticks/radios) for the course/unit/lesson. Students and/or teachers could then select whether said objectives/standards were met. 

From a student or school principal point of view, the data of standards met across variety of courses would be aggregated and viewable by USER. One final component would be comparing the actual vs. goal (i.e. compare standards met with a a master list of standards (we have this)) to discover "holes" where students have not yet demonstrated mastery. 

One of the UC campuses did something like this with their school of pharmacy program. Mapped competencies that must be met in order to garner licensing be the board. See www.iliosproject.org

** I realize using an LRS to record H5P outcomes and then deliver badges is a more modern, personalized, and engaging approach but unfortunately much of this is dictated by state and national education departments.

**Comment by btopro** [comment]
So to your ** at the end. If the badge was "you took course 101" and then competencies / benchmarks / core standards of states tagged the courses in CIS. You could have the data necessary to say "Student ABC Started requirement 1,5 and 6, has completed 2,3 and is missing 4".  This would meet the requirement and set in motion the framework of breaking down these illogically simple standards of "you took math" into "you got the algebra badge!", with the singular "you completed 101" being all the state / principle needs but the "how many badges is my student collecting" be there for the student / teacher.

**Comment by rickhumphries** [comment]
@kfurst I'll get back to you with a screen cast showing the other stuff we've done which might interest you soon. Just on holiday/vacation at the moment. But essentially we've created 'course modules' and 'course competencies' as content types in the CIS and then link which 'course modules' make up a course and which competencies make up a module. We've then got a 'view your progress' area where the student can see which they've completed from the dashboard.

It's something we needed to do in order to form a link back to our other CRM system (where we do all our enrolments etc.).

**Comment by btopro** [comment]
ya I'd like to see an update on that as well :) with where things are headed it sounds like the first part might make sense in CIS and the 'view your progress' would be in people (hypothetically)

**Comment by rickhumphries** [comment]
@kfurst @btopro as promised... https://youtu.be/q224P-PPhD0

**Comment by kfurst** [comment]
Just watched the tut Rick. Really, thanks for taking the time. I'm going to try installing Learning Locker to try to replicate a very, very basic level of what you've got going on in the video. Thanks again.

**Comment by btopro** [comment]
@kfurst here's some learning locker install stuff I used to get our instance up and running (currently just collecting data at the moment) -- https://gist.github.com/davidpesce/7d6e1b81594ecbc72311

It would be an amazing contribution to both elmsln and LL if there was a "1-liner" / copy and paste style script to install the thing. I started working on one and it's not perfect by any means but is a step in the right direction -- https://gist.github.com/btopro/fc7792788c91f4c14bf0

**Comment by kfurst** [comment]
I'm having a heck of a time on this LL install. I tried installing Learning Locker yesterday on another deb-based dev server just using LL's instructions with no success. Today I tried installing it on my ELMS vagrant VM with those instructions you linked above. First, I got a no xz compression error when I got to the installing the required PHP versions. Uninstalled the wrong epel release (http://serverfault.com/questions/675802/xz-compression-not-available-yum-error-on-centos) and installed the correct one. 

Then I go back to the php stop and try again. It connects and downloads but in processing the dependencies it breaks and gives lot of: 
Error: Package: php-5.6.15-1.el7.remi.x86_64 (remi-php56)
           Requires: libc.so.6(GLIBC_2.15)(64bit)
So I check that out and it looks like I'm missing some of the needed libraries. Ok fine I found a couple of sites online with libraries, except some are there and some aren't. Sigh. 

After reading about this issue... this doesn't have anything to do with the version of CentOS I'm using on that VM does it?  Is the main repo clone that I'm using for a vagrant install the same version you're using on your production and dev servers? I'm installing a clean version of ELMS to try and see if I have anymore luck.

**Comment by btopro** [comment]
you'll need to leave out large parts of the installer if installing this into the same VM as elmsln; you can do some fancy networking and have the two as separate VMs that talk to each other but I have no experience with this yet ( @bradallenfisher might).

I agree it's a difficult application to install which is why I started trying to boil it down into a one-liner kind of a thing but it's tricky. It uses MongoDB which took me some hunting to figure out the syntax of that language for creating user accounts and a DB. LL certainly was possible to get up and going but was pretty difficult.

Don't know if this still works but might be a good route to at least play with it in a vaccume (I did that prior to getting it up and going for our prod instance, though I run it on its own server bc of its complexity) -- https://github.com/rael9/learninglocker-vagrant

**Comment by kfurst** [comment]
Tried the vagrant option. Installation immediately fails due to a 'NoSshKeyException' 

Guess I'm just going to wait this one out awhile until we find something a little easier. 

Thanks for your help.

**Comment by btopro** [comment]
can also mess w/ LL directly if your just looking to play w/ it via their demo -- http://demo.learninglocker.net/

But yes, an automated install routine would be clutch for this though It would almost definitely have to be on a different server. It could theoretically run in the same place, especially in a vagrant context during install just for a sense of having a whole network and testing.
