### ISSUE TITLE
Figure Label design component

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#308]
@cmd30 has a great idea for adding textbook like captions to media elements.  I'm not sure what they would be called.  In images we already have fields for 'caption' and 'citation'.  Does anyone know what the techical name for these labels that are shown next to images in textbooks?

I'm thinking something like 'Reference Label'?

![chem005-testgraphics-1](https://cloud.githubusercontent.com/assets/3428964/10828354/351e0994-7e4a-11e5-90d3-8d13bea8d543.jpg)

- [x] Add Design Component
- [ ] Add field to media system

**Comment by heyMP** [comment]
Here is an HTML prototype of the component.

http://codepen.io/cmd30/pen/BoVNYa?editors=110

**Comment by btopro** [comment]
@heyMP @cmd30 are you thinking like this is something an ID would add to something or that this is the way we'd render the "autofootnoting" capabilities of the system currently.

Right now any media that appears can be auto-footnoted so that it has a 1. or whatever next to the image / video and then clicking it builds a link / jumps to the footnotes at the botom.

This could provide a cool alternative to that; or were you thinking a design element that someone could add a "caption" / "figure".

Love the idea either way, just asking :)

**Comment by heyMP** [comment]
I actually think it could be for both.  In our case, we just thinking of correlating it to the references in that appear in the textbook, so I was going to add a group of fields for each media content type called `field_footnote_label` and `field_footnote_label` or something like that.

But we could also render the "autofootnotes" through that

**Comment by btopro** [comment]
ok, so maybe we're talking about two different but related things. the WYSIWYG supports [fn] tags so you can turn any random part of the page into a reference footnote that plays nice with the auto generated ones from the remixables. Maybe we could incorporate the [fn] tags into the figure your talking about so that it would render as the fancy one your designing but then if you click it, jump down the page to list all of them w/ extended notes on copyright / description.

**Comment by michael-collins** [comment]
MLA standards: https://owl.english.purdue.edu/owl/resource/747/14/

**Comment by michael-collins** [comment]
@heyMP That label isn't really a reference. I'm thinking that the reference would be written in the text, "referring" to **Figure 7** or the facts about territory (See Table 1: Charting Territory).

Perhaps Figure Label or Title, Table Label or Title is more appropriate?

**Comment by btopro** [comment]
Possibly explore entity reference inline form so you could be attaching figures to media. As an alternative proposal, this could be a simple "element" that lives in the content system itself as we've talked about a few others like bulleted lists and quotes potentially living in the same bucket as its rendered
