### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#367]
Add some sort of notification (email or identification when logged in) that someone commented on their image in the studio.

**Comment by btopro** [comment]
Eventually this will be in inbox but as studio is driving a lot of these use-cases we'll start there more specifically w/ comments; should be really easy to just do that there for now

**Comment by michael-collins** [comment]
The idea is that inbox will aggregate all of the things that you need to pay attention to as a student. When things in inbox requires a student's attention, there will be an email sent out. Given that there could be a ton of these things, we'll only send an email once or twice a day, similar to Twitter or Slack. Otherwise, students will turn off the notifications all together. Lore.com once spammed my students with 60 emails because I was adding things to a course. They were not happy.

**Comment by btopro** [comment]
https://www.drupal.org/project/subscriptions - robust
https://www.drupal.org/project/comment_notify - get the job done

**Comment by btopro** [comment]
comment_notify drop dead simple but will need a real server to test it on since it has to send emails and I need to look at the frequency cause of what @michael-collins mentioned

**Comment by btopro** [comment]
comment_notify in CLE core til we eventually get inline notifications via inbox
