### ISSUE TITLE
Clean up current edit form

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#378]
Need a mock up of dealing with what will be the "advanced" edit mode. I really like the UI here on github w/ the less important things being smaller options on a right column but leaving this one up to you. Anything to break up the hideous wallet of... this thing below. Also the default save button in Zurb is not an action color for whatever reason. I'm thinking Red or Green, but anything :p other then what it is now!

![2015-12-08_00-18-29](https://cloud.githubusercontent.com/assets/329735/11648340/667f2e6c-9d41-11e5-8a42-9c87c2d49596.png)

**Comment by btopro** [comment]
Thought; on wide-screen where there's available area, what if we took these items on the bottom and (while presenting them better to begin with) shifted them to hang off the right-hand side. Like the styling of github (simple, headers w/ options in them) but the collapsibility of the wordpress.com advanced options (example screenshot)

![2015-12-09_08-54-01](https://cloud.githubusercontent.com/assets/329735/11687046/8860414e-9e52-11e5-9130-b8623cb9fbef.png)

**Comment by btopro** [comment]
#639

**Comment by btopro** [comment]
shifted to Htab, simple but effective. Also made buttons stick to bottom so you can always get to them quickly for saving when done

![2016-02-24_23-26-18](https://cloud.githubusercontent.com/assets/329735/13309819/07458cd4-db4e-11e5-98a6-9c8813e71480.png)

**Comment by michael-collins** [comment]
@btopro Careful with sticky. This usually sucks for mobile and we don't do it anywhere else.

**Comment by michael-collins** [comment]
I can make a mockup, but I don't really know what the intended functionality is here. We should discuss.

**Comment by btopro** [comment]
you haven't used the system in awhile then if you believe we don't do this anywhere....

**Comment by btopro** [comment]
intended functionality: make a container for extras. it's a staff facing form that I'm trying to make suck less

**Comment by michael-collins** [comment]
@btopro What exactly are extras? Should they be worked into other parts of the interface instead of having their own place?

We may want to think about moving those buttons into the top bar, as to replace the edit button with a save button. I've done some mockups in the past to show how we could communicate that effectively. Here is one of the media system I did last May. Not a perfect 1-to-1, but shows how we can change the color of the operations to be pertinent to the job at hand. Do we really don't really need to see the navigation if we want users to concentrate on doing a save or a discard changes operation? I'm suspecting not, but perhaps there's a case to be made. This would make the interface a lot more clear and minimize clutter for beginner users of the system, which is not something we've been good at thus far.

What I just described is how material does UX, which aligns with the new design pattern we are adopting.

![screen shot 2015-05-20 at 8 29 54 pm](https://cloud.githubusercontent.com/assets/1085304/13331167/47ed5740-dbca-11e5-972c-6598927cebe3.png)

**Comment by btopro** [comment]
Save button now replaces edit while editing (and triggers the save button). Screen below of tab group bandaid solution til #669 comes through

![2016-02-29_21-54-47](https://cloud.githubusercontent.com/assets/329735/13416225/1149cd0a-df2f-11e5-80ea-0ddf3d237a72.png)

**Comment by btopro** [comment]
Material CSS styles ripped out of adminimal theme... damn!

![2016-03-01_01-16-56](https://cloud.githubusercontent.com/assets/329735/13419355/4e696cec-df4b-11e5-8ac1-87e2e22b1a4d.png)

![2016-03-01_01-18-05](https://cloud.githubusercontent.com/assets/329735/13419375/7674bee4-df4b-11e5-9d85-9aee0b151ff9.png)

![2016-03-01_01-17-21](https://cloud.githubusercontent.com/assets/329735/13419376/79c7fce6-df4b-11e5-8111-eb4b52c2a06e.png)

**Comment by btopro** [comment]
@heyMP check out the i378 branch for these things applied; work across all systems pretty nicely. Basically just refactored the stuff from adminimal_theme that was being applied to that theme and then cleaned it up a bit to fit our look and feel, then applied to all our menus with styles that were reasonable. Forms already look loads better though obviously have room for improvement. It's a decent baby step towards seeing some of the materialize stuff in action prior to a full on refactor like will (probably) be needed

**Comment by btopro** [comment]
Closing for now. This is as far as it'll get til we redo in angular / actual materializecss implementation
