### ISSUE TITLE
Issue Importing Book Outline (XML)

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#451]
Hi. I'm getting the following warning messages when I try importing:

![image](https://cloud.githubusercontent.com/assets/4973810/12198387/69281f6e-b607-11e5-95a7-8102fb3a8081.png)

Is this something you've seen before?

**Comment by btopro** [comment]
ahhh I had this happen recently but not with elmsln, w/ drupal in general. This is because private file path isn't set and the upload for import wants to go there.

go to path `admin/config/media/file-system`

and set the private path to something like `/var/www/elmsln/config/private_files/courses/arth111`

**Comment by rickhumphries** [comment]
Perfect! That did it :) Nice one

**Comment by btopro** [comment]
nice; patch resolves this going forward
