### ISSUE TITLE
Course Outline Button not Accessible in Profile Edit Tab

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#467]
I am taking ASTRO 130 this semester at Penn State - and I noticed that when you click to edit your profile - none of the buttons accross the top (accessibility, outline, and settings) will activate upon click. This isn't critical by any means but makes navigation a bit confusing.
![edittab](https://cloud.githubusercontent.com/assets/7243665/12299574/387b624a-b9e5-11e5-9752-bf735d7a5e70.png)

**Comment by btopro** [comment]
This is related to the fact that LMSLESS (the bar across the top) is told not to load on admin pages. Foundation Access / Zurb Foundation is not currently our admin interface (for various reasons).  You can see the code that causes this issue here:
```
/**
 * Implements hook_page_build().
 */
function cis_lmsless_page_build(&$page) {
  // make sure they have access to view this
  if (user_access('view lmsless bar') && !path_is_admin(current_path())) {
    $page['page_top']['cis_lmsless'] = array(
      '#weight' => -10,
      '#markup' => _cis_lmsless_assemble(),
    );
  }
}
```

Now, if this IS NOT an admin path, it'll render the bar, and associated JS and all is good. The problem is that (for whatever reason) drupal core considers user/*/* to be an admin path. This from core:
```
/**
 * Implements hook_admin_paths().
 */
function user_admin_paths() {
  $paths = array(
    'user/*/cancel' => TRUE,
    'user/*/edit' => TRUE,
    'user/*/edit/*' => TRUE,
  );
  return $paths;
}
```

I agree that canceling an account is an admin task but modifying a profile definitely isn't. The way to fix this is for cis_lmsless to define admin paths be changed via an alter hook (hook_admin_paths_alter) which you can read about usage here -- https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_admin_paths_alter/7

I think this is enough evidence for you to craft a solution / PR to fix your educational experience. go for it!

**Comment by btopro** [comment]
I want mark to fix this for a multitude of reasons; @mmilutinovic1313 consider this your highest priority but it's not a blocking issue for us to jump up a version

**Comment by mmilutinovic1313** [comment]
Working on this now - I'm looking for the path of the file of which you posted code snippets. Are those under ulmus or cis?

**Comment by btopro** [comment]
Elmsln contrib -> CIS connector

**Comment by mmilutinovic1313** [comment]
Thanks

**Comment by mmilutinovic1313** [comment]
Update: I confirmed with @heyMP what @btopro also concluded, that something is changing the JQuery version on these edit pages. I'm working with @heyMP to look into this more.

**Comment by btopro** [comment]
@mmilutinovic1313 are you sure that the jquery version is busted? Where are you / role when this happens? I just tried to do it locally after ur patch and it worked so not sure

**Comment by mmilutinovic1313** [comment]
@btopro I will double check this, but both @heyMP and I ran into the issue when even after the patch went through. I can show you sometime via appear.in

**Comment by mmilutinovic1313** [comment]
@btopro hmmm....just kidding actually! It appears that it is now working in both my vagrant and on the actual course site I'm taking. This issue can be closed then

**Comment by btopro** [comment]
Congrats you are the first student to ever fix their lms while taking a course offers via it :)

**Comment by mmilutinovic1313** [comment]
Documenting this relates to issues #621 & #552 for presentation tomorrow
