### ISSUE TITLE
On updating, instructional significance icons missing in ToC [Courses]

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#476]
We've just updated to the latest version (yeeeeh). Only thing I've noticed is that the instructional significance icon is missing from the ToC's. It shows up again when I go to edit the page and save it...but just means you'd have to go through every page individually to kick it in:

![image](https://cloud.githubusercontent.com/assets/4973810/12326112/a63372c8-bac6-11e5-8c0c-98f7ae8fa04b.png)

**Comment by btopro** [comment]
related #200 #197 

Better question; do you want those to show in the first place / is it actually useful? I think @michael-collins may need some more differentiated icons in order for it to be more useful. From playing with it in one of our courses (for example) the assignment / submission icon aint that different from the page icon currently. It's also a big useless to have page icons all over the damn place so might be better served w/ a blank space for those but then key things noted (like assignments or end of lessons) might be worth noting

Also, awesome on upgrading and no one telling me about issues (yet) :)

**Comment by michael-collins** [comment]
I think icons are really useful for indicating when items are different. I can see that it would make sense for some courses to need to use the ToC with icons. This gets back to a system flexibility question. Can we make icons a configurable option? That is the best of both worlds.

**Comment by rickhumphries** [comment]
Agree with @michael-collins. I do find them useful to indicate the pages that relate to needing to visit our other Test System to comple an assessment. It's good to differentiate them just so students don't accidentally miss this. 

I'm sure they'll become even more useful as more functionality is added, allowing authors to differentiate pages more easily

**Comment by btopro** [comment]
they just need to actually be different :) a little too subtle right now (and we just need a whole bunch more). We're hoping to get some students involved in the design process and iconography would be a great area to represent things like this

**Comment by btopro** [comment]
see #672 if you care to know why this was happening. @rickhumphries now that things are pegged to node save you should be able to do bulk updates via drupal methods though we might want to explore some forms of bulk operations. Another way to trick it into happening would be to use the bulk search and replace VBO (in as of 0.6.0 I believe) so that you could replace some word with itself. this will skim off every node and resave it which should trigger icon inclusion. Resolving #197 means that if "none" is selected as to the significance of a node then it won't have an icon (so we can have it both ways).

**Comment by rickhumphries** [comment]
Brill, thanks @btopro
