### ISSUE TITLE
Support for Flyouts / off-screen / related concepts

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#480]
In the transition to ELMSLN we abandoned this off-canvas concept seen in this video https://www.youtube.com/watch?v=oib5lzMtG0k It's a right side fly out that's triggered to open based on interactions with the page. While it looks hideous, let's overlook this and consider use-cases where it could be extremely useful:
- Having related content pulled in from wikipedia / other sources that while not 100% required reading, may add additional context to content
- Pulling a twitter stream / other social media stream in that's updated to reflect current trending topics, especially for teaching controversial topics
- Having discussions that are piped in either from some place like Yammer or the Discuss system in ELMSLN so that we can have related conversations around the material without totally bloating up the normal UI to experience it
- placing media and complex interact objects off canvas, trigging their display / open 
- Providing a "more examples" area
- Providing "keep in mind" / "resource" areas that might be related to the material but not immediately needed at all times (like a series of PDF files that help with an assignment for example without throwing them in the garbage bin of "resources").
- Providing a "feedback" area for students to leave feedback about the material / submit an issue in context (we have past videos showing prototypes of this)
- Providing a chat area for communication with other people currently online
- Providing a way of quickly contacting helpdesk

**Comment by btopro** [comment]
@heyMP @michael-collins thoughts on above of if something like this could be useful to bring back in in some capacity --^

**Comment by michael-collins** [comment]
@heyMP @btopro I think all of those things are important and/or interesting functionality. With that said, adding all of them to a fly-out would be a step backwards in my opinion. This reminds me of the "just throw it in a modal" solution that was getting us into some trouble with the interface. We can accommodate all of this stuff with a well planned layout, thoughtfully placed menus, icons that trigger text-inputs, and other more elegant techniques. Some online learning interfaces that I've seen have really good UI/UX patterns to solve some of this stuff.

Because of the vertical nature of the menu, it will be more difficult to design. I think before we make a decision here, we should get a mockup together to see the impact it'll have on the interface. Let's wireframe some these interactions and evaluate how to best integrate them.

**Comment by btopro** [comment]
please stop being so visual

**Comment by btopro** [comment]
exist now via #669
