### ISSUE TITLE
Course/MOOC - creating custom pages for top menus

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#481]
The Syllabus menu doesn't make much sense for us in a lot of courses, and I've been wanting to add information here that is (a) specific to the course, rather than generic to all courses, and (b) I don't have to upload a PDF for.

How I've been getting around this is to create a custom page - add all info to this, then change the link reference for the syllabus menu in course settings here:

![image](https://cloud.githubusercontent.com/assets/4973810/12349147/4e8e07a0-bb65-11e5-86ef-53ed8731f29c.png)

However, since updating to 0.0.5 this notice displays on a custom page:

![image](https://cloud.githubusercontent.com/assets/4973810/12349136/3a4bb6fc-bb65-11e5-8179-f74a40d62e44.png)

**Comment by btopro** [comment]
good to know, this is because you created a page that's just hanging out there not associated to a book. This obviously shouldn't do this but to correct it in the short term make a book called like "other pages" or something and put it there. Many times we'll also just make a page in the outline called syllabus (when people don't want to use the PDF option) and reference it with this button it should go away.

**Comment by rickhumphries** [comment]
Ah yeh I see. Good tip. I'll do that for now. Thanks

**Comment by btopro** [comment]
this will ensure it's in a book, if its not then it won't throw a notice anymore
