### ISSUE TITLE
Editing course names after creation?

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#501]
I should have known not to do this but I did it anyway and used an apostrophe: 
![screen shot 2016-01-22 at 1 00 39 pm](https://cloud.githubusercontent.com/assets/15616523/12519221/8d2738f0-c10b-11e5-96e0-2b4f556abef3.png)

So is there a way to edit the course name after it's been created? While I don't anticipate many people trying to use apostrophes, I do foresee course name changes and/or misspellings that aren't caught till it's "too late."

**Comment by btopro** [comment]
click that arrow / name, hit settings. can change it there but that "settings" currently isn't pervasive across the other tools in the network

**Comment by btopro** [comment]
right now once you make a course named "whatever" and systems in that network you no longer can change the name (easily). Also deleting these spaces isnt possible without a backend command. This has historically been intentional; as we get things refined though we'll need to support course space renaming both on the front-end (like this issue is pointing to) and behind the scenes.

**Comment by btopro** [comment]
- [ ] Use elmsln.php API to make something to issue low level vsets
- [ ] allow it to issue non-blocking calls via usaged of httprl if available (add to request wrapper)
- [ ] vset site-name / title (not front-page) in the other services of a network
- [ ] update in CIS
- [ ] group settings differently on this page to know what's the same everywhere

This doesn't account for renaming the actual machine name in use but is a start

**Comment by btopro** [comment]
branching the other two issues off into their own thing as they are different API calls
