### ISSUE TITLE
Innovate tool coming back with Access Denied

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#518]
Got an access denied error when trying to go to the Innovate service.

**Comment by btopro** [comment]
- [ ] Change name of Innovate out of the box to be "A new Idea"
- [ ] Make innovate grant the person requesting it the admin role
- [ ] document the purpose of the innovate tool, maybe hide it on the UI except for admins

**Comment by michael-collins** [comment]
@btopro What is this?

**Comment by btopro** [comment]
Innovate is an early form of #26 it's the boilerplate distribution that all the other distributions ride on. When you spin it up you're getting:
- Foundation access / LMSless / Our user experience
- All the modules required to make sense in the context of elmsln
- connectivity to CIS / section management
- that's it

It's a blank slate meta distro so that you can build new applications on top of it. Idea then being faculty XYZ has all these requirements that don't fit neatly into studio, courses, etc. So we make a new bucket for that functionality using innovate to rapid prototype directly in the system. This could be use to have a conversation around what this new thing is while building a fully functional prototype. After 1 good sprint you could be left with a few helper modules you need to write and some design work and you're done, but the ideation has been taken care of for you.

**Comment by btopro** [comment]
An obvious next step is once the underpinnings of #26 exist you'd be able to click a button that's sorta like "profiler builder" where you put in a name but instead of downloading it makes a repo, exports config to it and runs the commands necessary to add a new application to elmsln's network of tools, then PRs the repo to get travis to kick in... and... yeah

**Comment by michael-collins** [comment]
@btopro Oh look, we are 4 years ahead of schedule on this tool ;)
