### ISSUE TITLE
Discuss distro development ideas

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#55]
A possible development direction would be to build some form of discussion area within the content page itself so that there's solid context for discussion. 

There are typically two types of discussions that take place on a course. The first is within and part of a page in the course outline, when the conversation is on a topic, and the second can just be general sharing of information - tools that are being recommended, study help or whatever. 

The discuss service itself could have two areas, 'My discussions' and 'General Discussions'. My discussions would pick up only the discussions hosted within the course-outline service that you've subscribed too, or contributed too and would display these threads here (or link back to them). General discussions would show the threads for more general forums. 

There's also the option of allowing annotations (www.drupal.org/project/annotator) within the course content and building discussions around that (or linking to an annotations within a discussion?) Annotations like this could be public or also allow students to just make private notes on the course content - which again could be streamed and collated into a 'My Notes' area.

**Comment by btopro** [comment]
from @mkwisc
Allow use of user pictures and whatever is defined as “display name” or “real name” within the course or system.
-Have notifications for specified individuals (i.e., course instructor if they choose to get notifications of all comments on an activity), and follow-up comment notifications to thread or replies to comment author (if they choose). There are different models of this already out there in some Drupal tools and other commenting systems that this could probably be modeled after. Reply to comment notifications might be a much further down the line feature—not necessary but people seem to often expect they can reply via email, so something to investigate. 
-Ability to tie a discussion to an activity or assignment within a unit or course so that progress can be tracked in some way, and discussions within a course unit can be displayed in different ways.
-Work well with multiple sections, if possible.
-Seems this would possibly take the place of a designated discussion forum, which is better suited for spontaneous discussions by faculty and students not directly tied to course activities like this discuss tool seems to be. That said, there are certainly situations when a discussion forum would still be useful and perhaps an additional tool available for a course space.

**Comment by btopro** [comment]
-- threaded discussion
-- try and encourage discussion on 3 separate things (distribution of critique / social feedback important)
-- 5 star / thumb up / ratings beyond just comment
-- commenting on parts of a submission (students largely don't use this sadly but its there)

Things we are currently building based on requirements from faculty
-- audio recording of comments (student to student and faculty to student)
-- ability to associate likert scale / emotion / other data point then just text
-- rich media
-- ability to highlight certain members (faculty doing this)

Things I'd like to see in a tool / think would provide greater flexibility
-- discuss in context (like Disqus)
-- aggregate to a stand alone system (sorta like Disqus data flows but not in their presentation)
-- two way street; I can start in Discussion and know its related to content in the course or start in the course and know what discussions are related to it
-- able to be modified from original; a make space approach (some like threading, some don't, some like comments, some don't, some want full on submission, some don't).
-- reference conversations from conversations
-- private, public, wait to view, different kinds of conversations based on a combination of settings.

**Comment by michael-collins** [comment]
Some additional features we need (might be a re-phrasing of what has been posted above):
-- Ability to restrict discussions to a student's assigned discussion group
-- If a student participated, that is linked to grading.

**Comment by btopro** [comment]
#37  is the future home for this thread

**Comment by rickhumphries** [comment]
Found another possible annotation tools which might be useful https://www.drupal.org/project/hypothesis

**Comment by btopro** [comment]
Very cool. it's a hosted solution though (or at least that integration claims to be with a hosted version). Still, very cool looking and worth some investigation on our part I'd think

**Comment by btopro** [comment]
would need some love, lol -- http://cgit.drupalcode.org/hypothesis/tree/hypothesis.module?h=7.x-1.x

**Comment by rickhumphries** [comment]
haha oh yeh :)

**Comment by btopro** [comment]
Maybe we should split the annotator discussion tool idea off to another thread. The discuss distro provides discussion forums via harmony and remixables allows participation in context. Obviously can flie a big smoother but the pieces are all there and working.

UX improvements to discuss and new functionality / types of conversations should be in new threads and reference this one.

**Comment by btopro** [comment]
once discuss gets higher priority down the line we can revisit; conversations closing in on a year old, there's a space for this; we'll go from there
