### ISSUE TITLE
Theme breaks if not course outline is present

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#634]
When creating a new course, if there is no content outline assigned to the master section Drupal will return only HTML with no assets.  This only happens on the homepage.

![screen shot 2016-02-15 at 4 00 07 pm](https://cloud.githubusercontent.com/assets/3428964/13060135/411dc8de-d3fd-11e5-92d4-d667e9695a21.png)

**Comment by heyMP** [comment]
This also only happens when the homepage is pointed to `mooc/book-toc` which is responsible for redirecting the user to the current sections homepage.

**Comment by btopro** [comment]
ahhh, so we need a fallback for when there's no outline set or is this an issue of there being no content?

**Comment by heyMP** [comment]
Fallback for when no outline is set.  People are constantly going to be deleting existing course outlines so we might as well just do the fallback.

**Comment by btopro** [comment]
Some additional UI suggestions / things noticed as a result of this issue:
- [ ] if there's no content in an outline (outline page only) the fly out nav doesn't work
- [ ] if there's nothing in a content outline, the home page should suggest that they add some (w/ a link to the outline designer to do so)
- [ ] replicate this in the flyout (once we make it work when its empty) so that they could shortcut link to add stuff there

These are more so use cases when building a site with no default content or accidentally deleting it all but still important pathways to account for.

**Comment by btopro** [comment]
Cleaned up, completely. so much easier to use. Also debugged several use cases where as you go from multiple books down to 0 that it could get po'ed and not know what to select, as well as fixed once you start adding books that it still knows what to do. Also added support for automatically selecting to create a new book outline if we detect none exist as well as fixing a case where you couldn't submit the settings page in mooc because there were no books with which to set a default
