### ISSUE TITLE
Image Attribution

### ISSUE THREAD

**Issue by rjf227** [elmsln/elmsln#639]
I need to be able to easily add an image attribution label in a page image.  I have uploaded the file, but seem to have to add the image attribution at the bottom of the page.
<img width="670" alt="screen shot 2016-02-16 at 10 25 36 pm" src="https://cloud.githubusercontent.com/assets/15616843/13099035/645cc43a-d4fc-11e5-8386-3098fe8bbc37.png">

**Comment by btopro** [comment]
Couple things here. That area is just for applying a banner to the content itself. Think of it as a unit/module mini-theme. There's two ways to get media into the system.

1.Click the image icon on the wysiwyg (less preferred) 
2.Open the network icon and hit Media Assets, upload it there, then copy the embed code where you want it to go.

This helps w/ long term sustainability of the unit placing the media there because it's quantified, it also opens the door to the different stylings we keep adding in for enhancing the way media is presented (like auto lightbox). It also provides fields for the attribution label. I know that @heyMP has also been working on a "figure" caption item that is delivered from the media system which he could speak to more then me.

You can close this out if this answers this question

**Comment by rjf227** [comment]
We use banners in our courses in the same way you intend here.  However, we are required to give attribution for the image source.  I actually do want to use the image as a banner, but I also want to cite the source.  
![screen shot 2016-02-17 at 10 05 00 am](https://cloud.githubusercontent.com/assets/15616843/13113667/f6c5197e-d55d-11e5-9c9f-1f13369fd6e8.png)

**Comment by rjf227** [comment]
Also, am I completely missing where the "media assets" are or do we not have that in our instance of eLMS?  This is what I see when I click on "Network":
![screen shot 2016-02-17 at 10 09 24 am](https://cloud.githubusercontent.com/assets/15616843/13113780/a4eba752-d55e-11e5-9c09-7e1f115c88a6.png)

**Comment by btopro** [comment]
Oooooo ok, sorry, misunderstood the request. You are correct then we do need some way of nicely citing this across the places it's usage is propegated.

As for the other thing that's a permission issue we've resolved in newer builds but I haven't pushed it to ur server yet; bandaid for now (refresh and it should be there)

**Comment by rjf227** [comment]
A whole new world has opened up - Thanks!!

**Comment by rjf227** [comment]
Also, for some reason the attribution isn't showing up in the page with the photo I uploaded to network <media with the added citation information:   
![screen shot 2016-02-17 at 10 47 39 am](https://cloud.githubusercontent.com/assets/15616843/13115330/4acd887e-d565-11e5-8b0b-ccf5f13c74e4.png)

**Comment by btopro** [comment]
Which embed method for the shortcode did you select? If you click the vertical ... in the media when on the item you should see an option to view the differents ways of rendering the media which have a variety of display types (which include citation in some)

**Comment by btopro** [comment]
I see part of the issue; We need to run upgrades on ur host to get the fixes we put in place related to this. try this one in the mean time to see what I'm talking about
```
[ciscode|rev=1|tool=elmsmedia|item=23|entity_type=node|render=display_mode|display_mode=image__boxed__lightboxed]
```

replacing image__boxed__lightboxed with `image__boxed` will drop the lightbox

**Comment by btopro** [comment]
works once we merge in i96
