### ISSUE TITLE
Micro credentials / Badges / Competency based education

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#648]
@rickhumphries I think I finally figured it out. I figured out what I don't like about the storage of the prototype data from forever ago and I figured out what I think might work (and I feel like an idiot for overthinking this whole time). The XPI statements and their storage in CIS (on ur sys) but constantly relating to things that happen in the course content. I'm not sure this needs to be centralized (the statement mapping).

merging with the idea in #640 . If we treated the course outline as actually a series of smaller items (lets say 40 instead of higher ed's 15ish) and then we had 2 content types:
- Unit / Lesson / Module / whatever
- Page (just like now) and pages and pages

XAPI statements of completion, etc = all pages finished in a module. Modules define their order just based on what order they are in the outline. So these statements and their mapping happen PER COURSE / outline / version of the course. THEN in CIS (or whatever #550 #629 we call the HUB for "how am I doing" as a student) we ask the courses (we know what they are enrolled in) for their progression and then the dashboard shows you how your doing / what you've earned. So the end result to the student is the same but the mappings all happen with the course outline itself; that way different faculty can teach differently.

**Comment by rickhumphries** [comment]
I think the idea of the CIS/Hub/Inbox or whatever querying the course for progress data would work.

I suppose my first concern is using the completion of a page as a way of credentialing. I think that may limit the flexibility of the system in a way, as it could intrinsically link together the way the content is laid out and how you want 'progress' to be perceived by the learner.

For instance if you want to show the 'official' course specification to the student and how they're progressing through that, but within the content you want to mix it up and have a lesson which achieves the 2 of the 5 learning outcomes from Unit 1 (of the official syllabus) and 4 of the 7 learning outcomes from Unit 4 of the official syllabus, I can only really think that you would achieve that by separating out the content from the course hierarchy components.

Not sure though - will have to keep reflecting on it 

I've also separated Badges from the official credentialling of our courses, purely because it allows us to also award badges for informal learning, or participation etc. So a learner might complete 3 learning activities (H5P at the moment) in a course. This doesn't give them any official course credit, but I want to award a badge for motivation purposes. I can still award a badge for official credit, but I just attach the same completion conditions to the badge as I do for the official credit.

**Comment by btopro** [comment]
Complete all pages was just 1 albeit weak example

**Comment by btopro** [comment]
for context, we have several ppl talking through learning pathways to which I will pose the argument that the "course" IS the learning pathway if done correctly. Content just happens to live there when it makes sense to, media and other experiences are hitched onto it to keep it in a flow (or free form as we're exploring as well)

**Comment by rickhumphries** [comment]
Just thinking about this again. I think the idea is sound to be fair. I guess we currently have our Course > Module > Competency setup as centralised CIS content types because these are originally set up in a different system (our main CRM) - so any changes made in our main CRM to a course component's status also need to be reflected to the student when they view their progress. 

I'm throwing bits of info out here, but some other things to potentially think about:
- Standardising how we communicate the Course Module/Unit/Lesson. This could be changed by an instructor as to how it's displayed to student's, but as a content type, perhaps 'course component' would work?
- Meta data for a course component. Currently I'm thinking:
-- Optional/Core: whether the course requires this component to be achieved or not
-- Active/Inactive: whether the component and content within is 'viewable' by the student. Depending on the learning pathway certain components can be made 'active' part way through the course - and should be student specific. Can be triggered by xAPI statements or date etc.
-- Weighting: If the completion of a component is linked to a '% course completed' type thing, then you would need to weight the component accordingly. Kind of like attributing a 'x number of learning hours for this component'. 
- Are we going to display grading information in the Course system? I imagine that the taking of assessments would happen in 'assess' and trigger completion of some components. If xAPI-enabled, would this feed from Assess > Learning Locker > Courses > Hub/Inbox?

**Comment by btopro** [comment]
like the content type idea; may need to let #640 play out as a prototype and then step back and review from there. I think branching path courses plug in nicely w/ some of the concepts you've hashed out here. Where those live we'll start to boil out from there.

Nice thing about a network is custom integration points can live anywhere it makes sense for individual deployments :)

**Comment by btopro** [comment]
dorr has been opened for this thanks to #946 and #954

**Comment by btopro** [comment]
@rickhumphries will be happy to know I've been sold on Competencies being in CIS associated w/ the course and then working it through the whole platform for an eventual dashboard of progression
