### ISSUE TITLE
How to add an instructor to a course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#65]
I can see a few places where I might add this information. In Content>Course>Edit>Administrative there's a dropdown field for Lead Instructor. Similarly in Offering>Edit>Administrative>Teachers there are two dropdown fields for Instructor of record and Teaching assistant. 

In all of these cases the dropdown list doesn't pre-populate with any usernames. Do I need to setup a user with a specific role/permissions in order for them to appear in these dropdown menus? We've changed the names of our different role types now and I can't remember if 'Instructor' was one of them to check!

**Comment by btopro** [comment]
I believe this is currently a bug because it's supposed to have the instructors / TA role'd people in CIS -- admin/structure/types/manage/course/fields

Also, we currently don't do anything with this information in the rest of the system. At the moment, we implement a hook in CIS (example here: https://github.com/btopro/elmsln-config-example/blob/master/shared/drupal-7.x/modules/cis_implementation_example/cis_example_elmsln_cis/cis_example_elmsln_cis.module#L5-L21 ) which then makes sure certain users (our internal staff) all get certain levels of access to newly created systems.

So you can update but I'm guessing this is both a feature request and a bug. Bug being that the users of certain roles don't show up in that list. Feature being the ability to grant instructor / ta / other roles to systems via a console of sorts.

I mentioned we do this via that hook but there's two other methods we use:
-- Our Jenkins robot has scripts that kick off jobs so I can quickly (forcibly) add people to areas, this is because I'm managing multiple elmsln deployments and is both too dev centric and overkill for what you want (most likely)
-- Our LMS Roster sync has instructor and TAs in the data feed so that's how we get them access to the spaces on our end. If a course is in development we'll add them manually, once its off and running they come across in this data-feed.

Future
=====
There's a script that's a side-car to drush-create-site (which actually builds the sites) called drush-command-job (https://github.com/btopro/elmsln/tree/master/scripts/drush-command-job). This is unfinished but the idea is that specialized tasks could be run by this script to do simple command / task execution. For example; We notice that you add an instructor to a course / offering / wherever that happens, we kick off a special job file that says "grant user A access to XYZ with role B". Job is processed and then a notification goes out when its done.

We could also skip that step and use the web-services built into all systems to dynamically request the user entity be created and then roles assigned to it, but that workflow is still up for debate as well since right now we don't allow the web services to query use object data (they could easily, we just don't let them)

**Comment by btopro** [comment]
OOo, looks like there's something up in this view -- admin/structure/views/view/user_type_lists/edit

looking into it now cause I need to pull from CIS who is teaching a course section so I can show it in the new UX.

**Comment by rickhumphries** [comment]
Sure OK - it was less about granting access (although we do need to think about that kind of functionality going forward so I'm glad you mentioned it) but because I was looking ahead at the state of UX video and noticed that there's a space for the instructor under the Syllabus menu. Where were you looking to populate this from?

We've got a bit of a complicated setup in terms of different user roles and just having a think about how we can create an awesome space for everyone (I'll probably come back to you with more ideas and questions on this soon! :) )

**Comment by rickhumphries** [comment]
Haha, just noticed previous comment!

**Comment by btopro** [comment]
Roles cleaned up in what's setup
