### ISSUE TITLE
CIS / global Role review

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#66]
I've nearly gotten sick thinking about this in the past but the bandaid will need ripped off...
Will absolutely need @rickhumphries on this one.

So, because we've effectively changed the scope and goals of CIS via #39 and #40 we need to review another aspect that needs changing. CIS currently has its own role structure. This has presented problems as illustrated most directly in #65 .

Proposed solution:
Review CIS Service Roles listing
https://github.com/btopro/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/features/cis_service_roles/cis_service_roles.info

*Desirable solution (but up for review)*
===============
-- Modify the details surrounding what cis_service_roles is to reflect that it's ELMSLN global, default roles (essentially)
-- Create an update routine for CIS (only) to use the cis_service_roles
-- Systems affected / in need of this update; 1 per deployment, CIS only.
-- Re-export the features in CIS that have RID implications and make sure they point to the same values as everything else
-- IF there are roles that are intentionally unique to CIS, bring them in at install time so they get role IDs higher then those currently in place

Review LTI supported role types (https://github.com/btopro/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/ulmus/lti_tool_provider/lti_tool_provider.module#L325-L338 ) and how they might map though to be honest I really don't like this list but we should at least be able to map each to one of our roles (if we needed to).

List in most of my personal installs:

instructor - obvious
teaching assistant - obvious
student - obvious
administrator - obvious

guest - catch all for someone we want to be able to view as a student would see without being one.
past student - after students are removed via system sync, this role can be used if there's a level of access desired after completion of a course, such as to their submissions while not being able to access anyone else's stuff.
staff - ID / internal staff to the organization
SERVICE ACCOUNT - ELMSLN web service role that accesses data

activation code holder - custom to our org, purchased access to unlock certain things

If there are any other proposed useful default roles then speak now :)

Alternative Apocalypse solution
========================
Come up with a comprehensive list of roles that ALL systems will have in ELMSLN. Use https://www.drupal.org/project/role_export to ensure that RIDs are unique and yet always the same no matter whatever roles might be custom added to instances in the wild. (rid something more like 12394, 37463 instead of 1, 2, 3 based on order they are created which is error prone); this is core in D8 as its effectively a machine_name for the role.

Implications
 -- rid changes from 6 (student we'll say) to 192976
-- all roles need updated to reflect the new method
-- all users need their role updated to reflect the change
-- all role-based features need exported in order to account for this
-- *all views, contexts, field permissions, organic groups, everything; everything utilizing the rid value (which has now changed..) will need to be accounted for in every system ever created and updated
-- everything needs reexported to reflect rid change so that all new things get routed the right place.
-- systems affected: everything ever created, everywhere.

**Comment by rickhumphries** [comment]
I've got fairly limited technical knowledge for this but the Apocalypse solution is still making me wince. 

I'll just describe a bit about the different user roles we have which might give a flavour for the variety of requirements that may be out there and then will put my thoughts at the bottom. Bearing in mind that our org involves work-based training, some of the roles that we've set up but haven't really done anything with yet are:

Student - yep

## Internal Instructors
Some of our larger courses are made up of a knowledge-based component and a competecy-based component, so there are two main roles here; 
* Tutor -  The tutor is the 'instructor' for the knowledge-based component
* Assessor - the assessor is the 'instructor' for the competency-based component
This could probably be treated in the same way as an 'Instructor' and 'Teaching Assistant' but with different labels

## External teachers
* Mentor
* Expert Witness
These two roles are very similar, but essentially they will be the student's manager or senior in the workplace. Their job is to support the student, sign off (and comment on) work submissions before they come to us. They also usually have their own course 'area' where they essentially get put on a 'mentor's course' so that we can give guidance to them on how to effectively support the student.

## External management
* Key account managers - these are pretty much the managers who oversee the training of an entire  company and just want to login and see the numbers! So they would want to filter a table down to see students in a particular grouping and see their progress (we're working on this view for the CIS). They don't get too involved in the actual teaching though.

## Some thoughts
Standardising the role types is a good call. When setting up a course/section it might be worth allowing more users be assigned as part of the 'support team' for a course. Currently there's only Instructor and Teaching Assistant, but you could add any user and assign them with a particular role for that course. This would then show for the student to say 'this is your support team' in the course section with a bit about the roles of each. 

The mentor/expert witness roles are an interesting one, as they essentially need access to two course outlines within the same course. One would be what the student sees and the other would be theirs, with their own information on how to be a mentor. I think there's a staff resources part of the CIS currently which is a bit like this, but I think it would be an interesting idea instead of (or merged with) staff resources, to create more than one book, then let the mentor/instructor select which book they want to see from a menu (a bit like assigning a book to a section then switching sections, but without having to actually create a new section). You could then build out different user guides for different user roles.

Exposing more than one course outline to a user (within the same section) to choose from may have other advantages in different situations too - like building courses within courses that don't necessarily have an end date. Examples of this are courses for Continuing Professional Development where new subject modules are always added, and you would potentially want to build out a course outline for each new subject. 

In terms of mapping to the LTI roles these go fairly well:
Mentor/Expert Witness --> Mentor
Key Account manager --> Manager

**Comment by btopro** [comment]
Going to be messing with this in a VM setup soon; the more I play w/ other parts of the system the more we might need a comprehensive role switcher. This would be painful once and require a lot of testing on my part w/ a lot of configurations but guarantee we never have this conversation again :)

**Comment by btopro** [comment]
action plan:
roles: service roles + admin + service account role (on by default)
dump  SERVICE ACCOUNT role from cis_service_restws
dump admin from ALL INSTALL PROFILES
dump cis_roles_perms thing entirely
export all roles in 1 cis_service_roles feature (or something like this like elmsln_roles
reapply to a site, see what happens, start repairing views and contexts either manually or work on that hook from above (probably from above, lets see what breaks).
reexport all features at this point
kick perms to own thing; defaultconfig style

**Comment by btopro** [comment]
We'll be going with the desired solution because in starting to test and apply its less a big deal then previously expected; I've already identified the variables it screws up (in my own instances even) and then i'll just create an update path for it. I already made an example hook for doing it at the right time as well as an (untested yet) example of fixing the masquerade settings as a result of this change https://www.drupal.org/node/2492377#comment-9945665

Next the other variables, Views are the only biggy but I know how to do it it's just actually accomplishing it. This will bring CIS into alignment with everything else as well as ensure ALL roles made in addition to the ones in setups NEVER can conflict (which is awesome).

**Comment by btopro** [comment]
- [ ] reexport features
- [ ] kick perms to own thing; defaultconfig style
- [ ] test update hooks

**Comment by btopro** [comment]
waiting on test results to close

**Comment by btopro** [comment]
This should be good though we'll still want to do additional testing
