### ISSUE TITLE
FERPA Privacy mode not totally working in critique pages

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#776]
The privacy mode only covers the user's name in the profile link when viewing a studio assignment to leave a comment. The rest of the names (like the one for the title of the video "John Smith's Video Pitch" or the ones that label who has commented) are left clear.

- [x] comment title
- [x] comment poster
- [x] submission title
- [x] submission itself
- [x] comment body text

**Comment by btopro** [comment]
we may need to make the class apply to anythign when a student produced the work. That's a bit aggressive but otherwise we'll be in this same scenario in a few weeks when @kat-wehr says "Oh well there's a person's name in the body field too" or in the ____ field. Comment box suffers this issue as well so we'll need to figure out if we want to obscure title / user's name and the work itself can be there (but then things like videos of faces.... well ya it's a pipedream potentially).

Maybe blur it all but when you mouse over it reduces the blur on that item unless it has some kind of black-list class. For example, blur everything, blacklist user's name / title of their work / comment names but reveal work / comments on mouse-over as you might know ahead of time that that work your going to show doesn't have PII concerns

**Comment by kat-wehr** [comment]
well, in the comment box as long as they're not saying the person's full name I don't see an issue with that. if it's just like "Hey Jimmy, nice video!" i mean there are 100's of Jimmy's at PSU. I would hope that's not a FERPA thing. 
Not to mention that all the student's names and user ID info are all publicly available on the PH... but yeah.

**Comment by btopro** [comment]
1. you don't know that it doesn't say a full name or something identifiable (Ollendyke is a pretty identifiable name)
2. Not everything is public in the PH. ALMOST everything but you still need to know a username / person's name and they have to say that they are listed in that listing (they can request to be removed at any time)

**Comment by btopro** [comment]
@kat-wehr can you email me those screenshots you use in the olc video so I can use that to find the properties to target plz?

**Comment by btopro** [comment]
- [ ] comment title
- [ ] comment poster
- [ ] submission title
- [ ] submission itself
- [ ] comment body text

Think this catches all of them

**Comment by btopro** [comment]
![2016-04-05_07-48-02](https://cloud.githubusercontent.com/assets/329735/14280760/c134ddce-fb02-11e5-85b2-c9880c6c0ac8.png)

**Comment by btopro** [comment]
prev screenshot done in real time
