### ISSUE TITLE
Buttons to run ELMSLN on Amazon and Digital Ocean

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#777]
Can we add buttons on elmsln.org that auto install on Amazon and Digital Ocean? Obviously we should mention that those services cost money. But this would lower the bar to get up and running for some.

In addition, there would need to be a fork button in the UI for each course, called "Fork this Course." Then a student or instructor could self host (transporting/importing properly licensed content automatically.

**Comment by btopro** [comment]
auto install would be tricky without some kind of oAuth token authorization; pages w/ step by step on what to do / optimizing the speed of being able to do it would help for sure.

The fork this course like the `Fork me` flag that's on code sites related to github would be awesome assuming there's a public repo associated with whatever's produced. We could even combine the two at some point and basically make it so that ppl can spawn off new elms stacks w/ a fork of the content to match....

this is getting trippy.

**Comment by btopro** [comment]
Lots more documentation on elmsln.org at this point to automate as much of this as we can. We now support amazon, we've got a 1-line copy and paste builder https://www.elmsln.org/install-guide so this is about as far as is possible now
