### ISSUE TITLE
Redirect loop in mooc/book-homepage callback

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#814]
If the user has a section_context set in the session that the user does not have access to and the user visits the `mooc/book-homepage` page, a redirect loop will occur.

- [x] Prevent the redirect loop from happening
- [x] use cis_connector_sections() to gather a list of sections instead of entity_field_query().  This is due to the fact that entity_field_query() will be affected by field permissions and potentially not return the full listing of sections.

**Comment by btopro** [comment]
So we have an issue to resolve here. Faculty having access to multiple editions of the same course and making it default them correctly. I teach version A of the course but Instructor 2 wants me to be able to review their version B. If I have full access to both it's  race condition as to which I'm delivered as I'll be a group member of both on the OG side. This is fine when your a passive participant / staff / admin because you know you have access to all kinds of things.

If faculty though, the notion of defaulting to another section just because you might need to be able to help were someone to contact you about the alternate version of the course could be confusing; especially if not expecting to view a section.
