### ISSUE TITLE
Suggestions in  issue #818 did not work 

### ISSUE THREAD

**Issue by aryavart** [elmsln/elmsln#820]
Hello sir
In issue no. #818    .....

Your suggestion was  "Type the same username and password again and you'll be logged in. If you made a course that doesn't require a login to access then right now not everything will auto log you in."

I use username and password "admin" and "admin" but it make no change  [ i have not created another account] 

I created new account for new course it say " ACCESS DENIED" 

"IN YOUR YOUTUBE VIDEO when you click Access Service this web Address Appear, "course.elmsln.local/demospace/MOOC/book-toc"

Sir have  activated some modules or configure any settings before making that video'

"I HAVE NOT ACTIVATED ANY MODULE OR CONFIGURED ANY SETTINGS" Is this reason i am facing problems. I am Following Exactly what you did in your videos. 

Please HELP ME OUT I AM STUCK ON FIRST STEP....CANT MOVE AHEAD......

ISSUE #818  information....
[On digitalocean I have 2 GB Ram / 40 Gb 
I have purchased my domain name. 
Installed on digitalocean using oneline installation.

I am facing problem in course creation again and again. And Installation Environment is Same for All. Installation Line is Same and Automated. So these is no question i am doing something wrong or i am missing something. SIR WHEN WHY ONLY I AM FACING UNUSUAL thing in course creation. 

[2] In your "YOUTUBE Video" when you click on "ACCESS SERVICE" YOU GOT THIS "HOME" and Lesson, table of contents etc. Picture BELOW:
![studio4](https://cloud.githubusercontent.com/assets/18336403/14408732/ff51713e-ff1d-11e5-8dac-2249f6d2fda0.png)

But when i click on "ACCESS SERVICE" i get this "USER ACCOUNT" Picture BELOW:
![studio3](https://cloud.githubusercontent.com/assets/18336403/14408733/0749e0ec-ff1e-11e5-92bd-2e76c3d7294f.png)

ALL things are same for all then why i am facing this situation.

**Comment by btopro** [comment]
Not sure

**Comment by aryavart** [comment]
Sir, i am operating my website with WINDOWS 10 laptop. May this be a reason i am facing huge problems. 
Sir you may be Super busy, i can understand, managing such a huge network, 
Can anybody else who have some  time and  help me out. 
Can you suggest me any name. 

I am unable to Start my website. No work. Totaly Blank.

**Comment by btopro** [comment]
we are super busy, but you're also describing problems that are basically just the way the system is at this point. As I said earlier, this is a 0.2.1 release. Less then a 1.0.0 and all aspects of the course network are finished. There is much work left to be done, and you are experiencing that. Typical courses we run off this system use the CIS to setup the courses, the Course outline and Studio tools. We then use Interact / Media to sprinkle right interactive material throughout the Course content outline. Discussions and Blog are still pretty early on in production usage. The issues you mention with accounts are expressed through other threads and in documentation on how to resolve -- http://elmsln.readthedocs.org/en/latest/

The course outline tool has the most work put into it by far and there are many videos on elmsln.org showing things produced with it. We have people working on end user documentation now among other things. It's not the easiest thing to be trying to build an organic, self replicating, expansive network of distributed things on a shoe-string budget but yet here we are.

For gaining access to new sites / systems that didn't automatically log you in you can use leafy / drush, the commandline task runners to gain access. This is built on Drupal so that we can leverage that community so if you know Drupaly concepts then they translate here. if you don't, this probably isn't for you yet as there's still much code to be written and bugs to be worked out.

I recommend you play with the demo space and see if this is for you. If it's not, then there's been no reason debugging any of this.
