### ISSUE TITLE
navigation visible in upper part of screen

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#838]
Can we have "back" / "next buttons or arrows that are visible at the top of the screen so if there is a lot of content or students are unaware of the ability to use their arrows, they can "see" the nav to get to the next pages.

**Comment by btopro** [comment]
I think we should have the option added back. I'll say they used to be in there and we removed them based on usage / clutter

**Comment by btopro** [comment]
Since this issue was filed we now have breadcrumb (active trail: Module / lesson) as well as a block on both left and right sides of the content. Left is where they are currently in the active path (current chapter / lesson w/ pages shown before and after what's coming up). Right side has scrollspy which turns headings into links.

Both of these suggest "what's coming up next / where have I been" as well as "oh there's actually a bunch of stuff here". This leaves Next / Prev as the fallback almost.

Closing out, open again if this becomes an issue once new UI stuff gets pushed out.
