### ISSUE TITLE
Learning Portal: transition space to prepare for learning 

### ISSUE THREAD

**Issue by kmiffitt** [elmsln/elmsln#851]
Inspired by article on [designing for happiness](http://www.fastcodesign.com/3058237/innovation-by-design/how-to-design-happiness), I'd like to work on a "learning portal" - a transition "space" that students enter the course pages through that helps them transition to the activity. 

Not much is sketched out right now, but I could imagine a widget-y approach that includes some sort of motivational quote/video, an area where students can set mini-goals (I want to review for 20 min), maybe an area where they can see how many other students are logged in, etc.

**Comment by btopro** [comment]
So maybe like a dashboard of some kind or a type of dashboard for the course. You could have like a story arch driven dashboard w/ question / framing of the day or another one that introduces you to a random topic / next topic? Could also play well with the #640 idea in that you could visualize it and get different inspiration based on what pathway you were forming.

**Comment by rickhumphries** [comment]
Yeh with the random/next topic thing there's a lot of potential for that. It could either, based on parameters you set:
*Show the next topic in the course (if linear course pathway)
*Show the next topic an instructor wants the students to do. So they manually choose the next topic and push this out to students in a particular section
*Shows an automatically recommended topic based on the taxonomy meta data of the topic and the student's 'competency/skill profile'. (thinking about LOR here). So if there's certain objectives in the course the student hasn't covered yet, the system would be like 'oh, well completing this topic would cover those missing objectives'

**Comment by btopro** [comment]
sounds related to #842 almost, be like a dashboard for the course itself as opposed to all courses across the network

**Comment by btopro** [comment]
#847 time to take in material and the way I've got it structured (data-wise) could also be a useful thing for this frame of reference into the course idea. It pulls together how many words (then words / minute to get duration), images, videos, audio files, etc are included on all the pages below the current one.

Using this idea, we could have a dashboard be on the section which knows about the top of the course outline (which is then specific per section so there could be variability per section / different 'hey heres whats up' style data per section of the course / offering of the course that is).
- The top of the course will know how long the course is to take, how much media there is etc (a good starting point for a dashboard).
- Learning Locker knows where you last were (or drupal technically as well) so we know where you left off / what you have next to work on
- we also know how much each grouping of material has in it so we'd know your progression through the current thing you are working on
- goal setting / suggesting could be aligned with this; we'd know "hey you are in week 6 (that data comes from CIS as to when it starts)", you've experienced 10 hours of content so far, you've got 4 hours in the up-coming less you've started; you may want to portion out 1.5 hours a day to keep on pace (cause we know it's currently Wed)
- From here, other analytics from learning locker / engagement / etc would start to make sense to pull together here
- Instructors / Staff can be presented slightly different dashboards based on the things they'd care about in this instance; Staff care about the last time there were quality audits, the fact that this course they are viewing is about 50% as much content as the average of other courses (duration to complete + activities per course / courses) and could also highlight that Lesson 8 is only 75% the material of Lesson 7 and 9 so maybe a rebalancing should be looked at
- This then (for staff) brings things together from a setup perspective because it now makes sense to provide you options about what you can do next like setup more sections/offerings (as well as show what you last did in working with this course so you remember where you left off in the building process)
Really, if done correctly and starting with a data-first approach, could unify a lot of other outstanding issues, especially staff UX when it comes to setting things up and getting in the right frame of mind to start work on a course. Faculty are an extension from there
Related
#842
#550 
#1134

**Comment by btopro** [comment]
#1251 adding field to data model for competencies at the assignment level

**Comment by btopro** [comment]
@kmiffitt been looking through some different visualization libraries which would be required for this as well as the data visualization improvement stuff. https://www.webcomponents.org/element/Collaborne/d3-progress-meter may not be the exact implementation but it's a very nice (easy for us to sustain) dashboard gauge. Could see this as part of a sort of "How I think I'm doing" or "Goals i've met" which as you check them off these gauges update
