### ISSUE TITLE
Where to put the Quiz module

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#899]
wrote up the combo here; still early but incredibly promising https://groups.drupal.org/node/511171

As a result, we need to have a discussion about where the quiz module should live. If it's in the content for keeping in the flow (which there are pros and cons to) or if it's in one of the existing systems (like interact or assessment which currently isn't used) and then is embedded in or what the best home for it is.

Quiz, H5P (videos especially) and page views are all able to be captured as XAPI statements with simple setup currently (which we can script much of to go a step further). So it's time to start talking quiz as we have a perfect training course to drive the use-case / interfaces for it. It's a matter of where this lives and how we aggregate it since it has it's own reporting / interfaces internally (Quiz 5.x is entity capable and MUCH better structurally then past versions) but it also ships statements to Learning locker. This means that we could present data local to a course without asking the LRS but then also aggregate all testing of a student from the LRS, allowing for more flexibility in displays across courses / for a dashboard.

**Comment by rickhumphries** [comment]
I see Quiz Module as being part of its own Assessment system as I think there's HUGE area to be built on here. The assessment system would have a specific role for more formal assessments involving long answer questions that need to be submitted to instructors for marking. Within that scope you would also have space to build out an area for course instructors to manage the submission of student's tests and grade them more efficiently and effectively. e-Assessment is a pretty big area so I can see it needing it's own system.

I know in the work-based training world, a lot of students have work-based tutors who may be in a more senior role and act as a mentor. When a submission is made it will be looked at by the mentor who will make comments and 'sign it off' before it then comes to us for official marking. Those types of functions and granularity just seem to fit best within its own system. 

Since the quiz module can send xAPI statements, that still gives us the opportunity to affect aspects of the course site visually (hiding/showing nodes, or showing content as 'complete') by querying those statements. 

Less-formal 'knowledge-check' quizzes can typically be done with H5P for embedding within course materials anyway, so I feel that lessens the need for a dedicated quiz module within the course site itself

**Comment by btopro** [comment]
@rickhumphries would you mind making a simple flow chart of how you'd see this playing out? Like series of pages, quiz on page 5 that's delivered from assessment kind of thing. Be good to start having some visuals from all of us to illustrate what's possible.

I agree that it probably needs thrown somewhere else BUT quiz (specifically) operates by making a question bank of every question created in the site its in then you pick the questions you want for the quiz at that time. This hopefully will play well with OG / section / Course filtering / entity references but we'll have to see. It should at least (just complicates things)

**Comment by rickhumphries** [comment]
@btopro will do!

**Comment by btopro** [comment]
Ok, it's in assessment now w/ a basic link to get there. That was the point of this issue, not to solve the world's testing issues / configure this (yet). We will be using this in the Fall so it'll see expansion in usability over the summer / sprints in the near future.
