### ISSUE TITLE
Using 'Course Title' field across systems

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#934]
When setting up a course in the CIS, two of the fields are 'Name' which tends to be used more as a course code or short form name, and the 'Course title' which is used as the long name. 

In most cases (or maybe it's just us!) the 'course title' is the only one that's actually really readable. In Media it would be great if the Course title were to be carried over to the course content created there too so you are able to display the course title next to the name in different views etc. I'm not sure if this is the case with other systems too?

**Comment by btopro** [comment]
this is one of the main benefits from all the work in 0.3.1 which isn't ready for prime time yet (hence no tagged release). I believe it's in 0.3.0 but I don't recommend switching to it yet as we're doing a lot of internal testing (I have a production mirror and keep iterating over upgrade routines and watching how the data propagates). 0.3.1 + changes the way data propagates for greater scale. In order to do that though it needs greater reliance on the network being stable. For example, if you update the course name in courses, it will update in studio, interact, media, CIS, etc and do so without invoking a scale penalty (easy to spider that command, harder to snake but more scalable) https://drupal.psu.edu/blog/post/web-service-requests-snakes-and-spiders is mostly around this subject though it then leads to greater ability for user, course and section data to stay in sync everywhere AutoMagically.

Current testing is very promising on my prod instance which is the largest deploy known of (83+ courses, 230+ sections, 3000 or so user accounts). Making sure that the load is distributed correctly and that we have greater assurances that the data will flow everywhere correctly. The issue with snake calls (unless they have checks) is that all this data model technically syncs (potentially) in CIS, then Interact, then Media, then People. If that's the case, and Interact is screwed up / not available / whatever, the call currently will just bomb completely on Media / People (cause interact had to do the push).  An alternate strategy might be somewhere between snakes and spiders, a snake data flow but that's always routing back through CIS for data assurance. We'll see, much longer answer then you expected probably ;)

**Comment by rickhumphries** [comment]
haha yeh just a bit. So from what you've said, the data will sync better between systems, which is awesome. But, just to clarify, the course content type that syncs in other systems will also have the 'Course title' as a field as well as 'Name'?

![image](https://cloud.githubusercontent.com/assets/4973810/15784032/a491bb9a-29a8-11e6-8ed0-f3c311df9146.png)

**Comment by btopro** [comment]
currently authorities don't have this field but it could be added, right now CIS and the services are the only things storing / tracking that.

**Comment by btopro** [comment]
related issue for enhancement mentioned #935
