### ISSUE TITLE
Document patch made to h5p_tincan_bridge module

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#974]
`core/dslmcode/shared/drupal-7.x/modules/ulmus/h5p_tincan_bridge/h5p_tincan_bridge.js`

needs it's patch submitted to the https://www.drupal.org/project/h5p_tincan_bridge issue queue

The patch allows for other projects to jump in and pass data downstream via $_POST so that they can ship custom properties / data to act upon later on.

**Comment by mmilutinovic1313** [comment]
I am creating another patch for the module on d.o. then? I am assuming this patch is different from the patch at https://www.drupal.org/node/2745313 that you had submitted earlier.

**Comment by btopro** [comment]
yeah different then that, its in the js file

**Comment by mmilutinovic1313** [comment]
Sent patch to d.o. I used your message and title for description. Their version has different code than ours (probably because we have 2 patches in that dir already). Do you want me to make an elms specific patch for that folder? Or just put the one I added to d.o. in that folder? 

https://www.drupal.org/node/2755205

**Comment by mmilutinovic1313** [comment]
Adding the d.o. patchfile in a PR in master
