### ISSUE TITLE
Investigate ngApp module

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#977]
https://www.drupal.org/project/ngapp looks VERY promising as we move everything towards angular

**Comment by mmilutinovic1313** [comment]
Got it installed now in my materialize branch. Checking to see if it hooks into Libraries / if it makes other things we want Angular to do easier. Updates to come.

**Comment by mmilutinovic1313** [comment]
So @heyMP and I have talked about using this module. Although we think it's cool and could have some benefits, it causes more hassle than good. This module wants us to abstract angular to switch out the REST delivery method (RESTws for Services). We don't really care about this, so it complicates things too much. Additionally, the CDN implementation for Angular would work best if we wrote an API to handle it, instead of plugging in random CDNs into the modules settings. It would also be inconvenient to load Angular Locally via this module. If we implement, we should abstract the few good parts of the module that meet our current development strategy.

**Comment by btopro** [comment]
Good to know. closing out
